PATCH https://awlservices.ptw.com/base/users/38522b95-7d5c-4a14-8c81-6dae6402c2e0/deactivate/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyTmFtZSI6InVzZXIzIiwiZXhwIjoxNTkzMDc1NjQxfQ.LnkpEtOjqp-Ik1SAh39MUt9xC20ClgWsVMPOEvHbsmc