export default {
  response: {
    count: 2,
    next: null,
    previous: null,
    result: [
      {
        createdOn: '2022-02-04',
        updatedOn: '2022-02-04T15:11:08',
        createdBy: 21,
        firstName: 'Surya',
        lastName: 'teja',
        emailId: 'surya1@ptw.com',
        mobileNumber: null,
        linkedInUrl: null,
        conversionNote: null,
        ownerId: 21,
        countryId: 34,
        cityId: 51,
        convertedById: 21,
        leadLocation: null,
        additionalInfo: null,
        isReview: true,
        isContact: true,
        isExclusion: false,
        id: 465,
        designation: 'asdf',
        address1: null,
        address2: null,
        address3: null,
        pincode: null,
        comment: 'dfs',
        ownerName: 'Jaya Surya',
        name: 'Surya teja',
        createdByName: 'Jaya Surya',
        convertedByName: 'Jaya Surya',
        city: {
          id: 51,
          name: 'Taipei',
          stateId: 50,
          state: 'Taiwan',
        },
        country: {
          id: 34,
          name: 'Taiwan',
          regionId: 7,
          region: 'Asia',
        },
        gender: null,
        status: {
          id: 36,
          name: 'InActive',
        },
        crmSource: {
          id: 20,
          name: 'Offline',
        },
        crmSourceGroup: null,
        hearAboutUs: null,
        clientType: null,
        crmCompany: {
          id: 429,
          name: 'newAcc67',
          website: null,
          employeeCount: null,
          annualRevenue: null,
          country: {
            id: 35,
            name: 'Japan',
            regionId: 7,
            region: 'Asia',
          },
          city: {
            id: 53,
            name: 'Entalize',
            stateId: 51,
            state: 'Tokyo',
          },
          address1: null,
          address2: null,
          address3: null,
          pincode: null,
          financeId: null,
          currency: {
            id: 141,
            name: 'Yemeni Rial',
          },
          marketType: {
            id: 241,
            name: 'Non-Games',
          },
          industry: {
            id: 9,
            name: 'Entertainment',
          },
          owners: [
            {
              userId: 120003204,
              name: 'Naresh Singh',
              regions: [
                {
                  id: 9,
                  name: 'APAC',
                },
              ],
              departments: [
                {
                  id: 318,
                  name: 'check edit dep',
                  code: 'ed345',
                },
              ],
            },
            {
              userId: 120003203,
              name: 'thota venkat test',
              regions: [
                {
                  id: 9,
                  name: 'APAC',
                },
              ],
              departments: [
                {
                  id: 318,
                  name: 'check edit dep',
                  code: 'ed345',
                },
              ],
            },
            {
              userId: 120003202,
              name: 'Ramesh Kumar',
              regions: [
                {
                  id: 4,
                  name: 'EMEA',
                },
              ],
              departments: null,
            },
            {
              userId: 120003199,
              name: 'praveen99 kumar',
              regions: [
                {
                  id: 5,
                  name: 'North America',
                },
              ],
              departments: null,
            },
          ],
          clientType: {
            id: 290,
            name: 'Third Party',
          },
          isApproved: true,
        },
        campaigns: null,
        services: null,
      },
      {
        createdOn: '2022-02-04',
        updatedOn: '2022-02-04T11:08:54',
        createdBy: 21,
        firstName: 'CoversionTestLead1',
        lastName: null,
        emailId: 'conversionTest@gmail.com',
        mobileNumber: null,
        linkedInUrl: null,
        conversionNote: null,
        ownerId: 21,
        countryId: 35,
        cityId: 54,
        convertedById: 21,
        leadLocation: null,
        additionalInfo: null,
        isReview: true,
        isContact: true,
        isExclusion: false,
        id: 461,
        designation: 'asdfsdfasdf',
        address1: null,
        address2: null,
        address3: null,
        pincode: null,
        comment: null,
        ownerName: 'Jaya Surya',
        name: 'CoversionTestLead1',
        createdByName: 'Jaya Surya',
        convertedByName: 'Jaya Surya',
        city: {
          id: 54,
          name: 'Japan',
          stateId: 52,
          state: 'Japan',
        },
        country: {
          id: 35,
          name: 'Japan',
          regionId: 7,
          region: 'Asia',
        },
        gender: null,
        status: {
          id: 18,
          name: 'Active',
        },
        crmSource: null,
        crmSourceGroup: {
          id: 274,
          name: 'Campaign',
        },
        hearAboutUs: null,
        clientType: null,
        crmCompany: {
          id: 427,
          name: 'conversionTestAcc',
          website: null,
          employeeCount: null,
          annualRevenue: null,
          country: {
            id: 35,
            name: 'Japan',
            regionId: 7,
            region: 'Asia',
          },
          city: {
            id: 53,
            name: 'Entalize',
            stateId: 51,
            state: 'Tokyo',
          },
          address1: null,
          address2: null,
          address3: null,
          pincode: null,
          financeId: null,
          currency: {
            id: 141,
            name: 'Yemeni Rial',
          },
          marketType: {
            id: 241,
            name: 'Non-Games',
          },
          industry: {
            id: 9,
            name: 'Entertainment',
          },
          owners: [
            {
              userId: 21,
              name: 'Jaya Surya',
              regions: [
                {
                  id: 7,
                  name: 'LATAM',
                },
                {
                  id: 9,
                  name: 'APAC',
                },
              ],
              departments: null,
            },
          ],
          clientType: {
            id: 291,
            name: 'Affiliated Developer',
          },
          isApproved: true,
        },
        campaigns: null,
        services: null,
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/crm/crmcontacts/',
};
