export default {
  response: [
    {
      createdOn: '2022-01-18T04:28:11',
      updatedOn: '2022-01-18T04:28:11',
      isActive: true,
      createdBy: 4,
      employeeCount: 271,
      emailId: 'Aaron.Graham80@gmail.com',
      cityId: null,
      countryId: null,
      isApproved: true,
      parentCompanyId: null,
      phoneNumber: '679-975-2853',
      isStrategic: false,
      id: 1697,
      name: 'Bednar - Schroeder',
      website: 'http://kathleen.name',
      pincode: null,
      address1: '45569 Ledner Road',
      address2: 'Rutherford River',
      address3: null,
      finance: null,
      parentComapnyName: null,
      createdByName: 'Avinash Koonapareddy',
      leadSourceGroup: null,
      conversionNote: null,
      currency: {
        id: 14,
        name: 'Euros',
      },
      annualRevenue: {
        id: 52,
        name: 'above 200 mn',
      },
      marketType: {
        id: 414,
        name: 'Non-Games',
      },
      city: null,
      country: null,
      industry: {
        id: 9,
        name: 'Entertainment',
      },
      clientType: null,
      owners: [
        {
          userId: 21,
          name: 'ramu k',
          regions: [
            {
              id: 7,
              name: 'Asia',
            },
          ],
          departments: null,
        },
      ],
      billingEntities: null,
      services: [
        {
          id: 33,
          name: 'SUO Services',
        },
      ],
    },
    {
      createdOn: '2022-01-17T11:50:45',
      updatedOn: '2022-01-17T11:50:45',
      isActive: true,
      createdBy: 1723,
      employeeCount: null,
      emailId: null,
      cityId: 51,
      countryId: 34,
      isApproved: true,
      parentCompanyId: 1681,
      phoneNumber: '5634753',
      isStrategic: false,
      id: 1696,
      name: 'child trans',
      website: null,
      pincode: null,
      address1: null,
      address2: null,
      address3: null,
      finance: 'fg4236',
      parentComapnyName: 'Trans',
      createdByName: 'Sushmita Rokhade',
      leadSourceGroup: null,
      conversionNote: null,
      currency: {
        id: 14,
        name: 'Euros',
      },
      annualRevenue: {
        id: 49,
        name: '1 to 10 mn',
      },
      marketType: {
        id: 414,
        name: 'Non-Games',
      },
      city: {
        id: 51,
        name: 'Taipei',
      },
      country: {
        id: 34,
        name: 'Taiwan',
      },
      industry: {
        id: 10,
        name: 'Education',
      },
      clientType: {
        id: 452,
        name: 'Self-Publishing Developer',
      },
      owners: [
        {
          userId: 1723,
          name: 'Sushmita Rokhade',
          regions: [
            {
              id: 7,
              name: 'Asia',
            },
            {
              id: 6,
              name: 'APAC',
            },
            {
              id: 5,
              name: 'Europe',
            },
          ],
          departments: null,
        },
      ],
      billingEntities: null,
      services: null,
    },
    {
      createdOn: '2022-01-14T12:28:10',
      updatedOn: '2022-01-14T12:28:10',
      isActive: true,
      createdBy: 4,
      employeeCount: 1341,
      emailId: 'Amira96@hotmail.com',
      cityId: null,
      countryId: null,
      isApproved: true,
      parentCompanyId: 1690,
      phoneNumber: '906-754-5056',
      isStrategic: false,
      id: 1694,
      name: 'Borer, Feest and Cassin',
      website: 'https://stevie.info',
      pincode: null,
      address1: '0991 Jimmie Islands',
      address2: 'Heber Fort',
      address3: null,
      finance: null,
      parentComapnyName: 'Johnson Group',
      createdByName: 'Avinash Koonapareddy',
      leadSourceGroup: null,
      conversionNote: null,
      currency: {
        id: 14,
        name: 'Euros',
      },
      annualRevenue: {
        id: 52,
        name: 'above 200 mn',
      },
      marketType: {
        id: 414,
        name: 'Non-Games',
      },
      city: null,
      country: null,
      industry: {
        id: 9,
        name: 'Entertainment',
      },
      clientType: null,
      owners: [
        {
          userId: 21,
          name: 'ramu k',
          regions: [
            {
              id: 7,
              name: 'Asia',
            },
          ],
          departments: null,
        },
      ],
      billingEntities: null,
      services: [
        {
          id: 33,
          name: 'SUO Services',
        },
      ],
    },
    {
      createdOn: '2022-01-14T06:13:04',
      updatedOn: '2022-01-14T06:13:04',
      isActive: true,
      createdBy: 4,
      employeeCount: 23232,
      emailId: null,
      cityId: 51,
      countryId: 34,
      isApproved: true,
      parentCompanyId: 1692,
      phoneNumber: '343432',
      isStrategic: false,
      id: 1692,
      name: 'Disney Games',
      website: 'http://www.disney.in',
      pincode: null,
      address1: 'Hyd',
      address2: 'Ind',
      address3: null,
      finance: '23232',
      parentComapnyName: 'Disney Games',
      createdByName: 'Avinash Koonapareddy',
      leadSourceGroup: null,
      conversionNote: null,
      currency: {
        id: 14,
        name: 'Euros',
      },
      annualRevenue: {
        id: 52,
        name: 'above 200 mn',
      },
      marketType: {
        id: 414,
        name: 'Non-Games',
      },
      city: {
        id: 51,
        name: 'Taipei',
      },
      country: {
        id: 34,
        name: 'Taiwan',
      },
      industry: {
        id: 9,
        name: 'Entertainment',
      },
      clientType: {
        id: 453,
        name: 'Third Party',
      },
      owners: [
        {
          userId: 4,
          name: 'Avinash Koonapareddy',
          regions: [
            {
              id: 7,
              name: 'Asia',
            },
          ],
          departments: [
            {
              id: 26,
              name: 'Art Production',
              code: 'Art Prod',
            },
          ],
        },
        {
          userId: 2840,
          name: 'Anirudh Chandran',
          regions: [],
          departments: null,
        },
      ],
      billingEntities: null,
      services: null,
    },
  ],
  endPoint: 'https://gateway.ptw.com/dev/crm/crmcompany/',
};
