export default {
  response: {
    count: 2,
    next: null,
    previous: null,
    result: [
      {
        firstName: 'kij',
        lastName: 'jjk',
        emailId: null,
        contactNumber: null,
        uniqueId: 'KIJJJK00001',
        viewCount: 25,
        nativeLanguages: {},
        nativeAccents: {},
        nativeSpotlight: null,
        billType: 'Tier1',
        playingAge: {},
        voiceTypes: {},
        gameTypes: {},
        unionLinked: false,
        unionDate: null,
        id: 66,
        gender: 'Male',
        age: null,
        status: 'Active',
        accents: {},
        studios: {
          8: 'Cinemata',
        },
        languages: {},
        filepath: null,
        filename: null,
        tags: {},
        image: null,
        talentDocs: [
          {
            id: 23,
            name: 'test',
            filename: 'po_download_1659335499908.pdf',
            filepath:
              'talent/docs/66/po_download_16593354999082022-09-14_11-42-52_AM.pdf',
          },
        ],
        talentAgents: [
          {
            agentId: 9,
            agentName: 'Jobs',
            agentStatus: 'Active',
            isPrimary: true,
            category: 'Agent',
            country: 'Albania',
            city: 'Lushnje',
            postCode: null,
            contacts: [
              {
                id: 15,
                name: 'sdfsdf',
                email: 'sdf@2hh.com',
                phone: null,
                primary: true,
              },
            ],
            lastPO: '2022-09-26',
          },
          {
            agentId: 7,
            agentName: 'hh',
            agentStatus: 'Active',
            isPrimary: false,
            category: 'Agent',
            country: 'Afghanistan',
            city: 'Khanabad',
            postCode: null,
            contacts: [
              {
                id: 14,
                name: 'test',
                email: 'jjj@kk.com',
                phone: '22222552',
                primary: true,
              },
            ],
            lastPO: '2022-09-23',
          },
        ],
        availability: null,
        longlist: [39, 40, 44, 9],
        shortlist: null,
        voiceclips: [],
        talentReviews: [],
        session_notes_talent: [88, 95, 101],
        purchaseOrder: [
          {
            id: 88,
            poNumber: 'Ban-89-PH',
            project: 'Stranger Things',
            projectId: 34,
            milestoneId: 17,
            agent: 'Jobs',
            agentId: 9,
          },
          {
            id: 86,
            poNumber: 'Ban-87-NA',
            project: 'Cyclone test',
            projectId: 3,
            milestoneId: 14,
            agent: 'hh',
            agentId: 7,
          },
          {
            id: 78,
            poNumber: 'Ban-79-PH',
            project: 'Stranger Things',
            projectId: 34,
            milestoneId: 17,
            agent: 'hh',
            agentId: 7,
          },
        ],
        castingNotes: [],
        talentProjects: [
          {
            projectId: 34,
            project: 'Stranger Things',
          },
          {
            projectId: 3,
            project: 'Cyclone test',
          },
        ],
      },
      {
        firstName: 'Honda',
        lastName: 'Start',
        emailId: null,
        contactNumber: null,
        uniqueId: 'HONSTA00001',
        viewCount: 131,
        nativeLanguages: {},
        nativeAccents: {},
        nativeSpotlight: null,
        billType: 'Tier2',
        playingAge: {},
        voiceTypes: {
          5: 'Animation',
          6: 'Breathy',
          7: 'Croaky',
        },
        gameTypes: {},
        unionLinked: false,
        unionDate: null,
        id: 58,
        gender: 'Male',
        age: null,
        status: 'Active',
        accents: {
          7: 'Antigua',
          14: 'Add',
          24: 'Accent Native',
        },
        studios: {
          8: 'Cinemata',
        },
        languages: {
          1: 'English Uk',
          5: 'Dutch',
          14: 'French',
          15: 'Arebic',
        },
        filepath: 'talent/docs/58/holidays (17)2022-07-05_01-15-31_PM.png',
        filename: 'holidays (17).png',
        tags: {},
        image:
          'iVBORw0KGgoAAAANSUhEUgAAAg0AAAINCAYAAAC9GEyUAAAAAXNSR0IArs4c6QAAIABJREFUeF7t3Qe4JGWZNuAiqauuAq5IMq+IgLIyEiQOGRERJQqShAUkDCBBMo7kHCRnRMmgiyQJCggoICCiIuD6q8iKoosKrqAo//VVTdX0zPTMec4MTOq7rotr6nS/Xf3VXS+nn1OpZ6lMBAgQIECAAIFAYJagRgkBAgQIECBAoBIaNAEBAgQIECAQCQgNEZMiAgQIECBAQGjQAwQIECBAgEAkIDRETIoIECBAgAABoUEPECBAgAABApGA0BAxKSJAgAABAgSEBj1AgAABAgQIRAJCQ8SkiAABAgQIEBAa9AABAgQIECAQCQgNEZMiAgQIECBAQGjQAwQIECBAgEAkIDRETIoIECBAgAABoUEPECBAgAABApGA0BAxKSJAgAABAgSEBj1AgAABAgQIRAJCQ8SkiAABAgQIEBAa9AABAgQIECAQCQgNEZMiAgQIECBAQGjQAwQIECBAgEAkIDRETIoIECBAgAABoUEPECBAgAABApGA0BAxKSJAgAABAgSEBj1AgAABAgQIRAJCQ8SkiAABAgQIEBAa9AABAgQIECAQCQgNEZMiAgQIECBAQGjQAwQIECBAgEAkIDRETIoIECBAgAABoUEPECBAgAABApGA0BAxKSJAgAABAgSEBj1AgAABAgQIRAJCQ8SkiAABAgQIEBAa9AABAgQIECAQCQgNEZMiAgQIECBAQGjQAwQIECBAgEAkIDRETIoIECBAgAABoUEPECBAgAABApGA0BAxKSJAgAABAgSEBj1AgAABAgQIRAJCQ8SkiAABAgQIEBAa9AABAgQIECAQCQgNEZMiAgQIECBAQGjQAwQIECBAgEAkIDRETIoIECBAgAABoUEPECBAgAABApGA0BAxKSJAgAABAgSEBj1AgAABAgQIRAJCQ8SkiAABAgQIEBAa9AABAgQIECAQCQgNEZMiAgQIECBAQGjQAwQIECBAgEAkIDRETIoIECBAgAABoUEPECBAgAABApGA0BAxKSJAgAABAgSEBj1AgAABAgQIRAJCQ8SkiAABAgQIEBAa9AABAgQIECAQCQgNEZMiAgQIECBAQGjQAwQIECBAgEAkIDRETIoIECBAgAABoUEPECBAgAABApGA0BAxKSJAgAABAgSEBj1AgAABAgQIRAJCQ8SkiAABAgQIEBAa9AABAgQIECAQCQgNEZMiAgQIECBAQGjQAwQIECBAgEAkIDRETIoIECBAgAABoUEPECBAgAABApGA0BAxKSJAgAABAgSEBj1AgAABAgQIRAJCQ8SkiAABAgQIEBAa9AABAgQIECAQCQgNEZMiAgQIECBAQGjQAwQIECBAgEAkIDRETIoIECBAgAABoUEPECBAgAABApGA0BAxKSJAgAABAgSEBj1AgAABAgQIRAJCQ8SkiAABAgQIEBAa9AABAgQIECAQCQgNEZMiAgQIECBAQGjQAwQIECBAgEAkIDRETIoIECBAgAABoUEPECBAgAABApGA0BAxKSJAgAABAgSEBj1AgAABAgQIRAJCQ8SkiAABAgQIEBAa9AABAgQIECAQCQgNEZMiAgQIECBAQGjQAwQIECBAgEAkIDRETIoIECBAgAABoUEPECBAgAABApGA0BAxKSJAgAABAgSEBj1AgAABAgQIRAJCQ8SkiAABAgQIEBAa9AABAgQIECAQCQgNEZMiAgQIECBAQGjQAwQIECBAgEAkIDRETIoIECBAgAABoUEPECBAgAABApGA0BAxKSJAgAABAgSEBj1AgAABAgQIRAJCQ8SkiAABAgQIEBAa9AABAgQIECAQCQgNEZMiAgQIECBAQGjQAwQIECBAgEAkIDRETIoIECBAgAABoUEPECBAgAABApGA0BAxKSJAgAABAgSEBj1AgAABAgQIRAJCQ8SkiAABAgQIEBAa9AABAgQIECAQCQgNEZMiAgQIECBAQGjQAwQIECBAgEAkMMtLL730UlSpiAABAgQIEBhoAaFhoDe/lSdAgAABArmA0JBbqSRAgAABAgMtIDQM9Oa38gQIECBAIBcQGnIrlQQIECBAYKAFhIaB3vxWngABAgQI5AJCQ26lkgABAgQIDLSA0DDQm9/KEyBAgACBXEBoyK1UEiBAgACBgRYQGgZ681t5AgQIECCQCwgNuZVKAgQIECAw0AJCw0BvfitPgAABAgRyAaEht1JJgAABAgQGWkBoGOjNb+UJECBAgEAuIDTkVioJECBAgMBACwgNA735rTwBAgQIEMgFhIbcSiUBAgQIEBhoAaFhoDe/lSdAgAABArmA0JBbqSRAgAABAgMtIDQM9Oa38gQIECBAIBcQGnIrlQQIECBAYKAFhIaB3vxWngABAgQI5AJCQ26lkgABAgQIDLSA0DDQm9/KEyBAgACBXEBoyK1UEiBAgACBgRYQGgZ681t5AgQIECCQCwgNuZVKAgQIECAw0AJCw0BvfitPgAABAgRyAaEht1JJgAABAgQGWkBoGOjNb+UJECBAgEAuIDTkVioJECBAgMBAC8zyxBNPvDTQAlaeAAECBAgQiASEhohJEQECBAgQIODwhB4gQIAAAQIEIgGhIWJSRIAAAQIECAgNeoAAAQIECBCIBISGiEkRAQIECBAgIDToAQIECBAgQCASEBoiJkUECBAgQICA0KAHCBAgQIAAgUhAaIiYFBEgQIAAAQJCgx4gQIAAAQIEIgGhIWJSRIAAAQIECAgNeoAAAQIECBCIBISGiEkRAQIECBAgIDToAQIECBAgQCASEBoiJkUECBAgQICA0KAHCBAgQIAAgUhAaIiYFBEgQIAAAQJCgx4gQIAAAQIEIgGhIWJSRIAAAQIECAgNeoAAAQIECBCIBISGiEkRAQIECBAgIDToAQIECBAgQCASEBoiJkUECBAgQICA0KAHCBAgQIAAgUhAaIiYFBEgQIAAAQJCgx4gQIAAAQIEIgGhIWJSRIAAAQIECAgNeoAAAQIECBCIBISGiEkRAQIECBAgIDToAQIECBAgQCASEBoiJkUECBAgQICA0KAHCBAgQIAAgUhAaIiYFBEgQIAAAQJCgx4gQIAAAQIEIgGhIWJSRIAAAQIECAgNeoAAAQIECBCIBISGiEkRAQIECBAgIDToAQIECBAgQCASEBoiJkUECBAgQICA0KAHCBAgQIAAgUhAaIiYFBEYPIGzzz2/OuKoYyZY8V132akq/7XTL3/5q3p2y23+s/73VXPMUX35gnPr+Xnf8pYh4W665da6Zocddxmn9uPrrlP/fMKxRw+5DAUECEwdAaFh6jgPxLt875576/XcdPOthlzfOeaYo65564ILViutuHw9v9Nnt6/mnnvuev6j636ieuSnjw65nEkVtB9YT/32txMtO+KwL9bPbbzhBl3N3d/9Xj3/6S0/0z321S+fX314maW7n8sHapn6fajefOO11bvf9a5Jjj2xWnqpJetlXPKVC6sDDvpCPX/xpZdPcrmHjD642uxTG0+RW++L77r7u/WPm2+1Tffw+KHhlNPOqJ87/sSTu5rRBx/QvG6zTeOx/PrJJ6sVV169qx+U0NBu01tu/Vb1+M9+Vq//M//7TDX7HLPX8/PPN3+1xuqr1vNbbvHp+t+55pyzr+szzzxTnXzKafVzN9/6rer3v/9DPf/GN76h/neF5Zardtt153p+wQUWGGcZExtHKSpjKeMoUxnLpMZRllPWpUxlfcq6DHcZcdMonOoCQsNUJ5953zD5IGzXXmgYOmAJDYOxp0Fo6B+AZt7flDP2mgkNM/b2m25H/6lPb1mP7Z577+vGePFFF1QLL/ze+uezzm52X59x1jnd8/PNN2917devqn8uf+Vvt23z1+1/LP6Brub0s86u5y+/oqkr039us3W16SZj/7q+c8xfx9ded339fPlLfdU11q7n/98vftG97ryzz6hGrrTiBIaHHHZE/dj5F17UPfeZrbaoDthvnwlqf/DQD6v9Dzy4fvy6a742wfPJAxOzWmbppSZ4+VNPNXtNll1x5e65f/u3N1X33v2d5K2GXZPsaXjwBw/Vy91si63rf2ebbbbqqssurucXWug98XsO6p6GNT+6bm00yyyzVKd96cR6vuwFuPb6G+r5vT6/X/XSSy/V8/PO2xzuuebqK6uy3dvpj3/6Uz37yQ03qX7xi1/W86Vn99h9t3r+0suvqP8tvd3uzbv68kuqt73trd0yJjaOUlDGUsZRpjKWiY2jPF+WU9alTGV92j0ak1pGqe1dn7hpFE51AaFhqpMPxhsO9UHY/hJc66PrVo//7L87lD1237Wev/6GG6sD99+3nu/98Dz8yOYY+znnNYcHyrT3HrtXO2zfHE8vU3uM/PwLvlz/XEJDv9dtuslG1aFfbHb7904jV1uz/vFXv3qie7j8cr3tlm9OUHvcCSd1vyA/t9uoydq4Q1n1LnR6DA3t+P7852fr2VlnnaV6/etfP2yLQQ8N++69Z98Qu/W221W333HnOJ7lUF77/0p5YvQhh9XPX3jRV7u6O759c/eB/Y9//KN+fJEPLFH9/e9/r+dXWXlkdc6ZzaGMMrWhYVLjKHW9Yxl/HO1yyjLKNH4oL+vSbxnlsd71GXbzeMFUExAaphr1YL3RUB+EQsPYfhjKqrdzhIaZ7/+j5MNaaJj5tvuMukZCw4y65abzcacfhJ/dedfqmzfd3K3Nhht8sp4//JDR1ayzzlrPt7s668eDPQ1tIPnnP/9Zv77sLm8Pk7TjKo+XEyXvuqM5Yau8R7vHY9PNm0Mr5S+y9q/n8vM3r/9G/fh7/v3d3Xg/ss561ZGHH1L/vPgH3j9ZWyW1Kgsfbmj4/v0P1GM6/czmsM6DD/6gev6FF+r5ueeeqxq54gr1/KhddqrmefObJxj/UIcnJnWFRVlY71UWZbucOeaw1CWXXl61J6i2np/dfrtql90+142h34mQV33t6/Xzl11+ZVX2TJTp2Wefq2abremVRRdZpNr2M82JuCuPXKlqD52sv9Gn+m6b9kTNcuLmeWP2TB16+JFd7eqrrVLP77zjDtWxx59Uz//w4Yerv/3tb/X86173uvpk3jIts3RzouxeezSHBNLpN795qi6dZ5431706/nTYEUdX555/wTgPr/fxj1XHH3NU/VhxXWKpD9fzf/rTn7u6xx95eILlrbDyatWTT/5PXVP+/7r37jvq+XLIIhlHqe0dS+842jcuyynrUqbx16esS79llMfa9Und1E0bAaFh2rjP9O+afhCuufbHxjk8sefnml+4O+7Q7MYcf0pCQ7/Xtbtnl1xm+ao9/lvqrrm6Oda72GKLdudXtOc9PP/8C9U3rr2uW9zeezYfaDtst233i7d8GH33ztvqx3vDzXA2cGpVljmc0FCOIe/2ub3qobQB6tSTT6zaD8L9Djy4uvKq5jyMEhi+duVl9Xw5t6SdhgoNpW5iNeW53tBw7PEnVqedcVa37A0++Yl6fvnlmg+8s845r/rJIz/tnu8XGrbZ7rP18+WD+oD9Pl/Pzz777NVlV1xZz++7/0Hddrjg3LOqFZZfrn68DRgrrbJGd35ACXntOvdur/YqkHKy7pabN1crrLzamtUzf/xj8x6f36sLJiVYnvilU+vHL7us6aX77727d3FTPL/3PvtXV1497vkyvYfkyiWvK6++Vvc+//Ivr6nnf/xQExh7p7XW+Xj12GOPdw9deF4TJlunSQ22jKNMvWMZ/9DgUCs7sWWU1/UeYhxqOZ6fdgJCw7Szn6nfOf0gFBqqKrUqDSM0CA2lD4SGmfrX53S9ckLDdL15ZtzBTeyD8H0LL1yvVPmrskynnzn2L8/eqyfmmmuuvis/uXsa2oXtvufe1X9dc2237FE771jP7zZq52rDTZq/Krfbtrk/w/MvPF/tuntzQleZRiyxRP3vFZd+pTvh7Kc/fbRq7/UwuVurn1X567k9PNNvue3u8fLc+FdPvDDm8MOyK65Slev2y/SWeeap/233ipT5Hz78o2q99TfqFl92NZepdzfxy7Gn4dlnmxMkl1p2xaod2xve8K/V/fc0f5G3u7Cvu/7GIQ9PtKFprrnmrF796ld3Y2/3pLzv/R/sTvRba801uqsR2sJyv4l2ncpjN1zbHO5470ILdXsgVl6t+av9ogvPrX796+YQSHtlSJk/+MD9qy0336x773ZbHPiF5p4fRx1+6OS2wjive/HFF+ufV1p1je7QQbsdy6GyYlimBx78QbXBxmPvh9GehPrDB5rLenunj623fvXjnzzSPdRu63bbT2zgZSxlHGUqhx/6jWOolZ7UMspr2/UZajmen7YCQsO09Z9p311oyDet0NAcxxcaxu0ZoSH/f0jl1BMQGqae9UC9U78Pwl6A9uZO5RrukSs1J+PtuMP21Zve1NwRcmLTlO5pGP+DaZH3NXs+Lrrg3GqFkavV8/d976763xdf/Hs1YunmmHj5Bd7+5V9OHtttj73rx8tfnKuuMvaeCZOzkftZHXv0EX1PrGzv8Nd7Quf4exru+/799TA23nTzbjjtvS6uvuLS7rHfPf10tcxyK3U/z/nGN9bzD9zX3AWyTC/HnoZ+d9h8/2KLVf919bh3t3z0sceqcmJpO/U7p6E9N+FLp57endz6u9893Z2z0bsHpt97lPM8Ru22R/ceW2/ZGJXLe9uTRo865vj6sbJHqT3+X84F6J3e8Y631z+WOyyu/ZHmEt32ZlyT0wP9XtPe2fHEk0+p2vc796zT69J3vuMd3UseeODBaoNNxu75eCX2NJSxlHGUqYyl3ziGWu+XYxlDvYfnX3kBoeGVNx7IdxjOcfrhAE1paHjuueeqJZZatn7L9i+5Ml/usdCead/+QiyPt7ulv/u9e7phlt3T7cly99x1e/Wa1zQnnk3uNByr5JyGG795Uz2UHXcZexb/Ukt+qH7s0q82964oUzkhdIklm5MQe6dy1n2ZymGDlyM03HBjM56dRo07nt6xlOcndZ+G559/vl7G2us2J0+WGxj9+7ubW3VfeN453cmbiy0+ovq/v/61fvx9C793ghtulRMXl1l+ZP18OXTT3o65HLYZfcjh9eOLLrpI/W+5j0c7HXXMcd0htfbqnPHdyuGQMp168gmTfVJsu+wSik4ac4LlRhus3530Wa7WGH96JU6E7B1Heb8yljKOMpUTUPuNY4KBjbmyo6zLlCyj33I9Nu0EhIZpZz9Tv/NwPgiHAyE0DH1HSKFBaCj/T03J1RNCw3B+Kw1WrdAwWNt7qq3t9BoaCkD75Uu9J8SVvQXtbaJ7/8Lsd+1+2Y0/YkRzUuTZZzSX203JNByrZE/Dvfd9vx7OJptt0Q1rWh6eaPfS9J5M+MH/WLy66vJLxmH775//vFp9reb7JsrUe3ii3yGXcgVBmXov1RtqT0Opb+/D0G7b8lg5HHTk0cfWy7v5huYy2/ZLntrxtPcxKHccve322+uHv3Pn3d2hkbbusosvqpb80Ihht8Qf/vC/1d77Npc1Pvb449URhzYnVi6/XLNnrEw/+tGP638fffzxav1PNIdyygf8B5dcpp7vva9Iv/s0lC8Eaw/xjH+fhvY9xh9HebyMZahx9K5wWUaZyvqUdRlqGeX5dn2GDecFU1VAaJiq3IPzZsP5IByOypTuaSjvdcGXv1K/5RcPbXZHl6ncY+Hu73y7nm/PDC/zv3qiuZX0yFWb49btdPiho+vZTTbacDjD71s7HKskNHRXT6ywcndvgeTqiX7nELwchyfKIaEyLfnhFbqrJ8qNtVrvFuWO79xZbbXN2Ptz9I7ntjua79b4zLbbd4b779ucV7LN1lt1h5rK1RPtPTn6HZ4o9e1NvMrlvu1UAsIySzXf9XH6qWO/rbM7ZHX+BdUpJ50wwfbrd3Or0085qVpzjbHf1jlUg9xya9N3+x5wYLXQe5rv6thn7z2q1772tRO89Kabb6kf+/79D3bnFZSfDx7dXLFx0Veb7/wo05233VrNP/989XxrsujiI7obU5VbPJfvX2mniY2jPD/+WCY2jlJbllPWpUxlfcq6DLWM8nzvYcGhzDw/7QSEhmlnP1O/83A+CIcDITQMfXhCaGi+Z0FoEBqG87tFbSYgNGROqoYpMD2Hhnb3bNlV207ljpDt3SH7rWrvTajKXon2fgf9br08TKpX7OZO5W6Wu+/Z3DWxvY9B+St6tTFXe+x/0Be6bwstV2B87YrmjpALLDB/twovx56GdmHj3xGy3Vuz0grN1TP7HnBQVfY2tNM6a3+knj36yMOq5577Sz2/4irNNisnRrYnd551+qndtziWExbb4/ETCw3t8svdPNs9CeWxsoegTL17Cdqvey/fulrGUab11v1Y51n+wr/ksuYqkPav8dtvvWnIq4B6e2TEmBNz2ztOJv1TbpHd+5d5+9pPrL9xt3es3G+k/RK1K8bc+fPAg0dX7T1QyjeRtldllPd8OcbRLme461JeZ09DsuWnfY3QMO23wUwzgvYX7KabN/f+n9T07ZtvrJ9++9vfNlRp9fTTv6+WXm7Cr7Du98JHHn5wnJv+TGrhvbfULTd3am/01O81Rx93QnXGmO9v+MD7F6u+ftW4lwsOuRLjFSRW7SV85Vs6Dzio+TbOiy+d9PseMvrgarNPjf2a8PY7N84c8xXkDz70ULd7es4556zaD+xRu+xYfxdH7zSx75UoNe2tqD80YkR1xFHNN4/2m0rdmac1l+rV3z0xZhxlPdrvnlhwwQXq57f49GbjHDJql9f74d9eiXHUscd1Nzx61zvfWe02aqe6fI+99umunugdz88f+8kEwytfr77P/s1u9HJ44p67mu9heNWrXtXVtoenjj72+OqRRx6tHy9Xnfx1zBUaJSiU8zPKNGrn5m6V5VLP4Uwv14d1ec9yLkF7qeYt3/pW/XOZ2hsnlfMSSq+X6W1vHfu12OXnl2scZTlCw3A6YMaqFRpmrO01XY82+SBsV0BoaO7WN6mAJTQ03SI0TPi//fh7GtoKoWG6/hU5UwxOaJgpNqOVIEBguALlfg5LL9vswVp3nY9Whx3S7M0xESAwcQGhQXcQIDDTC/zlL805Eb956rfdTaHKz+W7GMpUbtj1oTGX0c70GFaQwBQICA1TgOelBAjMGAJCw4yxnYxy+hcQGqb/bWSEBAhMoUB7lcRen9+vuu6aq+ullZtOHXnMcfX8Dd/4+mTf+nkKh+blBGYoAaFhhtpcBkuAwOQICA2To+Y1BCYUEBp0BQECM71A+YKrMu2w86jqySf/p56fb963VMcfc1Q9X+7TYSJAYGgBoWFoIxUECBAgQIBAueX+SxP7nlc8BAgQIECAAIEeAaFBOxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIC/RyICAAAJNklEQVQAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBAQGvQAAQIECBAgEAkIDRGTIgIECBAgQEBo0AMECBAgQIBAJCA0REyKCBAgQIAAAaFBDxAgQIAAAQKRgNAQMSkiQIAAAQIEhAY9QIAAAQIECEQCQkPEpIgAAQIECBD4/ymAcgUCyX5gAAAAAElFTkSuQmCC',
        talentDocs: [],
        talentAgents: [
          {
            agentId: 6,
            agentName: 'Supplier test',
            agentStatus: 'Active',
            isPrimary: true,
            category: 'Agent',
            country: 'India',
            city: 'Raipur',
            postCode: null,
            contacts: [
              {
                id: 12,
                name: 'contact p',
                email: 'asdbasdb@test.com',
                phone: '1233586546',
                primary: false,
              },
              {
                id: 11,
                name: 'contact o',
                email: 'jhdsfa@test.com',
                phone: '286646631',
                primary: false,
              },
              {
                id: 10,
                name: 'contact u',
                email: 'hasdjahsd@test.com',
                phone: '2565658536',
                primary: false,
              },
              {
                id: 9,
                name: 'contact y',
                email: 'abssdasd@test.com',
                phone: '16131616166',
                primary: false,
              },
            ],
            lastPO: '2022-09-23',
          },
          {
            agentId: 5,
            agentName: 'New',
            agentStatus: 'Active',
            isPrimary: false,
            category: 'Agent',
            country: 'Kosovo',
            city: 'Shtime',
            postCode: null,
            contacts: [
              {
                id: 3,
                name: 'Test',
                email: 'test@gmail.com',
                phone: '+91 91798 6737',
                primary: true,
              },
            ],
            lastPO: '2022-09-23',
          },
          {
            agentId: 9,
            agentName: 'Jobs',
            agentStatus: 'Active',
            isPrimary: false,
            category: 'Agent',
            country: 'Albania',
            city: 'Lushnje',
            postCode: null,
            contacts: [],
            lastPO: '2022-09-26',
          },
        ],
        availability: null,
        longlist: [40, 44, 9, 38],
        shortlist: null,
        voiceclips: [
          {
            id: 22,
            name: 'lkjhGFGHAJZX',
            duration: '0:27',
            gender: 'Male',
            filename: 'file_example_MP3_700KB (1).mp3',
            filepath:
              'talent/docs/58/file_example_mp3_700kb (1)2022-08-26_06-50-09_AM.mp3',
            voice_tags: {
              1: 'Gravelly',
              2: 'Hoarse',
              3: 'Wheezy',
              4: 'Gentle',
              5: 'Animation',
              6: 'Breathy',
              7: 'Croaky',
              8: 'Gruff',
              9: 'Penetrating',
              10: 'Voicenew',
              11: 'Voicenewn',
              12: 'Voicetag',
              13: 'Test',
              14: 'Gsadhsdh',
            },
            accents: {
              1: 'Geordie',
              2: 'Cockney',
              3: 'Scottish',
              4: 'Kenya',
              5: 'Uganda',
              6: 'Indian',
              7: 'Antigua',
              8: 'Welsh English',
              9: 'Midlands English',
              10: 'Ok',
              11: 'New',
              12: 'Newone',
              13: 'Newoneone',
              14: 'Add',
              15: 'O',
              16: 'Oko',
              17: 'Okok',
              18: 'Okokok',
              19: 'Okokokok',
              20: 'Farukh ',
              21: 'Jkkjkjjbk',
              22: 'New Accents',
              23: 'New Languages',
              24: 'Accent Native',
            },
            game_types: {
              1: 'Sports',
              2: 'Military',
              3: 'Racing',
              4: 'Cartoon',
              5: 'Rpg',
              6: 'Scientific',
              7: 'Innovation',
              8: 'New',
              9: 'Newgame',
              10: 'Newone',
            },
          },
        ],
        talentReviews: [
          {
            id: 9,
            sideUserId: 120003243,
            user: 'Farukh Patel',
            projectId: 16,
            project: 'project new',
            characterId: null,
            character: null,
            comment: 'comment',
          },
        ],
        session_notes_talent: [],
        purchaseOrder: [
          {
            id: 23,
            poNumber: 'Ban-24-PH',
            project: 'Stranger Things',
            projectId: 34,
            milestoneId: 17,
            agent: 'test',
            agentId: 2,
          },
          {
            id: 21,
            poNumber: 'Ban-22-NA',
            project: 'Cyclone1',
            projectId: 14,
            milestoneId: 10,
            agent: 'Supplier test',
            agentId: 6,
          },
          {
            id: 17,
            poNumber: 'Ban-18-NA',
            project: 'Cyclone',
            projectId: 1,
            milestoneId: 1,
            agent: 'Supplier test',
            agentId: 6,
          },
        ],
        castingNotes: [
          {
            project: 'Cyclone test',
            sideUser: null,
            character: 'Laxman',
            date: '06 Oct 2022',
            notes: null,
            type: 'Audition',
          },
        ],
        talentProjects: [
          {
            projectId: 1,
            project: 'Cyclone',
          },
          {
            projectId: 34,
            project: 'Stranger Things',
          },
          {
            projectId: 3,
            project: 'Cyclone test',
          },
        ],
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/side/talent/all/',
};
