export default {
  response: {
    count: 27,
    next: 'https://crm-pydev.ptw.com/assumption/?limit=15&offset=15',
    previous: null,
    result: [
      {
        updatedOn: '2022-03-30T08:22:29',
        typeId: 208,
        branchId: 66,
        lobId: 316,
        serviceId: 317,
        isMandatory: true,
        documentTypeId: 210,
        id: 33,
        assumption: 'assumption',
        lobName: 'Resouce Type Test',
        branchName: 'Glasgow',
        serviceName: 'RS Sub Lob',
        type: {
          id: 208,
          name: 'LOB',
        },
        documentType: {
          id: 208,
          name: 'LOB',
        },
      },
      {
        updatedOn: '2022-01-07T08:25:39',
        typeId: 208,
        branchId: 65,
        lobId: 286,
        serviceId: 289,
        isMandatory: true,
        documentTypeId: 210,
        id: 32,
        assumption: 'check assumption',
        lobName: 'dept123a',
        branchName: 'test',
        serviceName: 'dept_34',
        type: {
          id: 208,
          name: 'LOB',
        },
        documentType: {
          id: 208,
          name: 'LOB',
        },
      },
      {
        updatedOn: '2022-01-07T08:25:00',
        typeId: 209,
        branchId: null,
        lobId: null,
        serviceId: null,
        isMandatory: null,
        documentTypeId: 210,
        id: 31,
        assumption: 'check if mandatory is passing',
        lobName: null,
        branchName: null,
        serviceName: null,
        type: {
          id: 209,
          name: 'General',
        },
        documentType: {
          id: 209,
          name: 'General',
        },
      },
      {
        updatedOn: '2022-01-07T08:21:19',
        typeId: 208,
        branchId: 62,
        lobId: 290,
        serviceId: 299,
        isMandatory: true,
        documentTypeId: 210,
        id: 30,
        assumption: 'submit assumption updated',
        lobName: 'Player Support',
        branchName: 'Taipei1',
        serviceName: 'Support',
        type: {
          id: 208,
          name: 'LOB',
        },
        documentType: {
          id: 208,
          name: 'LOB',
        },
      },
      {
        updatedOn: '2022-01-07T08:19:56',
        typeId: 209,
        branchId: null,
        lobId: null,
        serviceId: null,
        isMandatory: null,
        documentTypeId: 210,
        id: 29,
        assumption: 'asumption updated',
        lobName: null,
        branchName: null,
        serviceName: null,
        type: {
          id: 209,
          name: 'General',
        },
        documentType: {
          id: 209,
          name: 'General',
        },
      },
      {
        updatedOn: '2022-01-07T08:16:31',
        typeId: 209,
        branchId: null,
        lobId: null,
        serviceId: null,
        isMandatory: null,
        documentTypeId: 210,
        id: 28,
        assumption: 'add assumption',
        lobName: null,
        branchName: null,
        serviceName: null,
        type: {
          id: 209,
          name: 'General',
        },
        documentType: {
          id: 209,
          name: 'General',
        },
      },
      {
        updatedOn: '2022-01-07T07:40:41',
        typeId: 209,
        branchId: null,
        lobId: null,
        serviceId: null,
        isMandatory: null,
        documentTypeId: 210,
        id: 27,
        assumption: 'assumption',
        lobName: null,
        branchName: null,
        serviceName: null,
        type: {
          id: 209,
          name: 'General',
        },
        documentType: {
          id: 209,
          name: 'General',
        },
      },
      {
        updatedOn: '2022-01-07T05:45:53',
        typeId: 209,
        branchId: null,
        lobId: null,
        serviceId: null,
        isMandatory: null,
        documentTypeId: 210,
        id: 26,
        assumption: 'check',
        lobName: null,
        branchName: null,
        serviceName: null,
        type: {
          id: 209,
          name: 'General',
        },
        documentType: {
          id: 209,
          name: 'General',
        },
      },
      {
        updatedOn: '2022-01-07T05:34:56',
        typeId: 208,
        branchId: 61,
        lobId: 290,
        serviceId: null,
        isMandatory: false,
        documentTypeId: 210,
        id: 25,
        assumption: 'assumption',
        lobName: 'Player Support',
        branchName: 'Ptwhyd',
        serviceName: null,
        type: {
          id: 208,
          name: 'LOB',
        },
        documentType: {
          id: 208,
          name: 'LOB',
        },
      },
      {
        updatedOn: '2022-01-07T05:34:28',
        typeId: 208,
        branchId: 64,
        lobId: 290,
        serviceId: null,
        isMandatory: true,
        documentTypeId: 210,
        id: 24,
        assumption: 'check',
        lobName: 'Player Support',
        branchName: 'Cap',
        serviceName: null,
        type: {
          id: 208,
          name: 'LOB',
        },
        documentType: {
          id: 208,
          name: 'LOB',
        },
      },
      {
        updatedOn: '2022-01-07T05:33:09',
        typeId: 209,
        branchId: null,
        lobId: null,
        serviceId: null,
        isMandatory: null,
        documentTypeId: 210,
        id: 23,
        assumption: 'add',
        lobName: null,
        branchName: null,
        serviceName: null,
        type: {
          id: 209,
          name: 'General',
        },
        documentType: {
          id: 209,
          name: 'General',
        },
      },
      {
        updatedOn: '2022-01-07T05:32:58',
        typeId: 208,
        branchId: 64,
        lobId: 286,
        serviceId: null,
        isMandatory: false,
        documentTypeId: 210,
        id: 22,
        assumption: 'assumptions',
        lobName: 'dept123a',
        branchName: 'Cap',
        serviceName: null,
        type: {
          id: 208,
          name: 'LOB',
        },
        documentType: {
          id: 208,
          name: 'LOB',
        },
      },
      {
        updatedOn: '2022-01-07T04:53:27',
        typeId: 209,
        branchId: null,
        lobId: null,
        serviceId: null,
        isMandatory: null,
        documentTypeId: 210,
        id: 21,
        assumption: 'add assumption',
        lobName: null,
        branchName: null,
        serviceName: null,
        type: {
          id: 209,
          name: 'General',
        },
        documentType: {
          id: 209,
          name: 'General',
        },
      },
      {
        updatedOn: '2022-01-06T08:04:55',
        typeId: 208,
        branchId: 61,
        lobId: 290,
        serviceId: null,
        isMandatory: true,
        documentTypeId: 210,
        id: 20,
        assumption: 'check mandatory',
        lobName: 'Player Support',
        branchName: 'Ptwhyd',
        serviceName: null,
        type: {
          id: 208,
          name: 'LOB',
        },
        documentType: {
          id: 208,
          name: 'LOB',
        },
      },
      {
        updatedOn: '2022-01-06T08:04:16',
        typeId: 209,
        branchId: null,
        lobId: null,
        serviceId: null,
        isMandatory: null,
        documentTypeId: 210,
        id: 19,
        assumption: 'check add',
        lobName: null,
        branchName: null,
        serviceName: null,
        type: {
          id: 209,
          name: 'General',
        },
        documentType: {
          id: 209,
          name: 'General',
        },
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/crm/assumption/',
};
