export default {
  response: {
    count: 63,
    next: null,
    previous: null,
    result: [
      {
        regionId: 7,
        countryId: 23,
        cityId: 39,
        branchCode: null,
        legalEntity: null,
        legalCode: null,
        addressLine1: null,
        addressLine2: null,
        addressLine3: null,
        registrationNumber: null,
        phoneNumber: null,
        emailId: null,
        blockNumber: null,
        buildingName: null,
        streetName: null,
        branchSpace: null,
        branchSpaceUnit: null,
        id: 68,
        town: null,
        pincode: '560004',
        name: 'Test 1',
        region: 'Asia',
        country: 'India',
        city: 'Bangalore',
        departments: null,
      },
      {
        regionId: 7,
        countryId: 23,
        cityId: 40,
        branchCode: null,
        legalEntity: null,
        legalCode: null,
        addressLine1:
          'PTWI Pvt Ltd, 6th Floor, B Wing Smartworks - Purva Summit, White Fields Hi-Tech City Madhapur, Hyderabad, Telangana',
        addressLine2: null,
        addressLine3: null,
        registrationNumber: null,
        phoneNumber: null,
        emailId: null,
        blockNumber: null,
        buildingName: null,
        streetName: null,
        branchSpace: null,
        branchSpaceUnit: null,
        id: 67,
        town: null,
        pincode: '500081',
        name: 'Portal',
        region: 'Asia',
        country: 'India',
        city: 'Hyderabad',
        departments: [
          {
            departmentId: 295,
            name: 'Localization',
            capacity: 10000,
          },
        ],
      },
      {
        regionId: 5,
        countryId: 14,
        cityId: 27,
        branchCode: null,
        legalEntity: null,
        legalCode: null,
        addressLine1:
          '9th floor, 1, Skypark, 8 Elliot Square, Glasgow G3 8EP, United Kingdom',
        addressLine2: null,
        addressLine3: null,
        registrationNumber: null,
        phoneNumber: null,
        emailId: null,
        blockNumber: null,
        buildingName: null,
        streetName: null,
        branchSpace: null,
        branchSpaceUnit: null,
        id: 66,
        town: null,
        pincode: '123456',
        name: 'Glasgow',
        region: 'Europe',
        country: 'United Kingdom',
        city: 'London',
        departments: [
          {
            departmentId: 295,
            name: 'Localization',
            capacity: 2000,
          },
          {
            departmentId: 270,
            name: 'Quality Assurance',
            capacity: 10000,
          },
        ],
      },
      {
        regionId: 7,
        countryId: 23,
        cityId: 40,
        branchCode: null,
        legalEntity: null,
        legalCode: null,
        addressLine1: null,
        addressLine2: null,
        addressLine3: null,
        registrationNumber: null,
        phoneNumber: null,
        emailId: null,
        blockNumber: null,
        buildingName: null,
        streetName: null,
        branchSpace: null,
        branchSpaceUnit: null,
        id: 65,
        town: null,
        pincode: null,
        name: 'test',
        region: 'Asia',
        country: 'India',
        city: 'Hyderabad',
        departments: null,
      },
      {
        regionId: 6,
        countryId: 16,
        cityId: 31,
        branchCode: null,
        legalEntity: null,
        legalCode: null,
        addressLine1: 'deede',
        addressLine2: null,
        addressLine3: null,
        registrationNumber: null,
        phoneNumber: null,
        emailId: null,
        blockNumber: null,
        buildingName: null,
        streetName: null,
        branchSpace: null,
        branchSpaceUnit: null,
        id: 64,
        town: null,
        pincode: '254354',
        name: 'Cap',
        region: 'Africa',
        country: 'South Africa',
        city: 'Cape Town',
        departments: null,
      },
      {
        regionId: 7,
        countryId: 34,
        cityId: 51,
        branchCode: null,
        legalEntity: null,
        legalCode: null,
        addressLine1: 'fre',
        addressLine2: null,
        addressLine3: null,
        registrationNumber: null,
        phoneNumber: null,
        emailId: null,
        blockNumber: null,
        buildingName: null,
        streetName: null,
        branchSpace: null,
        branchSpaceUnit: null,
        id: 62,
        town: null,
        pincode: '543664',
        name: 'Taipei1',
        region: 'Asia',
        country: 'Taiwan',
        city: 'Taipei',
        departments: [
          {
            departmentId: 38,
            name: 'Finance',
            capacity: 23,
          },
          {
            departmentId: 37,
            name: 'Security',
            capacity: 34,
          },
          {
            departmentId: 41,
            name: 'Fin',
            capacity: 35,
          },
          {
            departmentId: 36,
            name: 'ImportDep',
            capacity: 45,
          },
        ],
      },
      {
        regionId: 7,
        countryId: 23,
        cityId: 40,
        branchCode: null,
        legalEntity: null,
        legalCode: null,
        addressLine1: '1-2-413-28615',
        addressLine2: null,
        addressLine3: null,
        registrationNumber: null,
        phoneNumber: null,
        emailId: null,
        blockNumber: null,
        buildingName: null,
        streetName: null,
        branchSpace: null,
        branchSpaceUnit: null,
        id: 61,
        town: null,
        pincode: '500012',
        name: 'Ptwhyd',
        region: 'Asia',
        country: 'India',
        city: 'Hyderabad',
        departments: null,
      },
      {
        regionId: 7,
        countryId: 21,
        cityId: 37,
        branchCode: null,
        legalEntity: null,
        legalCode: null,
        addressLine1: 'abc12',
        addressLine2: 'dsa21',
        addressLine3: null,
        registrationNumber: null,
        phoneNumber: null,
        emailId: null,
        blockNumber: null,
        buildingName: null,
        streetName: null,
        branchSpace: '56',
        branchSpaceUnit: '2654',
        id: 59,
        town: null,
        pincode: '322432',
        name: 'Kabul1',
        region: 'Asia',
        country: 'Afghanistan',
        city: 'Kabul',
        departments: [
          {
            departmentId: 38,
            name: 'Finance',
            capacity: 23,
          },
          {
            departmentId: 37,
            name: 'Security',
            capacity: 21,
          },
        ],
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/wfm/branches/get/',
};
