export default {
  response: {
    count: 52,
    next: 'https://crm-pydev.ptw.com/campaign/?limit=15&offset=15',
    previous: null,
    result: [
      {
        createdOn: '2022-02-10T10:03:55',
        updatedOn: '2022-02-10T10:03:55',
        createdBy: 21,
        ownerId: 120003196,
        startDate: null,
        endDate: null,
        statusId: 31,
        typeId: 30,
        budgetCost: null,
        budgetCurrencyId: null,
        actualCost: null,
        actualCurrencyId: null,
        expectedRevenue: 10,
        expectedCurrencyId: 139,
        expectedPeriod: 10,
        expectedPeriodType: 'days',
        id: 68,
        name: 'jksdghq34',
        description: null,
        ownerName: 'Shivangi Nauni',
        createdByName: 'Jaya Surya',
        status: {
          id: 31,
          name: 'Planning',
        },
        type: {
          id: 30,
          name: 'Conference',
        },
        budgetCurrency: null,
        actualCurrency: null,
        expectedCurrency: {
          id: 139,
          name: 'Vietnamese Dong',
        },
      },
      {
        createdOn: '2022-02-10T10:01:50',
        updatedOn: '2022-02-10T10:01:50',
        createdBy: 21,
        ownerId: 120003196,
        startDate: null,
        endDate: null,
        statusId: 31,
        typeId: 30,
        budgetCost: null,
        budgetCurrencyId: null,
        actualCost: null,
        actualCurrencyId: null,
        expectedRevenue: null,
        expectedCurrencyId: null,
        expectedPeriod: null,
        expectedPeriodType: null,
        id: 67,
        name: 'jjjjjjj8797',
        description: null,
        ownerName: 'Shivangi Nauni',
        createdByName: 'Jaya Surya',
        status: {
          id: 31,
          name: 'Planning',
        },
        type: {
          id: 30,
          name: 'Conference',
        },
        budgetCurrency: null,
        actualCurrency: null,
        expectedCurrency: null,
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/crm/campaign/',
};
