export default {
  response: {
    count: 2,
    next: null,
    previous: null,
    result: [
      {
        voiceTypes: {
          1: 'Gravelly',
          2: 'Hoarse',
          3: 'Wheezy',
          4: 'Gentle',
          5: 'Animation',
          6: 'Breathy',
          7: 'Croaky',
          8: 'Gruff',
          9: 'Penetrating',
        },
        aboutCharacter: null,
        uniqueId: 'CHR0000000004',
        id: 4,
        name: 'Character',
        age: '30s',
        gender: 'Male',
        accents: {
          1: 'Geordie',
          2: 'Cockney',
          3: 'Scottish',
          4: 'Kenya',
          5: 'Uganda',
          6: 'Indian',
          7: 'Antigua',
          8: 'Welsh English',
          9: 'Midlands English',
        },
        profiles: 4,
        tier: 'Tier1',
        projectId: 1,
        project: 'Cyclone',
        clientId: 1,
        client: 'HMT',
        milestones: [
          {
            id: 1,
            name: 'Milestone 1',
          },
        ],
        characterDocs: [],
        shortlisted: 15,
      },
      {
        voiceTypes: {
          1: 'Gravelly',
          2: 'Hoarse',
          3: 'Wheezy',
          4: 'Gentle',
          5: 'Animation',
          6: 'Breathy',
          7: 'Croaky',
          8: 'Gruff',
          9: 'Penetrating',
        },
        aboutCharacter: null,
        uniqueId: 'CHR0000000001',
        id: 1,
        name: 'David ghahahhahgah',
        age: 'Teen',
        gender: 'Female',
        accents: {
          1: 'Geordie',
          2: 'Cockney',
          3: 'Scottish',
          4: 'Kenya',
          5: 'Uganda',
          6: 'Indian',
          7: 'Antigua',
          8: 'Welsh English',
          9: 'Midlands English',
        },
        profiles: 4,
        tier: 'Tier1',
        projectId: 1,
        project: 'Cyclone',
        clientId: 1,
        client: 'HMT',
        milestones: [
          {
            id: 1,
            name: 'Milestone 1',
          },
        ],
        characterDocs: [],
        shortlisted: 15,
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/side/character/',
};
