export default {
  response: {
    count: 5,
    next: null,
    previous: null,
    result: [
      {
        clientCrmId: 469,
        clientName: 'Former Animation',
        productionContact: null,
        productionEmail: null,
        invoicingEmail: null,
        ccContact: null,
        ccEmail: null,
        Notes: null,
        creditControlContact: null,
        creditControlEmail: null,
        creditControlPhone: null,
        currencyId: null,
        accountCode: null,
        vatNumber: null,
        vatRate: null,
        id: 5,
        currency: null,
        clientDocs: [],
        projects: null,
      },
      {
        clientCrmId: 471,
        clientName: 'HMT',
        productionContact: null,
        productionEmail: null,
        invoicingEmail: null,
        ccContact: null,
        ccEmail: null,
        Notes: null,
        creditControlContact: null,
        creditControlEmail: null,
        creditControlPhone: null,
        currencyId: null,
        accountCode: null,
        vatNumber: null,
        vatRate: null,
        id: 4,
        currency: null,
        clientDocs: [],
        projects: [
          {
            id: 2,
            name: 'Stranger thingsS1',
          },
        ],
      },
      {
        clientCrmId: 492,
        clientName: 'Solo alexa',
        productionContact: null,
        productionEmail: null,
        invoicingEmail: null,
        ccContact: null,
        ccEmail: null,
        Notes: null,
        creditControlContact: null,
        creditControlEmail: null,
        creditControlPhone: null,
        currencyId: null,
        accountCode: null,
        vatNumber: null,
        vatRate: null,
        id: 3,
        currency: null,
        clientDocs: [],
        projects: null,
      },
      {
        clientCrmId: 467,
        clientName: 'Paramount',
        productionContact: null,
        productionEmail: null,
        invoicingEmail: null,
        ccContact: null,
        ccEmail: null,
        Notes: null,
        creditControlContact: null,
        creditControlEmail: null,
        creditControlPhone: null,
        currencyId: null,
        accountCode: null,
        vatNumber: null,
        vatRate: null,
        id: 2,
        currency: null,
        clientDocs: [],
        projects: null,
      },
      {
        clientCrmId: 445,
        clientName: 'Tata Power',
        productionContact: null,
        productionEmail: null,
        invoicingEmail: null,
        ccContact: null,
        ccEmail: null,
        Notes: null,
        creditControlContact: null,
        creditControlEmail: null,
        creditControlPhone: null,
        currencyId: null,
        accountCode: null,
        vatNumber: null,
        vatRate: null,
        id: 1,
        currency: null,
        clientDocs: [],
        projects: [
          {
            id: 1,
            name: 'The Blood Dragon - Rox and Slayter casting and record(The blood dragon)',
          },
        ],
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/side/client/',
};
