export default {
  response: {
    count: 41,
    next: null,
    previous: null,
    result: [
      {
        createdOn: '2022-09-29T06:05:04',
        updatedOn: '2022-09-29T06:05:04',
        isActive: true,
        createdBy: 6,
        employeeCount: null,
        cityId: null,
        countryId: 185,
        stateId: null,
        isApproved: true,
        parentCompanyId: null,
        phoneNumber: null,
        isStrategic: false,
        id: 492,
        name: 'Solo alexa',
        website: null,
        pincode: null,
        address1: null,
        address2: null,
        address3: null,
        finance: null,
        parentComapnyName: null,
        createdByName: 'Vamshi Aditya',
        leadSourceGroup: null,
        conversionNote: null,
        currency: {id: 3, name: 'United States Dollar', code: 'USD'},
        annualRevenue: null,
        marketType: {id: 241, name: 'Non-Games'},
        city: null,
        state: null,
        country: {id: 185, name: 'Bermuda'},
        industry: {id: 10, name: 'Education'},
        clientType: {id: 291, name: 'Affiliated Developer'},
        owners: [
          {
            userId: 6,
            name: 'Vamshi Aditya',
            regions: [
              {id: 9, name: 'APAC'},
              {id: 7, name: 'LATAM'},
              {id: 5, name: 'North America'},
              {id: 4, name: 'EMEA'},
            ],
            departments: null,
          },
        ],
        billingEntities: null,
        services: null,
      },
      {
        createdOn: '2022-03-21T09:32:44',
        updatedOn: '2022-03-21T09:32:44',
        isActive: true,
        createdBy: 120003107,
        employeeCount: null,
        cityId: 50,
        countryId: 33,
        stateId: 49,
        isApproved: true,
        parentCompanyId: null,
        phoneNumber: '+123 (455) 555',
        isStrategic: false,
        id: 471,
        name: 'HMT',
        website: null,
        pincode: null,
        address1: null,
        address2: null,
        address3: null,
        finance: null,
        parentComapnyName: null,
        createdByName: 'Pavitra Hegde',
        leadSourceGroup: null,
        conversionNote: null,
        currency: {id: 142, name: 'Zambia Kwacha', code: 'ZMW'},
        annualRevenue: null,
        marketType: {id: 11, name: 'Games'},
        city: {id: 50, name: 'Magadan'},
        state: {id: 49, name: 'Maga Buryatdan'},
        country: {id: 33, name: 'Russia'},
        industry: {id: 10, name: 'Education'},
        clientType: {id: 289, name: 'Self-Publishing Developer'},
        owners: [
          {
            userId: 120003107,
            name: 'Pavitra Hegde',
            regions: [
              {id: 9, name: 'APAC'},
              {id: 7, name: 'LATAM'},
              {id: 5, name: 'North America'},
              {id: 4, name: 'EMEA'},
            ],
            departments: null,
          },
        ],
        billingEntities: null,
        services: null,
      },
      {
        createdOn: '2022-03-03T07:45:20',
        updatedOn: '2022-03-03T07:45:20',
        isActive: true,
        createdBy: 120003107,
        employeeCount: null,
        cityId: 49,
        countryId: 32,
        stateId: 48,
        isApproved: true,
        parentCompanyId: null,
        phoneNumber: null,
        isStrategic: false,
        id: 469,
        name: 'Former Animation',
        website: null,
        pincode: '0',
        address1: null,
        address2: null,
        address3: null,
        finance: null,
        parentComapnyName: null,
        createdByName: 'Pavitra Hegde',
        leadSourceGroup: null,
        conversionNote: null,
        currency: {id: 130, name: 'Turkish Lira', code: 'TRY'},
        annualRevenue: null,
        marketType: {id: 241, name: 'Non-Games'},
        city: {id: 49, name: 'Naju-Si'},
        state: {id: 48, name: 'Naju-Si'},
        country: {id: 32, name: 'Korea'},
        industry: {id: 9, name: 'Entertainment'},
        clientType: {id: 290, name: 'Third Party'},
        owners: [
          {
            userId: 120003112,
            name: 'Sushma Savanth',
            regions: [
              {id: 9, name: 'APAC'},
              {id: 7, name: 'LATAM'},
              {id: 5, name: 'North America'},
              {id: 4, name: 'EMEA'},
            ],
            departments: null,
          },
        ],
        billingEntities: null,
        services: null,
      },
      {
        createdOn: '2022-03-03T07:44:15',
        updatedOn: '2022-03-03T07:44:15',
        isActive: true,
        createdBy: 120003107,
        employeeCount: null,
        cityId: null,
        countryId: 27,
        stateId: null,
        isApproved: true,
        parentCompanyId: null,
        phoneNumber: null,
        isStrategic: false,
        id: 468,
        name: 'Focus media',
        website: null,
        pincode: null,
        address1: null,
        address2: null,
        address3: null,
        finance: null,
        parentComapnyName: null,
        createdByName: 'Pavitra Hegde',
        leadSourceGroup: null,
        conversionNote: null,
        currency: {id: 128, name: 'Trinidad and Tobago Dollar', code: 'TTD'},
        annualRevenue: null,
        marketType: {id: 241, name: 'Non-Games'},
        city: null,
        state: null,
        country: {id: 27, name: 'Thailand'},
        industry: {id: 9, name: 'Entertainment'},
        clientType: {id: 291, name: 'Affiliated Developer'},
        owners: [
          {
            userId: 120003112,
            name: 'Sushma Savanth',
            regions: [
              {id: 9, name: 'APAC'},
              {id: 7, name: 'LATAM'},
              {id: 5, name: 'North America'},
              {id: 4, name: 'EMEA'},
            ],
            departments: null,
          },
        ],
        billingEntities: null,
        services: null,
      },
      {
        createdOn: '2022-03-03T07:42:57',
        updatedOn: '2022-03-03T07:42:57',
        isActive: true,
        createdBy: 120003107,
        employeeCount: null,
        cityId: 50,
        countryId: 33,
        stateId: 49,
        isApproved: true,
        parentCompanyId: null,
        phoneNumber: null,
        isStrategic: false,
        id: 467,
        name: 'Paramount',
        website: null,
        pincode: '0',
        address1: null,
        address2: null,
        address3: null,
        finance: null,
        parentComapnyName: null,
        createdByName: 'Pavitra Hegde',
        leadSourceGroup: null,
        conversionNote: null,
        currency: {id: 129, name: 'Tunisian Dinar', code: 'TND'},
        annualRevenue: null,
        marketType: {id: 241, name: 'Non-Games'},
        city: {id: 50, name: 'Magadan'},
        state: {id: 49, name: 'Maga Buryatdan'},
        country: {id: 33, name: 'Russia'},
        industry: {id: 4, name: 'Games'},
        clientType: {id: 288, name: 'Publishers'},
        owners: [
          {
            userId: 120003107,
            name: 'Pavitra Hegde',
            regions: [
              {id: 9, name: 'APAC'},
              {id: 7, name: 'LATAM'},
              {id: 5, name: 'North America'},
              {id: 4, name: 'EMEA'},
            ],
            departments: null,
          },
        ],
        billingEntities: null,
        services: null,
      },
      {
        createdOn: '2022-03-03T07:38:29',
        updatedOn: '2022-03-03T07:38:29',
        isActive: true,
        createdBy: 120003107,
        employeeCount: null,
        cityId: 31,
        countryId: 16,
        stateId: 31,
        isApproved: true,
        parentCompanyId: null,
        phoneNumber: null,
        isStrategic: false,
        id: 466,
        name: 'Universal',
        website: null,
        pincode: '0',
        address1: null,
        address2: null,
        address3: null,
        finance: null,
        parentComapnyName: null,
        createdByName: 'Pavitra Hegde',
        leadSourceGroup: null,
        conversionNote: null,
        currency: {id: 128, name: 'Trinidad and Tobago Dollar', code: 'TTD'},
        annualRevenue: null,
        marketType: {id: 241, name: 'Non-Games'},
        city: {id: 31, name: 'Cape Town'},
        state: {id: 31, name: 'Western Cape'},
        country: {id: 16, name: 'South Africa'},
        industry: {id: 9, name: 'Entertainment'},
        clientType: {id: 287, name: 'Developers'},
        owners: [
          {
            userId: 120003204,
            name: 'Naresh Singh',
            regions: [
              {id: 9, name: 'APAC'},
              {id: 7, name: 'LATAM'},
              {id: 5, name: 'North America'},
              {id: 4, name: 'EMEA'},
            ],
            departments: null,
          },
        ],
        billingEntities: null,
        services: null,
      },
      {
        createdOn: '2022-02-24T13:34:16',
        updatedOn: '2022-02-24T13:34:16',
        isActive: true,
        createdBy: 21,
        employeeCount: null,
        cityId: 53,
        countryId: 35,
        stateId: 51,
        isApproved: true,
        parentCompanyId: null,
        phoneNumber: null,
        isStrategic: false,
        id: 458,
        name: '    yguig',
        website: null,
        pincode: null,
        address1: null,
        address2: null,
        address3: null,
        finance: null,
        parentComapnyName: null,
        createdByName: 'Jaya surya',
        leadSourceGroup: null,
        conversionNote: null,
        currency: {id: 141, name: 'Yemeni Rial', code: 'YER'},
        annualRevenue: null,
        marketType: {id: 241, name: 'Non-Games'},
        city: {id: 53, name: 'Entalize'},
        state: {id: 51, name: 'Tokyo'},
        country: {id: 35, name: 'Japan'},
        industry: {id: 9, name: 'Entertainment'},
        clientType: {id: 290, name: 'Third Party'},
        owners: [
          {
            userId: 120003208,
            name: 'venkat T',
            regions: [{id: 7, name: 'LATAM'}],
            departments: null,
          },
        ],
        billingEntities: null,
        services: null,
      },
      {
        createdOn: '2022-02-21T06:46:13',
        updatedOn: '2022-02-21T06:46:13',
        isActive: true,
        createdBy: 21,
        employeeCount: 10,
        cityId: null,
        countryId: 23,
        stateId: null,
        isApproved: true,
        parentCompanyId: 439,
        phoneNumber: null,
        isStrategic: false,
        id: 453,
        name: 'bajaj Finance',
        website: null,
        pincode: null,
        address1: null,
        address2: null,
        address3: null,
        finance: null,
        parentComapnyName: 'fish world',
        OpportunityCount: 1,
        createdByName: 'Jaya surya',
        leadSourceGroup: null,
        conversionNote: null,
        currency: {id: 141, name: 'Yemeni Rial', code: 'YER'},
        annualRevenue: {id: 51, name: '50 to 200 mn'},
        marketType: {id: 11, name: 'Games'},
        city: null,
        state: null,
        country: {id: 23, name: 'India'},
        industry: {id: 9, name: 'Entertainment'},
        clientType: {id: 290, name: 'Third Party'},
        owners: [
          {
            userId: 6,
            name: 'Vamshi Aditya',
            regions: [{id: 7, name: 'LATAM'}],
            departments: null,
          },
        ],
        billingEntities: null,
        services: null,
      },
      {
        createdOn: '2022-02-21T06:37:50',
        updatedOn: '2022-02-21T06:37:50',
        isActive: true,
        createdBy: 21,
        employeeCount: null,
        cityId: 52,
        countryId: 35,
        stateId: 51,
        isApproved: true,
        parentCompanyId: null,
        phoneNumber: null,
        isStrategic: false,
        id: 450,
        name: 'newAccountShivangi',
        website: null,
        pincode: null,
        address1: null,
        address2: null,
        address3: null,
        finance: null,
        parentComapnyName: null,
        createdByName: 'Jaya surya',
        leadSourceGroup: null,
        conversionNote: null,
        currency: {id: 142, name: 'Zambia Kwacha', code: 'ZMW'},
        annualRevenue: null,
        marketType: {id: 241, name: 'Non-Games'},
        city: {id: 52, name: 'PTW Japan'},
        state: {id: 51, name: 'Tokyo'},
        country: {id: 35, name: 'Japan'},
        industry: {id: 10, name: 'Education'},
        clientType: {id: 289, name: 'Self-Publishing Developer'},
        owners: [
          {
            userId: 120003196,
            name: 'Shivangi Nauni',
            regions: [{id: 9, name: 'APAC'}],
            departments: null,
          },
        ],
        billingEntities: [
          {
            id: 64,
            name: 'jasnhdcs',
            contactPerson: '1`72`83913203',
            contactNumber: '2516273803982',
            emailId: 'hgdhd@gmail.com',
            address1: 'jhsagfdghj',
            address2: 'jhgdsfaghj',
          },
        ],
        services: null,
      },
      {
        createdOn: '2022-02-16T09:31:52',
        updatedOn: '2022-02-16T09:31:52',
        isActive: true,
        createdBy: 21,
        employeeCount: null,
        cityId: 52,
        countryId: 35,
        stateId: 51,
        isApproved: true,
        parentCompanyId: null,
        phoneNumber: '9483483923',
        isStrategic: false,
        id: 445,
        name: 'Tata Power',
        website: null,
        pincode: null,
        address1: null,
        address2: null,
        address3: null,
        finance: null,
        parentComapnyName: null,
        createdByName: 'Jaya surya',
        leadSourceGroup: null,
        conversionNote: null,
        currency: {id: 3, name: 'United States Dollar', code: 'USD'},
        annualRevenue: null,
        marketType: {id: 11, name: 'Games'},
        city: {id: 52, name: 'PTW Japan'},
        state: {id: 51, name: 'Tokyo'},
        country: {id: 35, name: 'Japan'},
        industry: {id: 9, name: 'Entertainment'},
        clientType: {id: 289, name: 'Self-Publishing Developer'},
        owners: [
          {
            userId: 120003122,
            name: 'mithun mi',
            regions: [{id: 7, name: 'LATAM'}],
            departments: [{id: 290, name: 'Player Support', code: 'PLRS'}],
          },
          {
            userId: 6,
            name: 'Vamshi Aditya',
            regions: [{id: 9, name: 'APAC'}],
            departments: [{id: 295, name: 'Localization', code: 'LOC'}],
          },
        ],
        billingEntities: null,
        services: null,
      },
      {
        createdOn: '2022-02-09T05:48:21',
        updatedOn: '2022-02-09T05:48:21',
        isActive: true,
        createdBy: 6,
        employeeCount: null,
        cityId: 51,
        countryId: 34,
        stateId: 50,
        isApproved: true,
        parentCompanyId: null,
        phoneNumber: null,
        isStrategic: true,
        id: 439,
        name: 'fish world',
        website: null,
        pincode: null,
        address1: null,
        address2: null,
        address3: null,
        finance: null,
        parentComapnyName: null,
        createdByName: 'Vamshi Aditya',
        leadSourceGroup: 'Inbound',
        conversionNote: null,
        currency: {id: 3, name: 'United States Dollar', code: 'USD'},
        annualRevenue: {id: 48, name: 'Under 1mn'},
        marketType: {id: 11, name: 'Games'},
        city: {id: 51, name: 'Taipei'},
        state: {id: 50, name: 'Taiwan'},
        country: {id: 34, name: 'Taiwan'},
        industry: {id: 7, name: 'Technology'},
        clientType: {id: 290, name: 'Third Party'},
        owners: [
          {
            userId: 6,
            name: 'Vamshi Aditya',
            regions: [
              {id: 7, name: 'LATAM'},
              {id: 9, name: 'APAC'},
            ],
            departments: [{id: 314, name: 'test11', code: 'test2'}],
          },
          {
            userId: 120003204,
            name: 'Naresh Singh',
            regions: [{id: 9, name: 'APAC'}],
            departments: null,
          },
          {
            userId: 120003203,
            name: 'thota venkat test',
            regions: [{id: 7, name: 'LATAM'}],
            departments: null,
          },
        ],
        billingEntities: [
          {
            id: 63,
            name: 'Billing Info',
            contactPerson: 'vamshi',
            contactNumber: '86835627',
            emailId: 'vamshi@oa.co',
            address1: 'address 1',
            address2: 'address 2',
          },
        ],
        services: null,
      },
      {
        createdOn: '2022-02-08T09:24:45',
        updatedOn: '2022-02-08T09:24:45',
        isActive: true,
        createdBy: 25,
        employeeCount: 12,
        cityId: 54,
        countryId: 35,
        stateId: 52,
        isApproved: true,
        parentCompanyId: 445,
        phoneNumber: null,
        isStrategic: false,
        id: 438,
        name: 'uhkasdf',
        website: null,
        pincode: null,
        address1: null,
        address2: null,
        address3: null,
        finance: null,
        parentComapnyName: 'Tata Power',
        OpportunityCount: 12,
        createdByName: 'praveen kumar',
        leadSourceGroup: null,
        conversionNote: null,
        currency: {id: 142, name: 'Zambia Kwacha', code: 'ZMW'},
        annualRevenue: {id: 52, name: 'above 200 mn'},
        marketType: {id: 241, name: 'Non-Games'},
        city: {id: 54, name: 'Japan'},
        state: {id: 52, name: 'Japan'},
        country: {id: 35, name: 'Japan'},
        industry: {id: 10, name: 'Education'},
        clientType: {id: 290, name: 'Third Party'},
        owners: [
          {
            userId: 120003205,
            name: 'Navin Singh',
            regions: [{id: 7, name: 'LATAM'}],
            departments: null,
          },
        ],
        billingEntities: [
          {
            id: 62,
            name: 'Billing name',
            contactPerson: 'Surya',
            contactNumber: '093458023',
            emailId: 'alskdf@ptw.com',
            address1: 'sd flkasld asdf, asdlkfj sldf',
            address2: 'sdlfkasldfkl',
          },
        ],
        services: null,
      },
      {
        createdOn: '2022-02-04T15:18:38',
        updatedOn: '2022-02-04T15:18:38',
        isActive: true,
        createdBy: 21,
        employeeCount: null,
        cityId: 2657,
        countryId: 148,
        stateId: 1330,
        isApproved: true,
        parentCompanyId: null,
        phoneNumber: null,
        isStrategic: true,
        id: 430,
        name: 'Paytm',
        website: null,
        pincode: 'ASDF1 RT',
        address1: '123',
        address2: null,
        address3: null,
        finance: null,
        parentComapnyName: null,
        createdByName: 'Jaya surya',
        leadSourceGroup: null,
        conversionNote: null,
        currency: {id: 141, name: 'Yemeni Rial', code: 'YER'},
        annualRevenue: {id: 49, name: '1 to 10 mn'},
        marketType: {id: 241, name: 'Non-Games'},
        city: {id: 2657, name: 'Durres'},
        state: {id: 1330, name: 'Durres'},
        country: {id: 148, name: 'Albania'},
        industry: {id: 9, name: 'Entertainment'},
        clientType: {id: 289, name: 'Self-Publishing Developer'},
        owners: [
          {
            userId: 21,
            name: 'Jaya surya',
            regions: [
              {id: 9, name: 'APAC'},
              {id: 7, name: 'LATAM'},
            ],
            departments: [
              {id: 311, name: 'vamshi new dep', code: 'new2354'},
              {id: 316, name: 'Resouce Type Test', code: 'RSTY'},
            ],
          },
          {
            userId: 120003203,
            name: 'thota venkat test',
            regions: [
              {id: 7, name: 'LATAM'},
              {id: 5, name: 'North America'},
            ],
            departments: null,
          },
          {
            userId: 120002009,
            name: 'Abbi Bowdidge',
            regions: [{id: 5, name: 'North America'}],
            departments: [{id: 7, name: 'a1', code: 'a1'}],
          },
          {
            userId: 120003204,
            name: 'Naresh Singh',
            regions: [{id: 9, name: 'APAC'}],
            departments: [
              {id: 5, name: '1518', code: '1518OR'},
              {id: 7, name: 'a1', code: 'a1'},
              {id: 16, name: 'a10', code: 'a10'},
              {id: 17, name: 'a11', code: 'a11'},
              {id: 18, name: 'a12', code: 'a12'},
              {id: 19, name: 'a13', code: 'a13'},
              {id: 8, name: 'a2', code: 'a2'},
              {id: 9, name: 'a3', code: 'a3'},
              {id: 10, name: 'a4', code: 'a4'},
              {id: 11, name: 'a5', code: 'a5'},
              {id: 12, name: 'a6', code: 'a6'},
              {id: 13, name: 'a7', code: 'a7'},
              {id: 14, name: 'a8', code: 'a8'},
              {id: 15, name: 'a9', code: 'a9'},
              {id: 408, name: 'Administration', code: 'Admin'},
              {id: 387, name: 'adqewd', code: 'wasd'},
              {id: 557, name: 'anjali', code: '4321'},
              {id: 378, name: 'aqrq234', code: 'awsf234'},
              {id: 376, name: 'asdfaewfwef', code: 'adsfwer23'},
              {id: 373, name: 'asdfq234', code: '234waewaed'},
              {id: 375, name: 'asdfwef', code: 'asdf'},
              {id: 356, name: 'asdfwer32', code: 'adf23'},
              {id: 394, name: 'asdwqed', code: 'wafe12'},
              {id: 556, name: 'aserftg', code: '3212'},
              {id: 542, name: 'assddd', code: '       2344'},
              {id: 463, name: 'AUDIO', code: 'AUD'},
              {id: 389, name: 'awefqwer324', code: 'q23r2qr'},
              {id: 2, name: 'bbb', code: 'hgh'},
              {id: 392, name: 'blafqo34r', code: '876341qwer'},
              {id: 350, name: 'blah', code: 'blahblah'},
              {id: 409, name: 'Business Audit and Compliance', code: 'BA&C'},
              {id: 410, name: 'Business Excellence', code: 'BE'},
              {id: 3, name: 'Can can', code: 'can-can'},
              {id: 455, name: 'CENTRAL DEVELOPMENT SERVICES', code: 'CDS'},
              {id: 476, name: 'CENTRAL TECH', code: 'CNTRLTECH'},
              {id: 318, name: 'check edit dep', code: 'ed345'},
              {id: 401, name: 'check serive department', code: 'ser123'},
              {id: 474, name: 'CO / DEV', code: 'CODEV'},
              {id: 475, name: 'CONTENT PRODUCTION', code: 'CNTPROD'},
              {id: 411, name: 'Corporate', code: 'Corp'},
              {id: 215, name: 'create', code: 'crt12'},
              {id: 164, name: 'CreateTest1', code: 'CTN'},
              {id: 471, name: 'CREST', code: 'CRE'},
              {id: 459, name: 'CUSTOMER EXPERIENCE', code: 'CX'},
              {id: 412, name: 'Customer Support', code: 'CS'},
              {id: 54, name: 'd1', code: 'd1c`1'},
              {id: 333, name: 'deport dpartment', code: 'deport'},
              {id: 371, name: 'dept name 893', code: 'dpetcodehgut3'},
              {id: 286, name: 'dept123a', code: 'dept_a'},
              {id: 336, name: 'dept72New', code: '1341'},
              {id: 372, name: 'deptname123', code: 'deptcode098'},
              {id: 388, name: 'deptname324er', code: 'awer'},
              {id: 127, name: 'Development', code: 'DV-01'},
              {id: 473, name: 'E SPORTS', code: 'ESPORTS'},
              {id: 340, name: 'eafq3r', code: '132412RE'},
              {id: 345, name: 'eafqef', code: 'asdfaf'},
              {id: 449, name: 'Executive Team', code: 'ET'},
              {id: 41, name: 'Fin', code: 'Fn-02'},
              {id: 38, name: 'Finance', code: 'FN-01'},
              {id: 413, name: 'Finance & Accounts', code: 'F&A'},
              {id: 414, name: 'Finance/GA', code: 'FGA'},
              {id: 446, name: 'FP&A', code: 'FPA'},
              {id: 415, name: 'G & A', code: 'G&A'},
              {id: 211, name: 'gam', code: 'gam123'},
              {id: 137, name: 'Game', code: 'GM-01'},
              {id: 477, name: 'GAMEDEV', code: 'GAME DEV'},
              {id: 205, name: 'Gamequality', code: 'cd4'},
              {id: 416, name: 'Games Quality Assurance', code: 'GQA LOB'},
              {id: 417, name: 'Global Project', code: 'GP'},
              {id: 418, name: 'Global Project Management', code: 'GPM'},
              {id: 419, name: 'GPMO', code: 'GPMO CODE'},
              {id: 29, name: 'GQA', code: 'GQ_01'},
              {id: 152, name: 'GTA_ENV', code: 'GTA_E01'},
              {id: 420, name: 'Human Resources', code: 'HR'},
              {id: 130, name: 'Hydebrad-or', code: 'hkjhkjh'},
              {id: 36, name: 'ImportDep', code: 'ID'},
              {id: 450, name: 'India Lead Gen', code: 'ILG'},
              {id: 421, name: 'IT', code: 'IT CODE'},
              {id: 1, name: 'IT Department', code: 'uu'},
              {id: 422, name: 'IT Support', code: 'ITS'},
              {id: 423, name: 'IT/GA', code: 'ITGA'},
              {id: 384, name: 'jghiuyt876', code: '89798yiutut'},
              {id: 386, name: 'jkawd', code: 'q23ewd'},
              {id: 25, name: 'KiziMona', code: 'KZ'},
              {id: 424, name: 'Learning & Development', code: 'L&D'},
              {id: 425, name: 'LOC- translation', code: 'LOC-T (LOB)'},
              {id: 426, name: 'LOC-LQA(and QA)', code: 'LOC-LQA(& QA)'},
              {id: 295, name: 'Localization', code: 'LOC'},
              {id: 278, name: 'Localization QA', code: 'LQA'},
              {id: 427, name: 'Management', code: 'Manage'},
              {id: 52, name: 'mar5', code: 'ar-001'},
              {id: 428, name: 'Marketing', code: 'MKTG'},
              {id: 429, name: 'Mastering Technician', code: 'MT'},
              {id: 430, name: 'MIS', code: 'MIS CODE'},
              {id: 369, name: 'na5jgkuiy7876587i59', code: '876ui85tyu6758'},
              {id: 365, name: 'najgk', code: '8768tyu'},
              {id: 366, name: 'najgkuiy78', code: '876u8tyu'},
              {id: 367, name: 'najgkuiy787658759', code: '876u8tyu6758'},
              {id: 368, name: 'najgkuiy7876587i59', code: '876ui8tyu6758'},
              {id: 334, name: 'name', code: 'dnlsbjb'},
              {id: 380, name: 'name234134ewrewr', code: 'asdfq23'},
              {id: 108, name: 'name4', code: 'jhferte'},
              {id: 381, name: 'namedept678', code: 'deptcode68797'},
              {id: 123, name: 'nedo', code: 'coe'},
              {id: 30, name: 'Network', code: 'NW-01'},
              {id: 258, name: 'Network Analyst', code: 'NA-01'},
              {id: 248, name: 'Network Control', code: 'NC-01'},
              {id: 31, name: 'Network12', code: 'NW-12'},
              {id: 32, name: 'Network2', code: 'NW-03'},
              {id: 33, name: 'Network3', code: 'NW-04'},
              {id: 34, name: 'Network4', code: 'Network4'},
              {id: 62, name: 'Network61', code: 'NW-61'},
              {id: 307, name: 'new  dep with sub', code: 'sub3425'},
              {id: 300, name: 'new dep', code: '1233'},
              {id: 305, name: 'new dep sub ', code: '1234New'},
              {id: 302, name: 'new dep1', code: 'code234'},
              {id: 304, name: 'new dep2', code: 'dep2'},
              {id: 48, name: 'new dept1', code: 'TD-10'},
              {id: 361, name: 'new name 404', code: 'code123'},
              {id: 335, name: 'newDept64', code: '12423D'},
              {id: 122, name: 'newo', code: 'newoc'},
              {id: 87, name: 'newone', code: 'newcode'},
              {id: 80, name: 'newtest', code: 'se'},
              {id: 28, name: 'OneSome', code: 'some-01'},
              {id: 431, name: 'Operation / Quality Assurance', code: 'O/QA'},
              {id: 432, name: 'Operations', code: 'Ops'},
              {id: 433, name: 'OR E-Sports', code: 'OR ES'},
              {id: 155, name: 'or with subLob', code: '123'},
              {id: 451, name: 'ORANGE ROCK', code: 'OR'},
              {id: 82, name: 'p1', code: 'p2'},
              {id: 290, name: 'Player Support', code: 'PLRS'},
              {id: 279, name: 'Porting', code: 'PRT'},
              {id: 339, name: 'POVER', code: '112QWS'},
              {id: 434, name: 'President', code: 'President CODE'},
              {id: 90, name: 'q1', code: 'q2'},
              {id: 435, name: 'QA(and LQA)', code: 'QA&LQA'},
              {id: 468, name: 'QBIST', code: 'QBT'},
              {id: 270, name: 'Quality Assurance', code: 'QA'},
              {id: 436, name: 'Quality Engineering', code: 'QE'},
              {id: 223, name: 'quality1', code: 'qty3'},
              {id: 316, name: 'Resouce Type Test', code: 'RSTY'},
              {id: 437, name: 'Sales', code: 'Sales CODE'},
              {id: 448, name: 'Sales and Marketing', code: 'S&M'},
              {id: 447, name: 'Sales SIDE', code: 'Sales (SIDE)'},
              {id: 358, name: 'sdfwefdasf', code: 'code1'},
              {id: 37, name: 'Security', code: 'ST-012'},
              {id: 117, name: 'shdept', code: 'shcode'},
              {id: 347, name: 'shiv N', code: 'awef'},
              {id: 348, name: 'shiv Nauni', code: 'awef87asd'},
              {id: 351, name: 'shiv Nauni aefk', code: '1232134TYIU'},
              {id: 364, name: 'Shivagi n', code: '575trry'},
              {id: 337, name: 'Shivangi', code: '122AXF'},
              {id: 363, name: 'Shivangi iaofw', code: '46246reyt'},
              {id: 344, name: 'Shivangi N', code: '1234'},
              {id: 342, name: 'Shivangi Nauni', code: '122412GYUG'},
              {id: 338, name: 'Shrey', code: '123AWE'},
              {id: 438, name: 'SIDE Audio', code: 'SIDE-A'},
              {id: 439, name: 'SIDE/Global', code: 'SIDE/G'},
              {id: 440, name: 'Software', code: 'SW'},
              {id: 441, name: 'Software Development', code: 'SD'},
              {id: 442, name: 'Software Quality Assurance', code: 'SQA'},
              {id: 27, name: 'Someone', code: 'Some'},
              {id: 443, name: 'Studio operations', code: 'SO'},
              {id: 26, name: 'Suzuka', code: 'KZ-01'},
              {id: 444, name: 'Technology', code: 'Techno'},
              {id: 203, name: 'tes', code: 'QA1'},
              {id: 72, name: 'Test Dept', code: 'TD-01'},
              {id: 76, name: 'test dept20', code: 'jh'},
              {id: 217, name: 'test1', code: 'tst1'},
              {id: 314, name: 'test11', code: 'test2'},
              {id: 255, name: 'Test12', code: 'T1'},
              {id: 100, name: 'testdep', code: 'testcode'},
              {id: 104, name: 'testdeptman', code: 'codewe'},
              {id: 227, name: 'testgfgfg', code: 'fefefe'},
              {id: 131, name: 'TestQA1', code: 'TST-011'},
              {id: 257, name: 'testtesting', code: 'sdfds2'},
              {id: 445, name: 'TW office', code: 'TWO'},
              {id: 284, name: 'Update Issue', code: 'UI12'},
              {id: 311, name: 'vamshi new dep', code: 'new2354'},
              {id: 277, name: 'Voice & Audio', code: 'VA'},
              {id: 153, name: 'vxvv', code: '344'},
              {id: 158, name: 'with sub Lobs2', code: 'H123'},
              {id: 60, name: 'x1', code: 'x2'},
              {id: 400, name: 'xkjc', code: 'sw1'},
              {id: 78, name: 'xyz100', code: 'sdfd'},
              {id: 382, name: 'yut7868', code: '8768tuyt'},
              {id: 63, name: 'z1', code: 'z2'},
            ],
          },
          {
            userId: 120002236,
            name: 'Abbot Yakuntzov',
            regions: [
              {id: 9, name: 'APAC'},
              {id: 7, name: 'LATAM'},
              {id: 5, name: 'North America'},
              {id: 4, name: 'EMEA'},
            ],
            departments: null,
          },
          {
            userId: 120001527,
            name: 'Abbe Yakobovitz',
            regions: [{id: 9, name: 'APAC'}],
            departments: null,
          },
          {
            userId: 120001697,
            name: 'Aaren Bremley',
            regions: [{id: 5, name: 'North America'}],
            departments: null,
          },
          {
            userId: 622,
            name: 'Abba Fell',
            regions: [{id: 7, name: 'LATAM'}],
            departments: null,
          },
        ],
        billingEntities: null,
        services: null,
      },
      {
        createdOn: '2022-02-04T15:11:08',
        updatedOn: '2022-02-04T15:11:08',
        isActive: true,
        createdBy: 21,
        employeeCount: null,
        cityId: 53,
        countryId: 35,
        stateId: 51,
        isApproved: true,
        parentCompanyId: 444,
        phoneNumber: '07892749233',
        isStrategic: false,
        id: 429,
        name: 'newAcc67',
        website: null,
        pincode: null,
        address1: null,
        address2: null,
        address3: null,
        finance: null,
        parentComapnyName: 'TBZ',
        OpportunityCount: 10,
        createdByName: 'Jaya surya',
        leadSourceGroup: null,
        conversionNote: null,
        currency: {id: 141, name: 'Yemeni Rial', code: 'YER'},
        annualRevenue: null,
        marketType: {id: 241, name: 'Non-Games'},
        city: {id: 53, name: 'Entalize'},
        state: {id: 51, name: 'Tokyo'},
        country: {id: 35, name: 'Japan'},
        industry: {id: 9, name: 'Entertainment'},
        clientType: {id: 290, name: 'Third Party'},
        owners: [
          {
            userId: 120003204,
            name: 'Naresh Singh',
            regions: [{id: 9, name: 'APAC'}],
            departments: [{id: 318, name: 'check edit dep', code: 'ed345'}],
          },
          {
            userId: 120003203,
            name: 'thota venkat test',
            regions: [{id: 9, name: 'APAC'}],
            departments: [{id: 318, name: 'check edit dep', code: 'ed345'}],
          },
          {
            userId: 120003202,
            name: 'Ramesh Kumar',
            regions: [{id: 4, name: 'EMEA'}],
            departments: null,
          },
          {
            userId: 120003199,
            name: null,
            regions: [{id: 5, name: 'North America'}],
            departments: null,
          },
        ],
        billingEntities: null,
        services: null,
      },
      {
        createdOn: '2022-02-04T11:08:54',
        updatedOn: '2022-02-04T11:08:54',
        isActive: true,
        createdBy: 21,
        employeeCount: null,
        cityId: 53,
        countryId: 35,
        stateId: 51,
        isApproved: true,
        parentCompanyId: null,
        phoneNumber: null,
        isStrategic: false,
        id: 427,
        name: 'conversionTestAcc',
        website: null,
        pincode: null,
        address1: null,
        address2: null,
        address3: null,
        finance: null,
        parentComapnyName: null,
        createdByName: 'Jaya surya',
        leadSourceGroup: 'Campaign',
        conversionNote: null,
        currency: {id: 141, name: 'Yemeni Rial', code: 'YER'},
        annualRevenue: null,
        marketType: {id: 241, name: 'Non-Games'},
        city: {id: 53, name: 'Entalize'},
        state: {id: 51, name: 'Tokyo'},
        country: {id: 35, name: 'Japan'},
        industry: {id: 9, name: 'Entertainment'},
        clientType: {id: 291, name: 'Affiliated Developer'},
        owners: [
          {
            userId: 21,
            name: 'Jaya surya',
            regions: [
              {id: 7, name: 'LATAM'},
              {id: 9, name: 'APAC'},
            ],
            departments: null,
          },
        ],
        billingEntities: null,
        services: null,
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/crm/crmcompany/',
};
