export default {
  response: {
    count: 18,
    next: null,
    previous: null,
    result: [
      {
        createdOn: '2022-02-01T13:47:16',
        updatedOn: '2022-02-01T13:47:16',
        isActive: true,
        createdBy: 21,
        employeeCount: null,
        emailId: null,
        cityId: 51,
        countryId: 34,
        isApproved: true,
        parentCompanyId: 419,
        phoneNumber: null,
        isStrategic: false,
        id: 418,
        name: 'asf345',
        website: null,
        pincode: null,
        address1: null,
        address2: null,
        address3: null,
        finance: null,
        parentComapnyName: 'hiuy89',
        OpportunityCount: 0,
        createdByName: 'Jaya Surya',
        leadSourceGroup: null,
        conversionNote: null,
        currency: {id: 11, name: 'Euros'},
        annualRevenue: null,
        marketType: {id: 11, name: 'Games'},
        city: {id: 51, name: 'Taipei'},
        country: {id: 34, name: 'Taiwan'},
        industry: {id: 10, name: 'Education'},
        clientType: {id: 287, name: 'Developers'},
        owners: [
          {
            userId: 120003112,
            name: 'Sushma Savanth',
            regions: [{id: 9, name: 'APAC'}],
            departments: null,
          },
        ],
        billingEntities: null,
        services: null,
      },
      {
        createdOn: '2022-02-01T13:23:00',
        updatedOn: '2022-02-01T13:23:00',
        isActive: true,
        createdBy: 21,
        employeeCount: null,
        emailId: null,
        cityId: 53,
        countryId: 35,
        isApproved: true,
        parentCompanyId: null,
        phoneNumber: null,
        isStrategic: false,
        id: 416,
        name: 'shivangi009',
        website: null,
        pincode: null,
        address1: null,
        address2: null,
        address3: null,
        finance: '123sdf',
        parentComapnyName: null,
        createdByName: 'Jaya Surya',
        leadSourceGroup: null,
        conversionNote: null,
        currency: {id: 11, name: 'Euros'},
        annualRevenue: null,
        marketType: {id: 11, name: 'Games'},
        city: {id: 53, name: 'Entalize'},
        country: {id: 35, name: 'Japan'},
        industry: {id: 9, name: 'Entertainment'},
        clientType: {id: 290, name: 'Third Party'},
        owners: [
          {
            userId: 120003112,
            name: 'Sushma Savanth',
            regions: [{id: 10, name: 'Asia'}],
            departments: null,
          },
        ],
        billingEntities: null,
        services: null,
      },
      {
        createdOn: '2022-01-25T05:43:24',
        updatedOn: '2022-01-25T05:43:24',
        isActive: true,
        createdBy: 120003107,
        employeeCount: 22,
        emailId: null,
        cityId: 53,
        countryId: 35,
        isApproved: true,
        parentCompanyId: null,
        phoneNumber: '8912341234',
        isStrategic: false,
        id: 412,
        name: 'Collins',
        website: 'https://www.google.com',
        pincode: '2387387434',
        address1: 'Bangalore',
        address2: 'Karnataka',
        address3: 'India',
        finance: 'gmm6w67fs',
        parentComapnyName: null,
        createdByName: 'Pavitra Hegde',
        leadSourceGroup: 'Other',
        conversionNote: null,
        currency: {id: 1, name: 'Rupee'},
        annualRevenue: {id: 48, name: 'Under 1mn'},
        marketType: {id: 241, name: 'Non-Games'},
        city: {id: 53, name: 'Entalize'},
        country: {id: 35, name: 'Japan'},
        industry: {id: 9, name: 'Entertainment'},
        clientType: {id: 287, name: 'Developers'},
        owners: [
          {
            userId: 120003107,
            name: 'Pavitra Hegde',
            regions: [
              {id: 9, name: 'APAC'},
              {id: 10, name: 'Asia'},
              {id: 7, name: 'LATAM'},
              {id: 8, name: 'Europe'},
              {id: 6, name: 'South America'},
              {id: 5, name: 'North America'},
              {id: 4, name: 'EMEA'},
              {id: 3, name: 'Bangalore'},
              {id: 2, name: 'Hyderabad'},
            ],
            departments: null,
          },
        ],
        billingEntities: null,
        services: null,
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/crm/crmcompany/',
};
