export default {
  response: {
    result: [
      {
        createdOn: '2022-01-25',
        updatedOn: '2022-01-25T13:41:58',
        createdBy: 21,
        firstName: 'Surya',
        lastName: 'Teja',
        emailId: 'surya.teja@ptw.com',
        mobileNumber: '9483483923',
        linkedInUrl: null,
        conversionNote: null,
        ownerId: 120003092,
        countryId: 33,
        cityId: 50,
        convertedById: 25,
        leadLocation: '0',
        additionalInfo:
          "Relative Length unit does not have fixed sizes, they are relative to something it could be the font size of a parent element or the size of a viewport. I prefer these units since they adjust to different screen sizes. They include :\nsgrfsgssgsdgsdfsadSFASADlkjlkjflfksdlfsdfsdfsdfsdfdsfsdfsdfsfsf {\n        msg: 'You Have No Access to this Application .Please Contact Your Administration',\n      }",
        isReview: true,
        isContact: true,
        isExclusion: false,
        id: 440,
        designation: 'Designer',
        address1: null,
        address2: '0',
        address3: '0',
        pincode: null,
        comment: 'conversion request - qualifying',
        ownerName: 'Cherice Yoell',
        name: 'Surya Teja',
        createdByName: 'Jaya Surya',
        convertedByName: 'praveen kumar',
        city: {
          id: 50,
          name: 'Magadan',
          stateId: 49,
          state: 'Maga Buryatdan',
        },
        country: {
          id: 33,
          name: 'Russia',
          regionId: 7,
          region: 'Asia',
        },
        gender: {
          id: 1,
          name: 'Male',
        },
        status: {
          id: 36,
          name: 'InActive',
        },
        crmSource: {
          id: 20,
          name: 'Offline',
        },
        crmSourceGroup: {
          id: 275,
          name: '2021 Event',
        },
        hearAboutUs: {
          id: 284,
          name: 'Twitter',
        },
        clientType: null,
        crmCompany: {
          id: 411,
          name: 'Juniper',
          website: null,
          employeeCount: 33,
          annualRevenue: {
            id: 52,
            name: 'above 200 mn',
          },
          country: {
            id: 35,
            name: 'Japan',
            regionId: 7,
            region: 'Asia',
          },
          city: {
            id: 54,
            name: 'Japan',
            stateId: 52,
            state: 'Japan',
          },
          address1: 'Japan',
          address2: 'Japan',
          address3: 'Japan',
          pincode: '327478',
          financeId: '176263',
          currency: {
            id: 8,
            name: 'Japanese Yen',
          },
          marketType: {
            id: 241,
            name: 'Non-Games',
          },
          industry: {
            id: 10,
            name: 'Education',
          },
          owners: [
            {
              userId: 120003107,
              name: 'Pavitra Hegde',
              regions: [
                {
                  id: 9,
                  name: 'APAC',
                },
                {
                  id: 7,
                  name: 'LATAM',
                },
                {
                  id: 4,
                  name: 'EMEA',
                },
                {
                  id: 5,
                  name: 'North America',
                },
              ],
              departments: null,
            },
          ],
          clientType: {
            id: 289,
            name: 'Self-Publishing Developer',
          },
          isApproved: true,
        },
        campaigns: [
          {
            id: 60,
            name: 'New',
          },
          {
            id: 59,
            name: 'campaign validation',
          },
          {
            id: 61,
            name: 'New 2',
          },
        ],
        services: null,
      },
      {
        createdOn: '2022-01-25',
        updatedOn: '2022-01-25T11:36:55',
        createdBy: 25,
        firstName: 'Akhanda',
        lastName: 'Thalaiva',
        emailId: 'thalaiva.crm@ptw.com',
        mobileNumber: null,
        linkedInUrl: null,
        conversionNote: null,
        ownerId: 120003089,
        countryId: 23,
        cityId: 40,
        convertedById: 25,
        leadLocation: '0',
        additionalInfo: null,
        isReview: true,
        isContact: true,
        isExclusion: false,
        id: 439,
        designation: 'HR',
        address1: null,
        address2: '0',
        address3: '0',
        pincode: null,
        comment: 'zJcmvcmx,n,c',
        ownerName: 'Sushmitha Rokhade',
        name: 'Akhanda Thalaiva',
        createdByName: 'praveen kumar',
        convertedByName: 'praveen kumar',
        city: {
          id: 40,
          name: 'Hyderabad',
          stateId: 39,
          state: 'Telangana',
        },
        country: {
          id: 23,
          name: 'India',
          regionId: 7,
          region: 'Asia',
        },
        gender: null,
        status: {
          id: 18,
          name: 'Active',
        },
        crmSource: null,
        crmSourceGroup: null,
        hearAboutUs: null,
        clientType: null,
        crmCompany: {
          id: 411,
          name: 'Juniper',
          website: null,
          employeeCount: 33,
          annualRevenue: {
            id: 52,
            name: 'above 200 mn',
          },
          country: {
            id: 35,
            name: 'Japan',
            regionId: 7,
            region: 'Asia',
          },
          city: {
            id: 54,
            name: 'Japan',
            stateId: 52,
            state: 'Japan',
          },
          address1: 'Japan',
          address2: 'Japan',
          address3: 'Japan',
          pincode: '327478',
          financeId: '176263',
          currency: {
            id: 8,
            name: 'Japanese Yen',
          },
          marketType: {
            id: 241,
            name: 'Non-Games',
          },
          industry: {
            id: 10,
            name: 'Education',
          },
          owners: [
            {
              userId: 120003107,
              name: 'Pavitra Hegde',
              regions: [
                {
                  id: 9,
                  name: 'APAC',
                },
                {
                  id: 7,
                  name: 'LATAM',
                },
                {
                  id: 4,
                  name: 'EMEA',
                },
                {
                  id: 5,
                  name: 'North America',
                },
              ],
              departments: null,
            },
          ],
          clientType: {
            id: 289,
            name: 'Self-Publishing Developer',
          },
          isApproved: true,
        },
        campaigns: [
          {
            id: 61,
            name: 'New 2',
          },
          {
            id: 60,
            name: 'New',
          },
        ],
        services: null,
      },
      {
        createdOn: '2022-01-25',
        updatedOn: '2022-01-25T05:45:38',
        createdBy: 120003107,
        firstName: 'George',
        lastName: 'Haris',
        emailId: 'george@gmail.com',
        mobileNumber: null,
        linkedInUrl: null,
        conversionNote: 'Good',
        ownerId: 22,
        countryId: 23,
        cityId: 39,
        convertedById: 120003107,
        leadLocation: '0',
        additionalInfo: null,
        isReview: true,
        isContact: true,
        isExclusion: false,
        id: 438,
        designation: 'QA',
        address1: 'Bangalore',
        address2: '0',
        address3: '0',
        pincode: '267476',
        comment: 'Good',
        ownerName: 'Ramesh babu',
        name: 'George Haris',
        createdByName: 'Pavitra Hegde',
        convertedByName: 'Pavitra Hegde',
        city: {
          id: 39,
          name: 'Bangalore',
          stateId: 38,
          state: 'Karnataka',
        },
        country: {
          id: 23,
          name: 'India',
          regionId: 7,
          region: 'Asia',
        },
        gender: {
          id: 3,
          name: 'Other',
        },
        status: {
          id: 18,
          name: 'Active',
        },
        crmSource: {
          id: 20,
          name: 'Offline',
        },
        crmSourceGroup: null,
        hearAboutUs: {
          id: 284,
          name: 'Twitter',
        },
        clientType: null,
        crmCompany: {
          id: 412,
          name: 'gsfdgdfg',
          website: null,
          employeeCount: 22,
          annualRevenue: {
            id: 48,
            name: 'Under 1mn',
          },
          country: {
            id: 30,
            name: 'Singapore',
            regionId: 7,
            region: 'Asia',
          },
          city: {
            id: 47,
            name: 'Singapore',
            stateId: 46,
            state: 'Singapore',
          },
          address1: null,
          address2: null,
          address3: null,
          pincode: null,
          financeId: 'gmm6w67fs',
          currency: {
            id: 2,
            name: 'Russian Rouble',
          },
          marketType: {
            id: 241,
            name: 'Non-Games',
          },
          industry: {
            id: 10,
            name: 'Education',
          },
          owners: [
            {
              userId: 120003075,
              name: 'Corabel Messent',
              regions: [
                {
                  id: 9,
                  name: 'APAC',
                },
              ],
              departments: null,
            },
          ],
          clientType: {
            id: 289,
            name: 'Self-Publishing Developer',
          },
          isApproved: true,
        },
        campaigns: [
          {
            id: 58,
            name: 'campaign',
          },
        ],
        services: null,
      },
      {
        createdOn: '2022-01-24',
        updatedOn: '2022-01-24T10:19:46',
        createdBy: 120003108,
        firstName: 'Clara',
        lastName: 'R',
        emailId: 'clara@gmail.com',
        mobileNumber: '4378436436',
        linkedInUrl: null,
        conversionNote: 'test',
        ownerId: 120003107,
        countryId: 35,
        cityId: 54,
        convertedById: 120003108,
        leadLocation: null,
        additionalInfo: 'test',
        isReview: true,
        isContact: true,
        isExclusion: false,
        id: 437,
        designation: 'QA',
        address1: 'Japan',
        address2: null,
        address3: null,
        pincode: '36746745',
        comment: 'Good',
        ownerName: 'Pavitra Hegde',
        name: 'Clara R',
        createdByName: 'Sreeja Vijayakumar',
        convertedByName: 'Sreeja Vijayakumar',
        city: {
          id: 54,
          name: 'Japan',
          stateId: 52,
          state: 'Japan',
        },
        country: {
          id: 35,
          name: 'Japan',
          regionId: 7,
          region: 'Asia',
        },
        gender: {
          id: 2,
          name: 'Female',
        },
        status: {
          id: 18,
          name: 'Active',
        },
        crmSource: {
          id: 19,
          name: 'Online',
        },
        crmSourceGroup: null,
        hearAboutUs: {
          id: 283,
          name: 'Referral',
        },
        clientType: null,
        crmCompany: {
          id: 411,
          name: 'Juniper',
          website: null,
          employeeCount: 33,
          annualRevenue: {
            id: 52,
            name: 'above 200 mn',
          },
          country: {
            id: 35,
            name: 'Japan',
            regionId: 7,
            region: 'Asia',
          },
          city: {
            id: 54,
            name: 'Japan',
            stateId: 52,
            state: 'Japan',
          },
          address1: 'Japan',
          address2: 'Japan',
          address3: 'Japan',
          pincode: '327478',
          financeId: '176263',
          currency: {
            id: 8,
            name: 'Japanese Yen',
          },
          marketType: {
            id: 241,
            name: 'Non-Games',
          },
          industry: {
            id: 10,
            name: 'Education',
          },
          owners: [
            {
              userId: 120003107,
              name: 'Pavitra Hegde',
              regions: [
                {
                  id: 9,
                  name: 'APAC',
                },
                {
                  id: 7,
                  name: 'LATAM',
                },
                {
                  id: 4,
                  name: 'EMEA',
                },
                {
                  id: 5,
                  name: 'North America',
                },
              ],
              departments: null,
            },
          ],
          clientType: {
            id: 289,
            name: 'Self-Publishing Developer',
          },
          isApproved: true,
        },
        campaigns: [
          {
            id: 59,
            name: 'campaign validation',
          },
          {
            id: 58,
            name: 'campaign',
          },
        ],
        services: null,
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/crm/crmcontacts/',
};
