export default {
  response: {
    count: 36,
    next: null,
    previous: null,
    result: [
      {regionId: 9, id: 37, name: 'Country-01', currency: 'INR', region: null},
      {regionId: 7, id: 35, name: 'Japan', currency: 'Yen', region: null},
      {
        regionId: 7,
        id: 34,
        name: 'Taiwan',
        currency: 'New Dollar',
        region: null,
      },
      {
        regionId: 7,
        id: 33,
        name: 'Russia',
        currency: 'Russian Rouble',
        region: null,
      },
      {
        regionId: 7,
        id: 32,
        name: 'Korea',
        currency: 'Korean won',
        region: null,
      },
      {
        regionId: 7,
        id: 31,
        name: 'South Korea',
        currency: 'South Korean won',
        region: null,
      },
      {
        regionId: 7,
        id: 30,
        name: 'Singapore',
        currency: 'Singapore dollar',
        region: null,
      },
      {
        regionId: 7,
        id: 29,
        name: 'Malaysia',
        currency: 'Malaysian Ringgit',
        region: null,
      },
      {
        regionId: 7,
        id: 28,
        name: 'Indonesia',
        currency: 'Indonesian Rupiah',
        region: null,
      },
      {
        regionId: 7,
        id: 27,
        name: 'Thailand',
        currency: 'Thai Baht',
        region: null,
      },
      {
        regionId: 7,
        id: 26,
        name: 'Myanmar',
        currency: 'Burmese Kyat',
        region: null,
      },
      {
        regionId: 7,
        id: 25,
        name: 'Bangladesh',
        currency: 'Bangladeshi Taka',
        region: null,
      },
      {
        regionId: 7,
        id: 24,
        name: 'Nepal',
        currency: 'Nepalese Rupee',
        region: null,
      },
      {
        regionId: 7,
        id: 23,
        name: 'India',
        currency: 'Indian Rupee',
        region: null,
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/wfm/countries/',
};
