export default {
  response: {
    count: 10,
    next: null,
    previous: null,
    result: [
      {
        firstName: 'Govind',
        lastName: 'Menon',
        userName: 'Govind',
        emailId: 'govind.menon@ptw.com',
        colorCode: null,
        isLevelThreeAdmin: false,
        id: 120003242,
        roles: null,
        location: 'Hyderabad',
        userStudios: [],
        created_by_relation: null,
        slots: [],
        eventDate: '2022-04-08',
      },
      {
        firstName: 'Kiran',
        lastName: 'V',
        userName: 'kiran',
        emailId: 'kiran.valluri@ptw.com',
        colorCode: null,
        isLevelThreeAdmin: false,
        id: 120003114,
        roles: null,
        location: 'Hyderabad',
        userStudios: [],
        created_by_relation: null,
        slots: [],
        eventDate: '2022-04-08',
      },
      {
        firstName: 'Sushma',
        lastName: 'Savanth',
        userName: 'sushmasavanth',
        emailId: 'savanth.sushma@ptw.com',
        colorCode: null,
        isLevelThreeAdmin: false,
        id: 120003112,
        roles: 'Admin, Director',
        location: 'Bangalore',
        userStudios: [],
        created_by_relation: null,
        slots: [
          {
            startTime: '19:00',
            endTime: '19:15',
            meetingId: 36,
            name: 'meeting',
            timezoneId: 44,
            notes: 'enter',
            organizerId: 120003107,
            organizer: 'Sushma Savanth',
            sideUsers: [
              {
                sideUserId: 120003107,
                sideUser: 'Sushma Savanth',
                colorCode: null,
              },
            ],
            studio: 'Cafe Ole',
            studioId: 4,
            studioRoom: 'Cafe Ole Room1',
            studioRoomId: 5,
            eventDate: '2022-04-08',
            type: 'Meeting',
          },
        ],
        eventDate: '2022-04-08',
      },
      {
        firstName: 'Atul',
        lastName: 'Bhat',
        userName: 'atulbhat',
        emailId: 'atul.bhatt@ptw.com',
        colorCode: null,
        isLevelThreeAdmin: false,
        id: 120003111,
        roles: 'Engineer',
        location: 'Bangalore',
        userStudios: [],
        created_by_relation: null,
        slots: [],
        eventDate: '2022-04-08',
      },
      {
        firstName: 'Sreeja',
        lastName: 'Vijayakumar',
        userName: 'SreejaV',
        emailId: 'sreeja.vijayakumar@ptw.com',
        colorCode: null,
        isLevelThreeAdmin: false,
        id: 120003108,
        roles: 'Engineer',
        location: 'Bangalore',
        userStudios: [],
        created_by_relation: null,
        slots: [],
        eventDate: '2022-04-08',
      },
      {
        firstName: 'Pavitra',
        lastName: 'Hegde',
        userName: 'pavitrahegde',
        emailId: 'pavitra.subramanyahegde@ptw.com',
        colorCode: null,
        isLevelThreeAdmin: false,
        id: 120003107,
        roles: 'Admin',
        location: 'Bangalore',
        userStudios: [],
        created_by_relation: null,
        slots: [],
        eventDate: '2022-04-08',
      },
      {
        firstName: 'Vinodh',
        lastName: 'gk',
        userName: 'vinodh',
        emailId: 'vinodh.gk@ptw.com',
        colorCode: null,
        isLevelThreeAdmin: false,
        id: 120003104,
        roles: 'Freelance PM',
        location: 'Bangalore',
        userStudios: [],
        created_by_relation: null,
        slots: [],
        eventDate: '2022-04-08',
      },
      {
        firstName: 'manikanta',
        lastName: 'kamepalli',
        userName: 'manikanta',
        emailId: 'manikanta.kamepalli@ptw.com',
        colorCode: null,
        isLevelThreeAdmin: false,
        id: 23,
        roles: null,
        location: 'Hyderabad',
        userStudios: [],
        created_by_relation: null,
        slots: [],
        eventDate: '2022-04-08',
      },
      {
        firstName: 'Naveen',
        lastName: 'Alle',
        userName: 'Naveen',
        emailId: 'naveenkumar.reddy@ptw.com',
        colorCode: null,
        isLevelThreeAdmin: false,
        id: 4,
        roles: 'Admin',
        location: 'Bangalore',
        userStudios: [],
        created_by_relation: null,
        slots: [],
        eventDate: '2022-04-08',
      },
      {
        firstName: 'admin',
        lastName: 'admin',
        userName: 'admin',
        emailId: 'admin@admin.com',
        colorCode: null,
        isLevelThreeAdmin: true,
        id: 1,
        roles: null,
        location: null,
        userStudios: [],
        created_by_relation: null,
        slots: [],
        eventDate: '2022-04-08',
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/side/users/',
};
