export default {
  response: {
    count: 87,
    next: null,
    previous: null,
    result: [
      {
        id: 318,
        name: 'check edit dep',
        code: 'ed345',
        isService: true,
        branches: [
          {
            regionId: 7,
            branchSpaceUnit: null,
            registrationNumber: null,
            countryId: 23,
            companyId: 1,
            phoneNumber: null,
            cityId: 40,
            createdBy: 1,
            emailId: null,
            branchCode: null,
            id: 40,
            blockNumber: null,
            legalEntity: null,
            town: null,
            buildingName: null,
            legalCode: null,
            pincode: null,
            createdOn: '2021-01-27T10:15:15',
            streetName: null,
            addressLine1: null,
            name: 'Hyderabad',
            isActive: true,
            branchSpace: null,
            addressLine2: null,
            comments: '',
            addressLine3: null,
            country: {
              name: 'India',
              createdBy: 1,
              shortName: 'Ind',
              createdOn: '2021-01-27T09:29:52',
              currency: 'Indian Rupee',
              id: 23,
              regionId: 7,
              isActive: true,
            },
          },
        ],
        hodId: null,
        subLobs: [
          {
            id: 320,
            name: 'sublob dep',
            code: null,
            services: [
              {
                id: 33,
                createdBy: 6,
                createdOn: '2022-02-09T10:55:32',
                name: 'edit service',
                isActive: true,
              },
            ],
            resourceTypes: [
              {
                id: 359,
                isActive: true,
                name: 'edit resource',
                createdBy: 6,
                createdOn: '2022-02-09T10:55:32',
              },
            ],
          },
        ],
      },
      {
        id: 316,
        name: 'Resouce Type Test',
        code: 'RSTY',
        isService: true,
        branches: [
          {
            regionId: 7,
            branchSpaceUnit: null,
            registrationNumber: null,
            countryId: 23,
            companyId: 1,
            phoneNumber: null,
            cityId: 40,
            createdBy: 1,
            emailId: null,
            branchCode: null,
            id: 40,
            blockNumber: null,
            legalEntity: null,
            town: null,
            buildingName: null,
            legalCode: null,
            pincode: null,
            createdOn: '2021-01-27T10:15:15',
            streetName: null,
            addressLine1: null,
            name: 'Hyderabad',
            isActive: true,
            branchSpace: null,
            addressLine2: null,
            comments: '',
            addressLine3: null,
            country: {
              name: 'India',
              createdBy: 1,
              shortName: 'Ind',
              createdOn: '2021-01-27T09:29:52',
              currency: 'Indian Rupee',
              id: 23,
              regionId: 7,
              isActive: true,
            },
          },
        ],
        hodId: null,
        subLobs: [
          {
            id: 327,
            name: 'code2',
            code: null,
            services: [],
            resourceTypes: [],
          },
          {
            id: 325,
            name: 'test6',
            code: null,
            services: [],
            resourceTypes: [],
          },
          {
            id: 317,
            name: 'RS Sub Lob',
            code: null,
            services: [
              {
                id: 30,
                createdBy: 6,
                createdOn: '2022-02-09T09:13:49',
                name: 'client details',
                isActive: true,
              },
            ],
            resourceTypes: [
              {
                id: 355,
                isActive: true,
                name: 'Functional Test',
                createdBy: 592,
                createdOn: '2022-02-09T07:26:08',
              },
            ],
          },
        ],
      },
      {
        id: 314,
        name: 'test11',
        code: 'test2',
        isService: true,
        branches: [
          {
            regionId: 7,
            branchSpaceUnit: null,
            registrationNumber: null,
            countryId: 23,
            companyId: 1,
            phoneNumber: null,
            cityId: 40,
            createdBy: 1,
            emailId: null,
            branchCode: null,
            id: 40,
            blockNumber: null,
            legalEntity: null,
            town: null,
            buildingName: null,
            legalCode: null,
            pincode: null,
            createdOn: '2021-01-27T10:15:15',
            streetName: null,
            addressLine1: null,
            name: 'Hyderabad',
            isActive: true,
            branchSpace: null,
            addressLine2: null,
            comments: '',
            addressLine3: null,
            country: {
              name: 'India',
              createdBy: 1,
              shortName: 'Ind',
              createdOn: '2021-01-27T09:29:52',
              currency: 'Indian Rupee',
              id: 23,
              regionId: 7,
              isActive: true,
            },
          },
        ],
        hodId: null,
        subLobs: [
          {
            id: 326,
            name: 'test41',
            code: null,
            services: [],
            resourceTypes: [],
          },
          {
            id: 315,
            name: 'test4',
            code: '0.8177055815113652',
            services: [
              {
                id: 31,
                createdBy: 6,
                createdOn: '2022-02-09T09:16:16',
                name: 'ser',
                isActive: true,
              },
            ],
            resourceTypes: [
              {
                id: 356,
                isActive: true,
                name: 'res',
                createdBy: 6,
                createdOn: '2022-02-09T09:16:16',
              },
            ],
          },
        ],
      },
      {
        id: 311,
        name: 'vamshi new dep',
        code: 'new2354',
        isService: true,
        branches: [
          {
            regionId: 7,
            branchSpaceUnit: null,
            registrationNumber: null,
            countryId: 35,
            companyId: 1,
            phoneNumber: null,
            cityId: 52,
            createdBy: 1,
            emailId: null,
            branchCode: null,
            id: 52,
            blockNumber: null,
            legalEntity: null,
            town: null,
            buildingName: null,
            legalCode: null,
            pincode: null,
            createdOn: '2021-01-27T10:15:55',
            streetName: null,
            addressLine1: null,
            name: 'Ptw Japan',
            isActive: true,
            branchSpace: null,
            addressLine2: null,
            comments: '',
            addressLine3: null,
            country: {
              name: 'Japan',
              createdBy: 1,
              shortName: 'Jap',
              createdOn: '2021-01-27T09:30:57',
              currency: 'Yen',
              id: 35,
              regionId: 7,
              isActive: true,
            },
          },
        ],
        hodId: 120003182,
        subLobs: [
          {
            id: 313,
            name: 'vam new sub 1',
            code: '0.4086616698251144',
            services: [],
            resourceTypes: [],
          },
          {
            id: 312,
            name: 'vam new sub',
            code: '0.32236879286406195',
            services: [
              {
                id: 17,
                createdBy: 6,
                createdOn: '2022-01-19T13:46:03',
                name: 'new ser 1',
                isActive: true,
              },
            ],
            resourceTypes: [],
          },
        ],
        hod: 'thota venkat',
        emailId: 'thoatavenkat361642597293202@gamail.com',
        designation: 'QA',
      },
      {
        id: 307,
        name: 'new  dep with sub',
        code: 'sub3425',
        isService: true,
        branches: [
          {
            regionId: 6,
            branchSpaceUnit: null,
            registrationNumber: null,
            countryId: 16,
            companyId: 1,
            phoneNumber: null,
            cityId: 31,
            createdBy: 1,
            emailId: null,
            branchCode: null,
            id: 64,
            blockNumber: null,
            legalEntity: null,
            town: null,
            buildingName: null,
            legalCode: null,
            pincode: '254354',
            createdOn: '2021-04-07T07:45:00',
            streetName: null,
            addressLine1: 'deede',
            name: 'Cap',
            isActive: true,
            branchSpace: null,
            addressLine2: null,
            comments: '',
            addressLine3: null,
            country: {
              name: 'South Africa',
              createdBy: 1,
              shortName: 'Sou',
              createdOn: '2021-01-27T09:29:10',
              currency: 'South African Rand',
              id: 16,
              regionId: 6,
              isActive: true,
            },
          },
        ],
        hodId: 120003183,
        subLobs: [
          {
            id: 309,
            name: 'sub depart 2',
            code: '0.7406917329417335',
            services: [],
            resourceTypes: [],
          },
          {
            id: 308,
            name: 'sub department',
            code: '4',
            services: [
              {
                id: 16,
                createdBy: 6,
                createdOn: '2022-01-19T13:28:22',
                name: 'nested service',
                isActive: true,
              },
            ],
            resourceTypes: [],
          },
        ],
        hod: 'yasar arafat',
        emailId: 'yasar1642597451920@ptw.com',
        designation: 'QA',
      },
      {
        id: 305,
        name: 'new dep sub ',
        code: '1234New',
        isService: true,
        branches: [
          {
            regionId: 6,
            branchSpaceUnit: null,
            registrationNumber: null,
            countryId: 16,
            companyId: 1,
            phoneNumber: null,
            cityId: 31,
            createdBy: 1,
            emailId: null,
            branchCode: null,
            id: 64,
            blockNumber: null,
            legalEntity: null,
            town: null,
            buildingName: null,
            legalCode: null,
            pincode: '254354',
            createdOn: '2021-04-07T07:45:00',
            streetName: null,
            addressLine1: 'deede',
            name: 'Cap',
            isActive: true,
            branchSpace: null,
            addressLine2: null,
            comments: '',
            addressLine3: null,
            country: {
              name: 'South Africa',
              createdBy: 1,
              shortName: 'Sou',
              createdOn: '2021-01-27T09:29:10',
              currency: 'South African Rand',
              id: 16,
              regionId: 6,
              isActive: true,
            },
          },
        ],
        hodId: 120003145,
        subLobs: [
          {
            id: 306,
            name: 'sub lob',
            code: '2',
            services: [
              {
                id: 15,
                createdBy: 6,
                createdOn: '2022-01-19T12:32:49',
                name: 'sub lob service',
                isActive: true,
              },
            ],
            resourceTypes: [],
          },
        ],
        hod: 'Shaheen Soudagar',
        emailId: 'shaheen.soudagar11642066756703@ptw.com',
        designation: 'QA',
      },
      {
        id: 304,
        name: 'new dep2',
        code: 'dep2',
        isService: false,
        branches: [
          {
            regionId: 7,
            branchSpaceUnit: null,
            registrationNumber: null,
            countryId: 23,
            companyId: 1,
            phoneNumber: null,
            cityId: 40,
            createdBy: 1,
            emailId: null,
            branchCode: null,
            id: 40,
            blockNumber: null,
            legalEntity: null,
            town: null,
            buildingName: null,
            legalCode: null,
            pincode: null,
            createdOn: '2021-01-27T10:15:15',
            streetName: null,
            addressLine1: null,
            name: 'Hyderabad',
            isActive: true,
            branchSpace: null,
            addressLine2: null,
            comments: '',
            addressLine3: null,
            country: {
              name: 'India',
              createdBy: 1,
              shortName: 'Ind',
              createdOn: '2021-01-27T09:29:52',
              currency: 'Indian Rupee',
              id: 23,
              regionId: 7,
              isActive: true,
            },
          },
        ],
        hodId: 120003157,
        subLobs: null,
        hod: 'ben ten',
        emailId: 'mohammed.arafat@ptw.com',
        designation: 'Developer',
      },
      {
        id: 302,
        name: 'new dep1',
        code: 'code234',
        isService: true,
        branches: [
          {
            regionId: 6,
            branchSpaceUnit: null,
            registrationNumber: null,
            countryId: 16,
            companyId: 1,
            phoneNumber: null,
            cityId: 31,
            createdBy: 1,
            emailId: null,
            branchCode: null,
            id: 64,
            blockNumber: null,
            legalEntity: null,
            town: null,
            buildingName: null,
            legalCode: null,
            pincode: '254354',
            createdOn: '2021-04-07T07:45:00',
            streetName: null,
            addressLine1: 'deede',
            name: 'Cap',
            isActive: true,
            branchSpace: null,
            addressLine2: null,
            comments: '',
            addressLine3: null,
            country: {
              name: 'South Africa',
              createdBy: 1,
              shortName: 'Sou',
              createdOn: '2021-01-27T09:29:10',
              currency: 'South African Rand',
              id: 16,
              regionId: 6,
              isActive: true,
            },
          },
        ],
        hodId: 120003140,
        subLobs: [
          {
            id: 303,
            name: 'new sub1',
            code: '11',
            services: [],
            resourceTypes: [],
          },
        ],
        hod: 'Shaheen Soudagar',
        emailId: 'devi.periyasamy1@ptw.com',
        designation: 'AI',
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/wfm/departments/',
};
