export default {
  response: {
    count: 11,
    next: null,
    previous: null,
    result: [
      {
        equipmentCount: 10,
        studioId: 6,
        id: 12,
        name: 'Tv V2',
        availableCount: 10,
        inUseCount: 0,
        studio: 'check for test',
        project_equipment: [],
        audition_equipment: [],
        session_equipment: [],
      },
      {
        equipmentCount: 20,
        studioId: 6,
        id: 11,
        name: 'Tv V1',
        availableCount: 20,
        inUseCount: 0,
        studio: 'check for test',
        project_equipment: [],
        audition_equipment: [],
        session_equipment: [],
      },
      {
        equipmentCount: 1,
        studioId: 8,
        id: 10,
        name: 'Ok',
        availableCount: 1,
        inUseCount: 0,
        studio: 'Cinemata',
        project_equipment: [],
        audition_equipment: [],
        session_equipment: [],
      },
      {
        equipmentCount: 2,
        studioId: 9,
        id: 9,
        name: 'New Charget',
        availableCount: 2,
        inUseCount: 0,
        studio: 'Side La updated',
        project_equipment: [],
        audition_equipment: [],
        session_equipment: [],
      },
      {
        equipmentCount: 20,
        studioId: 9,
        id: 8,
        name: 'Charger',
        availableCount: 20,
        inUseCount: 0,
        studio: 'Side La updated',
        project_equipment: [],
        audition_equipment: [],
        session_equipment: [],
      },
      {
        equipmentCount: 30,
        studioId: 5,
        id: 7,
        name: 'Laptop',
        availableCount: 30,
        inUseCount: 0,
        studio: 'WPP',
        project_equipment: [],
        audition_equipment: [],
        session_equipment: [],
      },
      {
        equipmentCount: 200,
        studioId: 5,
        id: 6,
        name: 'Mouse',
        availableCount: 191,
        inUseCount: 9,
        studio: 'WPP',
        project_equipment: [
          {
            projectId: 34,
            equipmentId: 6,
            count: 3,
          },
          {
            projectId: 1,
            equipmentId: 6,
            count: 4,
          },
        ],
        audition_equipment: [
          {
            auditionId: 26,
            auditionUniqueId: 'AUDI0026',
            count: 3,
          },
          {
            auditionId: 25,
            auditionUniqueId: 'AUDI0025',
            count: 3,
          },
          {
            auditionId: 21,
            auditionUniqueId: 'AUDI0021',
            count: 3,
          },
          {
            auditionId: 19,
            auditionUniqueId: 'AUDI0019',
            count: 4,
          },
          {
            auditionId: 11,
            auditionUniqueId: 'AUDI0011',
            count: 4,
          },
          {
            auditionId: 10,
            auditionUniqueId: 'AUDI0010',
            count: 4,
          },
          {
            auditionId: 9,
            auditionUniqueId: 'AUDI0009',
            count: 4,
          },
          {
            auditionId: 8,
            auditionUniqueId: 'AUDI0008',
            count: 4,
          },
          {
            auditionId: 2,
            auditionUniqueId: 'AUDI0002',
            count: 10,
          },
        ],
        session_equipment: [
          {
            sessionId: 275,
            sessionUniqueId: 'SISSRNDK0275',
            count: 3,
          },
          {
            sessionId: 274,
            sessionUniqueId: 'SISSRNDK0274',
            count: 3,
          },
          {
            sessionId: 273,
            sessionUniqueId: 'SISSRNDK0273',
            count: 3,
          },
          {
            sessionId: 271,
            sessionUniqueId: 'SISSRNDK0271',
            count: 3,
          },
          {
            sessionId: 269,
            sessionUniqueId: 'SISSRNDK0269',
            count: 3,
          },
          {
            sessionId: 268,
            sessionUniqueId: 'SISSRNDK0268',
            count: 3,
          },
          {
            sessionId: 266,
            sessionUniqueId: 'SISSRNDK0266',
            count: 3,
          },
          {
            sessionId: 265,
            sessionUniqueId: 'SISSRNDK0265',
            count: 3,
          },
          {
            sessionId: 264,
            sessionUniqueId: 'SISSRNDK0264',
            count: 3,
          },
          {
            sessionId: 263,
            sessionUniqueId: 'SISSRNDK0263',
            count: 3,
          },
          {
            sessionId: 260,
            sessionUniqueId: 'SISSRNDK0260',
            count: 3,
          },
          {
            sessionId: 258,
            sessionUniqueId: 'SISSRNDK0258',
            count: 3,
          },
          {
            sessionId: 251,
            sessionUniqueId: 'SISSRNDK0251',
            count: 3,
          },
          {
            sessionId: 225,
            sessionUniqueId: 'SISSRNDK0225',
            count: 3,
          },
          {
            sessionId: 223,
            sessionUniqueId: 'SISSRNDK0223',
            count: 3,
          },
          {
            sessionId: 222,
            sessionUniqueId: 'SISSRNDK0222',
            count: 3,
          },
          {
            sessionId: 208,
            sessionUniqueId: 'SISSRNDK0208',
            count: 4,
          },
          {
            sessionId: 195,
            sessionUniqueId: 'SISSRNDK0195',
            count: 4,
          },
          {
            sessionId: 194,
            sessionUniqueId: 'SISSRNDK0194',
            count: 4,
          },
          {
            sessionId: 193,
            sessionUniqueId: 'SISSRNDK0193',
            count: 4,
          },
          {
            sessionId: 192,
            sessionUniqueId: 'SISSRNDK0192',
            count: 4,
          },
          {
            sessionId: 191,
            sessionUniqueId: 'SISSRNDK0191',
            count: 4,
          },
          {
            sessionId: 190,
            sessionUniqueId: 'SISSRNDK0190',
            count: 4,
          },
          {
            sessionId: 189,
            sessionUniqueId: 'SISSRNDK0189',
            count: 4,
          },
          {
            sessionId: 188,
            sessionUniqueId: 'SISSRNDK0188',
            count: 4,
          },
          {
            sessionId: 187,
            sessionUniqueId: 'SISSRNDK0187',
            count: 4,
          },
          {
            sessionId: 184,
            sessionUniqueId: 'SISSRNDK0184',
            count: 4,
          },
          {
            sessionId: 183,
            sessionUniqueId: 'SISSRNDK0183',
            count: 4,
          },
          {
            sessionId: 135,
            sessionUniqueId: 'SISSRNDK0135',
            count: 4,
          },
          {
            sessionId: 134,
            sessionUniqueId: 'SISSRNDK0134',
            count: 4,
          },
          {
            sessionId: 127,
            sessionUniqueId: 'SISSRNDK0127',
            count: 4,
          },
          {
            sessionId: 126,
            sessionUniqueId: 'SISSRNDK0126',
            count: 4,
          },
          {
            sessionId: 105,
            sessionUniqueId: 'SISSRNDK0105',
            count: 4,
          },
          {
            sessionId: 99,
            sessionUniqueId: 'SISSRNDK0099',
            count: 4,
          },
          {
            sessionId: 96,
            sessionUniqueId: 'SISSRNDK0096',
            count: 4,
          },
          {
            sessionId: 95,
            sessionUniqueId: 'SISSRNDK0095',
            count: 4,
          },
          {
            sessionId: 94,
            sessionUniqueId: 'SISSRNDK0094',
            count: 4,
          },
          {
            sessionId: 92,
            sessionUniqueId: 'SISSRNDK0092',
            count: 4,
          },
          {
            sessionId: 90,
            sessionUniqueId: 'SISSRNDK0090',
            count: 4,
          },
          {
            sessionId: 89,
            sessionUniqueId: 'SISSRNDK0089',
            count: 4,
          },
          {
            sessionId: 67,
            sessionUniqueId: 'SISSRNDK0067',
            count: 10,
          },
          {
            sessionId: 64,
            sessionUniqueId: 'SISSRNDK0064',
            count: 4,
          },
          {
            sessionId: 62,
            sessionUniqueId: 'SISSRNDK0062',
            count: 4,
          },
          {
            sessionId: 58,
            sessionUniqueId: 'SISSRNDK0058',
            count: 4,
          },
          {
            sessionId: 57,
            sessionUniqueId: 'SISSRNDK0057',
            count: 4,
          },
          {
            sessionId: 52,
            sessionUniqueId: 'SISSRNDK0052',
            count: 4,
          },
          {
            sessionId: 44,
            sessionUniqueId: 'SISSRNDK0044',
            count: 2,
          },
          {
            sessionId: 24,
            sessionUniqueId: 'SISSRNDK0024',
            count: 4,
          },
          {
            sessionId: 21,
            sessionUniqueId: 'SISSRNDK0021',
            count: 4,
          },
          {
            sessionId: 20,
            sessionUniqueId: 'SISSRNDK0020',
            count: 4,
          },
          {
            sessionId: 19,
            sessionUniqueId: 'SISSRNDK0019',
            count: 4,
          },
          {
            sessionId: 18,
            sessionUniqueId: 'SISSRNDK0018',
            count: 4,
          },
          {
            sessionId: 17,
            sessionUniqueId: 'SISSRNDK0017',
            count: 4,
          },
          {
            sessionId: 16,
            sessionUniqueId: 'SISSRNDK0016',
            count: 4,
          },
          {
            sessionId: 15,
            sessionUniqueId: 'SISSRNDK0015',
            count: 4,
          },
          {
            sessionId: 14,
            sessionUniqueId: 'SISSRNDK0014',
            count: 4,
          },
          {
            sessionId: 9,
            sessionUniqueId: 'SISSRNDK0009',
            count: 4,
          },
          {
            sessionId: 7,
            sessionUniqueId: 'SISSRNDK0007',
            count: 4,
          },
          {
            sessionId: 6,
            sessionUniqueId: 'SISSRNDK0006',
            count: 4,
          },
          {
            sessionId: 5,
            sessionUniqueId: 'SISSRNDK0005',
            count: 4,
          },
          {
            sessionId: 4,
            sessionUniqueId: 'SISSRNDK0004',
            count: 4,
          },
          {
            sessionId: 3,
            sessionUniqueId: 'SISSRNDK0003',
            count: 4,
          },
        ],
      },
      {
        equipmentCount: 200,
        studioId: 1,
        id: 5,
        name: 'Tv',
        availableCount: 200,
        inUseCount: 0,
        studio: 'Studio Bangalore',
        project_equipment: [],
        audition_equipment: [
          {
            auditionId: 5,
            auditionUniqueId: 'AUDI0005',
            count: 2,
          },
          {
            auditionId: 2,
            auditionUniqueId: 'AUDI0002',
            count: 2,
          },
        ],
        session_equipment: [],
      },
      {
        equipmentCount: 600,
        studioId: 1,
        id: 4,
        name: 'Cables',
        availableCount: 581,
        inUseCount: 19,
        studio: 'Studio Bangalore',
        project_equipment: [
          {
            projectId: 34,
            equipmentId: 4,
            count: 3,
          },
          {
            projectId: 3,
            equipmentId: 4,
            count: 10,
          },
          {
            projectId: 1,
            equipmentId: 4,
            count: 600,
          },
        ],
        audition_equipment: [
          {
            auditionId: 27,
            auditionUniqueId: 'AUDI0027',
            count: 10,
          },
          {
            auditionId: 26,
            auditionUniqueId: 'AUDI0026',
            count: 3,
          },
          {
            auditionId: 25,
            auditionUniqueId: 'AUDI0025',
            count: 3,
          },
          {
            auditionId: 24,
            auditionUniqueId: 'AUDI0024',
            count: 10,
          },
          {
            auditionId: 23,
            auditionUniqueId: 'AUDI0023',
            count: 10,
          },
          {
            auditionId: 22,
            auditionUniqueId: 'AUDI0022',
            count: 10,
          },
          {
            auditionId: 20,
            auditionUniqueId: 'AUDI0020',
            count: 10,
          },
          {
            auditionId: 19,
            auditionUniqueId: 'AUDI0019',
            count: 600,
          },
          {
            auditionId: 18,
            auditionUniqueId: 'AUDI0018',
            count: 10,
          },
          {
            auditionId: 17,
            auditionUniqueId: 'AUDI0017',
            count: 10,
          },
          {
            auditionId: 16,
            auditionUniqueId: 'AUDI0016',
            count: 10,
          },
          {
            auditionId: 15,
            auditionUniqueId: 'AUDI0015',
            count: 10,
          },
          {
            auditionId: 14,
            auditionUniqueId: 'AUDI0014',
            count: 10,
          },
          {
            auditionId: 13,
            auditionUniqueId: 'AUDI0013',
            count: 10,
          },
          {
            auditionId: 12,
            auditionUniqueId: 'AUDI0012',
            count: 10,
          },
          {
            auditionId: 11,
            auditionUniqueId: 'AUDI0011',
            count: 600,
          },
          {
            auditionId: 10,
            auditionUniqueId: 'AUDI0010',
            count: 600,
          },
          {
            auditionId: 7,
            auditionUniqueId: 'AUDI0007',
            count: 600,
          },
          {
            auditionId: 6,
            auditionUniqueId: 'AUDI0006',
            count: 10,
          },
          {
            auditionId: 4,
            auditionUniqueId: 'AUDI0004',
            count: 3,
          },
        ],
        session_equipment: [
          {
            sessionId: 275,
            sessionUniqueId: 'SISSRNDK0275',
            count: 3,
          },
          {
            sessionId: 274,
            sessionUniqueId: 'SISSRNDK0274',
            count: 3,
          },
          {
            sessionId: 273,
            sessionUniqueId: 'SISSRNDK0273',
            count: 3,
          },
          {
            sessionId: 272,
            sessionUniqueId: 'SISSRNDK0272',
            count: 10,
          },
          {
            sessionId: 271,
            sessionUniqueId: 'SISSRNDK0271',
            count: 3,
          },
          {
            sessionId: 269,
            sessionUniqueId: 'SISSRNDK0269',
            count: 3,
          },
          {
            sessionId: 268,
            sessionUniqueId: 'SISSRNDK0268',
            count: 3,
          },
          {
            sessionId: 267,
            sessionUniqueId: 'SISSRNDK0267',
            count: 10,
          },
          {
            sessionId: 266,
            sessionUniqueId: 'SISSRNDK0266',
            count: 3,
          },
          {
            sessionId: 265,
            sessionUniqueId: 'SISSRNDK0265',
            count: 3,
          },
          {
            sessionId: 264,
            sessionUniqueId: 'SISSRNDK0264',
            count: 3,
          },
          {
            sessionId: 263,
            sessionUniqueId: 'SISSRNDK0263',
            count: 3,
          },
          {
            sessionId: 262,
            sessionUniqueId: 'SISSRNDK0262',
            count: 10,
          },
          {
            sessionId: 261,
            sessionUniqueId: 'SISSRNDK0261',
            count: 10,
          },
          {
            sessionId: 260,
            sessionUniqueId: 'SISSRNDK0260',
            count: 3,
          },
          {
            sessionId: 259,
            sessionUniqueId: 'SISSRNDK0259',
            count: 123,
          },
          {
            sessionId: 258,
            sessionUniqueId: 'SISSRNDK0258',
            count: 3,
          },
          {
            sessionId: 256,
            sessionUniqueId: 'SISSRNDK0256',
            count: 10,
          },
          {
            sessionId: 255,
            sessionUniqueId: 'SISSRNDK0255',
            count: 10,
          },
          {
            sessionId: 254,
            sessionUniqueId: 'SISSRNDK0254',
            count: 10,
          },
          {
            sessionId: 253,
            sessionUniqueId: 'SISSRNDK0253',
            count: 10,
          },
          {
            sessionId: 252,
            sessionUniqueId: 'SISSRNDK0252',
            count: 10,
          },
          {
            sessionId: 251,
            sessionUniqueId: 'SISSRNDK0251',
            count: 3,
          },
          {
            sessionId: 250,
            sessionUniqueId: 'SISSRNDK0250',
            count: 10,
          },
          {
            sessionId: 249,
            sessionUniqueId: 'SISSRNDK0249',
            count: 10,
          },
          {
            sessionId: 248,
            sessionUniqueId: 'SISSRNDK0248',
            count: 10,
          },
          {
            sessionId: 247,
            sessionUniqueId: 'SISSRNDK0247',
            count: 10,
          },
          {
            sessionId: 239,
            sessionUniqueId: 'SISSRNDK0239',
            count: 10,
          },
          {
            sessionId: 225,
            sessionUniqueId: 'SISSRNDK0225',
            count: 3,
          },
          {
            sessionId: 223,
            sessionUniqueId: 'SISSRNDK0223',
            count: 3,
          },
          {
            sessionId: 222,
            sessionUniqueId: 'SISSRNDK0222',
            count: 3,
          },
          {
            sessionId: 219,
            sessionUniqueId: 'SISSRNDK0219',
            count: 10,
          },
          {
            sessionId: 218,
            sessionUniqueId: 'SISSRNDK0218',
            count: 10,
          },
          {
            sessionId: 217,
            sessionUniqueId: 'SISSRNDK0217',
            count: 10,
          },
          {
            sessionId: 214,
            sessionUniqueId: 'SISSRNDK0214',
            count: 10,
          },
          {
            sessionId: 213,
            sessionUniqueId: 'SISSRNDK0213',
            count: 10,
          },
          {
            sessionId: 212,
            sessionUniqueId: 'SISSRNDK0212',
            count: 10,
          },
          {
            sessionId: 211,
            sessionUniqueId: 'SISSRNDK0211',
            count: 10,
          },
          {
            sessionId: 209,
            sessionUniqueId: 'SISSRNDK0209',
            count: 10,
          },
          {
            sessionId: 207,
            sessionUniqueId: 'SISSRNDK0207',
            count: 10,
          },
          {
            sessionId: 204,
            sessionUniqueId: 'SISSRNDK0204',
            count: 10,
          },
          {
            sessionId: 203,
            sessionUniqueId: 'SISSRNDK0203',
            count: 10,
          },
          {
            sessionId: 187,
            sessionUniqueId: 'SISSRNDK0187',
            count: 600,
          },
          {
            sessionId: 186,
            sessionUniqueId: 'SISSRNDK0186',
            count: 12,
          },
          {
            sessionId: 183,
            sessionUniqueId: 'SISSRNDK0183',
            count: 600,
          },
          {
            sessionId: 182,
            sessionUniqueId: 'SISSRNDK0182',
            count: 10,
          },
          {
            sessionId: 181,
            sessionUniqueId: 'SISSRNDK0181',
            count: 10,
          },
          {
            sessionId: 180,
            sessionUniqueId: 'SISSRNDK0180',
            count: 10,
          },
          {
            sessionId: 179,
            sessionUniqueId: 'SISSRNDK0179',
            count: 10,
          },
          {
            sessionId: 178,
            sessionUniqueId: 'SISSRNDK0178',
            count: 10,
          },
          {
            sessionId: 177,
            sessionUniqueId: 'SISSRNDK0177',
            count: 10,
          },
          {
            sessionId: 176,
            sessionUniqueId: 'SISSRNDK0176',
            count: 10,
          },
          {
            sessionId: 175,
            sessionUniqueId: 'SISSRNDK0175',
            count: 10,
          },
          {
            sessionId: 174,
            sessionUniqueId: 'SISSRNDK0174',
            count: 10,
          },
          {
            sessionId: 173,
            sessionUniqueId: 'SISSRNDK0173',
            count: 10,
          },
          {
            sessionId: 171,
            sessionUniqueId: 'SISSRNDK0171',
            count: 10,
          },
          {
            sessionId: 170,
            sessionUniqueId: 'SISSRNDK0170',
            count: 10,
          },
          {
            sessionId: 169,
            sessionUniqueId: 'SISSRNDK0169',
            count: 10,
          },
          {
            sessionId: 168,
            sessionUniqueId: 'SISSRNDK0168',
            count: 10,
          },
          {
            sessionId: 165,
            sessionUniqueId: 'SISSRNDK0165',
            count: 10,
          },
          {
            sessionId: 163,
            sessionUniqueId: 'SISSRNDK0163',
            count: 10,
          },
          {
            sessionId: 161,
            sessionUniqueId: 'SISSRNDK0161',
            count: 10,
          },
          {
            sessionId: 160,
            sessionUniqueId: 'SISSRNDK0160',
            count: 10,
          },
          {
            sessionId: 159,
            sessionUniqueId: 'SISSRNDK0159',
            count: 10,
          },
          {
            sessionId: 158,
            sessionUniqueId: 'SISSRNDK0158',
            count: 10,
          },
          {
            sessionId: 157,
            sessionUniqueId: 'SISSRNDK0157',
            count: 10,
          },
          {
            sessionId: 156,
            sessionUniqueId: 'SISSRNDK0156',
            count: 10,
          },
          {
            sessionId: 155,
            sessionUniqueId: 'SISSRNDK0155',
            count: 10,
          },
          {
            sessionId: 154,
            sessionUniqueId: 'SISSRNDK0154',
            count: 10,
          },
          {
            sessionId: 153,
            sessionUniqueId: 'SISSRNDK0153',
            count: 10,
          },
          {
            sessionId: 152,
            sessionUniqueId: 'SISSRNDK0152',
            count: 10,
          },
          {
            sessionId: 151,
            sessionUniqueId: 'SISSRNDK0151',
            count: 10,
          },
          {
            sessionId: 150,
            sessionUniqueId: 'SISSRNDK0150',
            count: 10,
          },
          {
            sessionId: 148,
            sessionUniqueId: 'SISSRNDK0148',
            count: 10,
          },
          {
            sessionId: 147,
            sessionUniqueId: 'SISSRNDK0147',
            count: 10,
          },
          {
            sessionId: 146,
            sessionUniqueId: 'SISSRNDK0146',
            count: 10,
          },
          {
            sessionId: 145,
            sessionUniqueId: 'SISSRNDK0145',
            count: 10,
          },
          {
            sessionId: 144,
            sessionUniqueId: 'SISSRNDK0144',
            count: 10,
          },
          {
            sessionId: 143,
            sessionUniqueId: 'SISSRNDK0143',
            count: 10,
          },
          {
            sessionId: 142,
            sessionUniqueId: 'SISSRNDK0142',
            count: 10,
          },
          {
            sessionId: 141,
            sessionUniqueId: 'SISSRNDK0141',
            count: 10,
          },
          {
            sessionId: 140,
            sessionUniqueId: 'SISSRNDK0140',
            count: 10,
          },
          {
            sessionId: 138,
            sessionUniqueId: 'SISSRNDK0138',
            count: 10,
          },
          {
            sessionId: 137,
            sessionUniqueId: 'SISSRNDK0137',
            count: 10,
          },
          {
            sessionId: 136,
            sessionUniqueId: 'SISSRNDK0136',
            count: 10,
          },
          {
            sessionId: 133,
            sessionUniqueId: 'SISSRNDK0133',
            count: 10,
          },
          {
            sessionId: 131,
            sessionUniqueId: 'SISSRNDK0131',
            count: 10,
          },
          {
            sessionId: 130,
            sessionUniqueId: 'SISSRNDK0130',
            count: 10,
          },
          {
            sessionId: 129,
            sessionUniqueId: 'SISSRNDK0129',
            count: 10,
          },
          {
            sessionId: 128,
            sessionUniqueId: 'SISSRNDK0128',
            count: 10,
          },
          {
            sessionId: 125,
            sessionUniqueId: 'SISSRNDK0125',
            count: 10,
          },
          {
            sessionId: 123,
            sessionUniqueId: 'SISSRNDK0123',
            count: 10,
          },
          {
            sessionId: 122,
            sessionUniqueId: 'SISSRNDK0122',
            count: 10,
          },
          {
            sessionId: 109,
            sessionUniqueId: 'SISSRNDK0109',
            count: 10,
          },
          {
            sessionId: 95,
            sessionUniqueId: 'SISSRNDK0095',
            count: 600,
          },
          {
            sessionId: 87,
            sessionUniqueId: 'SISSRNDK0087',
            count: 10,
          },
          {
            sessionId: 67,
            sessionUniqueId: 'SISSRNDK0067',
            count: 20,
          },
          {
            sessionId: 70,
            sessionUniqueId: 'SISSRNDK0070',
            count: 10,
          },
          {
            sessionId: 64,
            sessionUniqueId: 'SISSRNDK0064',
            count: 60,
          },
          {
            sessionId: 61,
            sessionUniqueId: 'SISSRNDK0061',
            count: 10,
          },
          {
            sessionId: 60,
            sessionUniqueId: 'SISSRNDK0060',
            count: 10,
          },
          {
            sessionId: 58,
            sessionUniqueId: 'SISSRNDK0058',
            count: 3,
          },
          {
            sessionId: 52,
            sessionUniqueId: 'SISSRNDK0052',
            count: 3,
          },
          {
            sessionId: 51,
            sessionUniqueId: 'SISSRNDK0051',
            count: 10,
          },
          {
            sessionId: 50,
            sessionUniqueId: 'SISSRNDK0050',
            count: 10,
          },
          {
            sessionId: 49,
            sessionUniqueId: 'SISSRNDK0049',
            count: 10,
          },
          {
            sessionId: 48,
            sessionUniqueId: 'SISSRNDK0048',
            count: 10,
          },
          {
            sessionId: 46,
            sessionUniqueId: 'SISSRNDK0046',
            count: 10,
          },
          {
            sessionId: 45,
            sessionUniqueId: 'SISSRNDK0045',
            count: 10,
          },
          {
            sessionId: 34,
            sessionUniqueId: 'SISSRNDK0034',
            count: 10,
          },
          {
            sessionId: 33,
            sessionUniqueId: 'SISSRNDK0033',
            count: 10,
          },
          {
            sessionId: 32,
            sessionUniqueId: 'SISSRNDK0032',
            count: 10,
          },
          {
            sessionId: 31,
            sessionUniqueId: 'SISSRNDK0031',
            count: 10,
          },
          {
            sessionId: 30,
            sessionUniqueId: 'SISSRNDK0030',
            count: 10,
          },
          {
            sessionId: 29,
            sessionUniqueId: 'SISSRNDK0029',
            count: 10,
          },
          {
            sessionId: 28,
            sessionUniqueId: 'SISSRNDK0028',
            count: 10,
          },
          {
            sessionId: 27,
            sessionUniqueId: 'SISSRNDK0027',
            count: 10,
          },
          {
            sessionId: 26,
            sessionUniqueId: 'SISSRNDK0026',
            count: 10,
          },
          {
            sessionId: 25,
            sessionUniqueId: 'SISSRNDK0025',
            count: 10,
          },
          {
            sessionId: 24,
            sessionUniqueId: 'SISSRNDK0024',
            count: 3,
          },
          {
            sessionId: 22,
            sessionUniqueId: 'SISSRNDK0022',
            count: 10,
          },
          {
            sessionId: 21,
            sessionUniqueId: 'SISSRNDK0021',
            count: 3,
          },
          {
            sessionId: 20,
            sessionUniqueId: 'SISSRNDK0020',
            count: 3,
          },
          {
            sessionId: 19,
            sessionUniqueId: 'SISSRNDK0019',
            count: 3,
          },
          {
            sessionId: 18,
            sessionUniqueId: 'SISSRNDK0018',
            count: 3,
          },
          {
            sessionId: 17,
            sessionUniqueId: 'SISSRNDK0017',
            count: 3,
          },
          {
            sessionId: 16,
            sessionUniqueId: 'SISSRNDK0016',
            count: 3,
          },
          {
            sessionId: 15,
            sessionUniqueId: 'SISSRNDK0015',
            count: 3,
          },
          {
            sessionId: 14,
            sessionUniqueId: 'SISSRNDK0014',
            count: 3,
          },
          {
            sessionId: 13,
            sessionUniqueId: 'SISSRNDK0013',
            count: 10,
          },
          {
            sessionId: 12,
            sessionUniqueId: 'SISSRNDK0012',
            count: 10,
          },
          {
            sessionId: 11,
            sessionUniqueId: 'SISSRNDK0011',
            count: 10,
          },
          {
            sessionId: 10,
            sessionUniqueId: 'SISSRNDK0010',
            count: 10,
          },
          {
            sessionId: 9,
            sessionUniqueId: 'SISSRNDK0009',
            count: 3,
          },
          {
            sessionId: 7,
            sessionUniqueId: 'SISSRNDK0007',
            count: 3,
          },
          {
            sessionId: 6,
            sessionUniqueId: 'SISSRNDK0006',
            count: 3,
          },
          {
            sessionId: 5,
            sessionUniqueId: 'SISSRNDK0005',
            count: 3,
          },
          {
            sessionId: 4,
            sessionUniqueId: 'SISSRNDK0004',
            count: 3,
          },
          {
            sessionId: 3,
            sessionUniqueId: 'SISSRNDK0003',
            count: 3,
          },
        ],
      },
      {
        equipmentCount: 300,
        studioId: 1,
        id: 3,
        name: 'Tablet',
        availableCount: 300,
        inUseCount: 0,
        studio: 'Studio Bangalore',
        project_equipment: [],
        audition_equipment: [],
        session_equipment: [
          {
            sessionId: 184,
            sessionUniqueId: 'SISSRNDK0184',
            count: 1,
          },
        ],
      },
      {
        equipmentCount: 320,
        studioId: 1,
        id: 1,
        name: 'Iphone',
        availableCount: 320,
        inUseCount: 0,
        studio: 'Studio Bangalore',
        project_equipment: [],
        audition_equipment: [],
        session_equipment: [],
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/side/studioEquipments/',
};
