export default {
  response: {
    count: 7,
    next: null,
    previous: null,
    result: [
      {
        createdOn: '2021-12-16T04:09:02',
        isActive: true,
        createdBy: 1,
        slugName: 'IAM',
        id: 6,
        name: 'Access Management',
        host: 'https://iam-qa.ptw.com/',
      },
      {
        createdOn: '2021-12-16T04:09:02',
        isActive: true,
        createdBy: 1,
        slugName: 'API',
        id: 7,
        name: 'API Management',
        host: 'https://gateway.ptw.com:1338/',
      },
      {
        createdOn: '2021-12-16T04:09:01',
        isActive: true,
        createdBy: 1,
        slugName: 'PRMS',
        id: 3,
        name: 'PRMS Access Management',
        host: 'https://prms-qa.ptw.com/',
      },
      {
        createdOn: '2021-12-16T04:09:01',
        isActive: true,
        createdBy: 1,
        slugName: 'CRM',
        id: 4,
        name: 'CRM Access Management',
        host: 'https://crm-qa.ptw.com/',
      },
      {
        createdOn: '2021-12-16T04:09:01',
        isActive: true,
        createdBy: 1,
        slugName: 'SIDE',
        id: 5,
        name: 'Side Audio Tool AM',
        host: 'https://side-qa.ptw.com/',
      },
      {
        createdOn: '2021-12-16T04:09:00',
        isActive: true,
        createdBy: 1,
        slugName: 'WFM',
        id: 1,
        name: 'WFM Access Management',
        host: 'https://wfm-qa01.ptw.com/',
      },
      {
        createdOn: '2021-12-16T04:09:00',
        isActive: true,
        createdBy: 1,
        slugName: 'HRMS',
        id: 2,
        name: 'HRMS Access Management',
        host: 'https://hrms-qa01.ptw.com/',
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/qa/iam/application/',
};
