export default {
  response: {
    count: 1,
    next: null,
    previous: null,
    result: [
      {
        firstName: 'test',
        lastName: 'Patel',
        emailId: null,
        contactNumber: '09179898628',
        uniqueId: 'TESPAT00001',
        viewCount: 19,
        nativeLanguages: {},
        nativeAccents: {},
        nativeSpotlight: null,
        billType: 'Tier2',
        playingAge: {},
        voiceTypes: {
          5: 'Animation',
        },
        gameTypes: {},
        unionLinked: false,
        unionDate: null,
        id: 8,
        gender: 'Male',
        age: null,
        status: 'Active',
        accents: {},
        studios: {
          1: 'SIDE',
          2: 'Studios VOA',
          3: 'Red Audio Fool Moon',
          4: 'TakeMaker',
          5: 'iKSample',
          6: 'Cinemata',
          7: 'WPP',
          8: 'Levsha',
          9: 'Arc TV',
          10: 'Café Ole',
          11: 'Jarpa',
          12: 'Lola MX',
          13: 'Character',
          14: 'Digital Azul',
          15: 'TV Group',
          16: 'Entalize',
          17: 'Musai',
          18: 'Monocon',
          19: 'Red Angel',
          20: 'SIDE Shanghai',
          21: 'NorDubb',
          22: 'Cineast',
          23: 'Deaf Cat Gulf',
          24: 'Deaf Cat Levant',
          25: 'Qumra House Levant',
          26: 'Meraki',
          27: 'Halo',
          28: 'Andovar',
          29: 'ATM',
          30: 'Melodika',
          31: 'Perfect Voices',
          32: 'Soundesign',
          33: 'Kable Group',
        },
        languages: {},
        filepath: null,
        filename: null,
        tags: {},
        image: null,
        talentDocs: [],
        talentAgents: [
          {
            agentId: 1,
            agentName: 'Farukh',
            agentStatus: 'Active',
            isPrimary: true,
            category: 'Agent',
            country: 'India',
            city: 'Kolkata',
            postCode: null,
            contacts: [
              {
                id: 1,
                name: 'Farukh',
                email: 'farukh.patel@ptw.com',
                phone: '78873872',
                primary: false,
              },
            ],
            lastPO: null,
          },
        ],
        availability: null,
        longlist: [3],
        shortlist: null,
        voiceclips: [],
        talentReviews: [],
        session_notes_talent: [],
        purchaseOrder: [],
        castingNotes: [
          {
            project: 'Stranger things',
            sideUser: null,
            character: 'hassssssssssssss xz mmmmmmmmmmmmmmmmmm mxzzzzzzz',
            date: '01 Nov 2022',
            notes: null,
            type: 'Audition',
          },
          {
            project: 'Stranger things',
            sideUser: null,
            character: 'hassssssssssssss xz mmmmmmmmmmmmmmmmmm mxzzzzzzz',
            date: '03 Nov 2022',
            notes: null,
            type: 'Audition',
          },
        ],
        talentProjects: [
          {
            projectId: 2,
            project: 'Stranger things',
          },
        ],
      },
    ],
    message: 'Record Found Successfully',
    id: null,
    statusCode: 200,
  },
  endPoint: 'https://gateway.ptw.com/dev/side/talent/:id/',
};
