export default {
  response: {
    result: [
      {
        createdOn: '2022-02-04',
        updatedOn: '2022-02-04T05:03:37',
        createdBy: 468,
        firstName: 'Sijo',
        lastName: null,
        emailId: 'sijo@xyz.com',
        mobileNumber: null,
        linkedInUrl: null,
        conversionNote: null,
        ownerId: 2840,
        countryId: null,
        cityId: null,
        convertedById: null,
        leadLocation: null,
        additionalInfo: null,
        isReview: false,
        isContact: false,
        isExclusion: false,
        id: 1764,
        designation: null,
        address1: null,
        address2: null,
        address3: null,
        pincode: null,
        comment: null,
        ownerName: 'Anirudh Chandran',
        name: 'Sijo',
        createdByName: 'Jaya Surya',
        convertedByName: null,
        city: null,
        country: null,
        gender: null,
        status: {
          id: 16,
          name: 'Lead',
        },
        crmSource: null,
        crmSourceGroup: null,
        hearAboutUs: null,
        clientType: null,
        crmCompany: {
          id: 1745,
          name: 'New Account 2',
          website: null,
          employeeCount: null,
          annualRevenue: null,
          country: {
            id: 7,
            name: 'United States of America',
            regionId: 2,
            region: 'North America',
          },
          city: {
            id: 19,
            name: 'Baltimore',
            stateId: 19,
            state: 'Baltimore',
          },
          address1: null,
          address2: null,
          address3: null,
          pincode: '0',
          financeId: null,
          currency: {
            id: 2,
            name: 'United States Dollar',
          },
          marketType: {
            id: 11,
            name: 'Games',
          },
          industry: {
            id: 4,
            name: 'Games',
          },
          owners: [
            {
              userId: 7,
              name: 'Govind menon',
              regions: [
                {
                  id: 3,
                  name: 'South America',
                },
                {
                  id: 5,
                  name: 'Europe',
                },
                {
                  id: 6,
                  name: 'APAC',
                },
                {
                  id: 7,
                  name: 'Asia',
                },
              ],
              departments: null,
            },
            {
              userId: 2840,
              name: 'Anirudh Chandran',
              regions: [
                {
                  id: 7,
                  name: 'Asia',
                },
                {
                  id: 6,
                  name: 'APAC',
                },
              ],
              departments: null,
            },
          ],
          clientType: {
            id: 451,
            name: 'Publishers',
          },
          isApproved: true,
        },
        campaigns: null,
        services: null,
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/crm/crmcontacts/441/?status=lead',
};
