export default {
  response: [
    {
      updatedOn: '2022-02-01T12:26:11',
      createdBy: 21,
      logDate: '2022-02-01',
      logTime: '12:26',
      notesCategoryId: 1,
      tableId: 404,
      isReview: false,
      isConstant: true,
      logMessage: 'Details Updated',
      timezoneId: null,
      endTime: null,
      recordType: 'LOG ACTIVITY',
      statusId: 320,
      id: 1456,
      comment: 'Gender has been updated as Male',
      name: null,
      createdByName: 'Jaya Surya',
      logType: null,
      notesCategory: {
        id: 1,
        name: 'CONTACT',
      },
      timezone: null,
      status: {
        id: 320,
        name: 'No Longer In Role',
      },
    },
  ],
  endPoint: 'https://gateway.ptw.com/dev/crm/logactivity/',
};

export const editData = {
  updatedOn: '2022-02-04T05:56:40',
  createdBy: 21,
  logDate: '2022-02-01',
  logTime: '11:26 AM',
  notesCategoryId: 1,
  tableId: 404,
  isReview: false,
  isConstant: false,
  logMessage: 'Activity created',
  timezoneId: null,
  endTime: null,
  recordType: 'LOG ACTIVITY',
  statusId: 320,
  id: 1568,
  comment: 'Got an email from client',
  name: null,
  createdByName: 'Jaya Surya',
  logType: '{id: 28, name: "Email"}',
  notesCategory: {id: 1, name: 'CONTACT'},
  timezone: null,
  status: {id: 320, name: 'No Longer In Role'},
  type: 'edit',
};
