export default {
  response: {
    count: 10,
    next: null,
    previous: null,
    result: [
      {
        milestoneId: null,
        currencyId: 142,
        clientCrmId: 469,
        clientName: 'Former Animation',
        clientId: 5,
        clientContact: 'rmaaa R',
        clientEmail: 'wfmramam@ptw.com',
        clientPo: null,
        projectId: 4,
        projectOppId: null,
        castingType: 'Side Directed Auditions No Clips',
        directingType: 'Client Directing',
        sideBookingTime: 'Side Booking',
        actorMinRate: null,
        actorMaxRate: null,
        actorBuyoutType: 'Buyout Not Included in Studio Fee',
        postRate: null,
        postDelivery: 'Batch Delivery',
        quoteDate: '2022-11-10',
        invoiceDate: null,
        sideJobNumber: 'abc123',
        createdUserId: 4,
        jobType: null,
        bonusDisplay: null,
        pmNotes: null,
        expectedHours: {
          totals: {
            noTimeConstraintTotal: 'Enter Rate',
            timeConstrainedTotal: 'Enter Rate',
            lipSyncTotal: 'Enter Rate',
          },
          wordCount: {
            noTimeConstraint: 0,
            timeConstrained: 0,
            lipSync: 0,
            total: 0,
          },
          linesCount: {
            noTimeConstraint: 0,
            timeConstrained: 0,
            lipSync: 0,
            total: 0,
          },
          recordRate: {
            expectedRecordRate: 'Expected Record Rate(Lines)',
            noTimeConstraint: 0,
            timeConstrained: 0,
            lipSync: 0,
          },
          keySequence: {
            noTimeConstraint: 1,
            timeConstrained: 2,
            lipSync: 3,
            total: 4,
          },
        },
        servicesDetails: [
          {
            sectionName: 'Pre-Production',
            sectionTotals: {
              runningTotal: 30,
              serviceSubTotal: 30,
              accountingSubTotal: 30,
              internalCostSubTotal: 30,
            },
            sectionDetails: [
              {
                units: 5,
                unitRate: 1,
                serviceType: 'day(s) casting (inc. clips)',
                serviceTotal: 5,
                accountingTotal: 5,
                internalCostTotal: 5,
                accountingCategory: 'Pre-Production',
                accountingUnitRate: 1,
                serviceDescription: 'day(s) casting (inc. clips)',
                internalCostUnitRate: 1,
              },
              {
                units: 10,
                unitRate: 1,
                serviceType: 'day(s) casting',
                serviceTotal: 10,
                accountingTotal: 10,
                internalCostTotal: 10,
                accountingCategory: 'Pre-Production',
                accountingUnitRate: 1,
                serviceDescription: 'day(s) casting',
                internalCostUnitRate: 1,
              },
              {
                units: 15,
                unitRate: 1,
                serviceType: 'day(s) casting (inc. clips)',
                serviceTotal: 15,
                accountingTotal: 15,
                internalCostTotal: 15,
                accountingCategory: 'Pre-Production',
                accountingUnitRate: 1,
                serviceDescription: 'day(s) casting (inc. clips)',
                internalCostUnitRate: 1,
              },
            ],
          },
          {
            sectionName: 'Studio Recording Session',
            sectionTotals: {
              runningTotal: 111,
              serviceSubTotal: 111,
              accountingSubTotal: 111,
              internalCostSubTotal: 111,
            },
            sectionDetails: [
              {
                units: 55,
                unitRate: 1,
                serviceType: 'hr(s) studio',
                serviceTotal: 55,
                accountingTotal: 55,
                internalCostTotal: 55,
                accountingCategory: 'Studio Recording Session',
                accountingUnitRate: 1,
                serviceDescription: 'hr(s) studio',
                internalCostUnitRate: 1,
              },
              {
                units: 56,
                unitRate: 1,
                serviceType: 'day(s) studio',
                serviceTotal: 56,
                accountingTotal: 56,
                internalCostTotal: 56,
                accountingCategory: 'Studio Recording Session',
                accountingUnitRate: 1,
                serviceDescription: 'day(s) studio',
                internalCostUnitRate: 1,
              },
            ],
          },
        ],
        quoteDetails: {
          estPmFee: 0,
          grandTotal: 141,
          quoteSubTotal: 141,
          accGrossProfit: 0,
          accCostSubTotal: 141,
          stdProductionFee: 0,
          combinedCostTotal: 282,
          internalCostSubTotal: 141,
          accGrossProfitPercent: 0,
          internalCostGrossProfit: -141,
          transferPricingDiscount: 0,
          internalCostGrossProfitPercent: -100,
          transferPricingDiscountPercent: 0,
        },
        primaryLanguageId: null,
        projectCategory: 'Games & Non Games',
        createdBy: 4,
        id: 10,
        type: 'Tier',
        category: 'Potential Project',
        name: 'F3',
        version: '1.0',
        status: 'To Do',
        project: 'HMT',
        languages: ['English Uk'],
        talents: null,
        characters: null,
        brief: 'ok ok',
        milestone: null,
        currency: {
          id: 142,
          name: 'Zambia Kwacha',
          symbol: 'ZK',
        },
        projectRel: 'HMT',
        createdUser: {
          user: 'Naveen Alle',
          emailId: 'naveenkumar.reddy@ptw.com',
        },
        locLanguages: [],
        studios: [],
      },
      {
        milestoneId: null,
        currencyId: 142,
        clientCrmId: 468,
        clientName: 'Focus media',
        clientId: 6,
        clientContact: 'NameAcc L',
        clientEmail: 'nameacc@az.co',
        clientPo: null,
        projectId: 3,
        projectOppId: null,
        castingType: 'Side Directed Auditions and Demos',
        directingType: 'Side Directing',
        sideBookingTime: 'Side Booking',
        actorMinRate: null,
        actorMaxRate: null,
        actorBuyoutType: null,
        postRate: null,
        postDelivery: 'Batch Delivery',
        quoteDate: '2022-11-09',
        invoiceDate: null,
        sideJobNumber: 'hhs78263',
        createdUserId: 4,
        jobType: 'Union',
        bonusDisplay: 'Condensed',
        pmNotes: null,
        expectedHours: {
          totals: {
            noTimeConstraintTotal: 0.5,
            timeConstrainedTotal: 0.5,
            lipSyncTotal: 1,
          },
          wordCount: {
            noTimeConstraint: 6,
            timeConstrained: 6,
            lipSync: 6,
            total: 18,
          },
          linesCount: {
            noTimeConstraint: 2,
            timeConstrained: 3,
            lipSync: 5,
            total: 10,
          },
          recordRate: {
            expectedRecordRate: 'Expected Record Rate(Lines)',
            noTimeConstraint: 8,
            timeConstrained: 7,
            lipSync: 5,
          },
          keySequence: {
            noTimeConstraint: 1,
            timeConstrained: 2,
            lipSync: 3,
            total: 4,
          },
        },
        servicesDetails: [],
        quoteDetails: {
          grandTotal: 0,
          quoteSubTotal: 0,
          accGrossProfit: 0,
          accCostSubTotal: 0,
          combinedCostTotal: 0,
          internalCostSubTotal: 0,
          accGrossProfitPercent: 0,
          internalCostGrossProfit: 0,
          transferPricingDiscount: 0,
          internalCostGrossProfitPercent: 0,
          transferPricingDiscountPercent: 0,
        },
        primaryLanguageId: null,
        projectCategory: 'Games & Non Games',
        createdBy: 4,
        id: 9,
        type: 'LA',
        category: 'Potential Project',
        name: 'quote v2',
        version: '1.0',
        status: 'To Do',
        project: 'project 12',
        languages: ['English Us'],
        talents: null,
        characters: null,
        brief: 'content',
        milestone: null,
        currency: {
          id: 142,
          name: 'Zambia Kwacha',
          symbol: 'ZK',
        },
        projectRel: 'project 12',
        createdUser: {
          user: 'Naveen Alle',
          emailId: 'naveenkumar.reddy@ptw.com',
        },
        locLanguages: [],
        studios: [],
      },
      {
        milestoneId: 4,
        currencyId: 142,
        clientCrmId: 471,
        clientName: 'HMT',
        clientId: 4,
        clientContact: 'Shubham G',
        clientEmail: 'shubham@gmail.com',
        clientPo: null,
        projectId: 2,
        projectOppId: null,
        castingType: 'Side Directed Auditions and Demos',
        directingType: 'Side Directing',
        sideBookingTime: 'Side Booking',
        actorMinRate: null,
        actorMaxRate: null,
        actorBuyoutType: null,
        postRate: null,
        postDelivery: 'Batch Delivery',
        quoteDate: '2022-10-21',
        invoiceDate: null,
        sideJobNumber: 'hsy7812',
        createdUserId: 120003107,
        jobType: 'Union',
        bonusDisplay: 'Condensed',
        pmNotes: null,
        expectedHours: {
          totals: {
            p21Total: 'Enter Rate',
            p2Total: 'Enter Rate',
            p3Total: 'Enter Rate',
          },
          wordCount: {
            p21: 0,
            p2: 0,
            p3: 0,
            total: 0,
          },
          linesCount: {
            p21: 0,
            p2: 0,
            p3: 0,
            total: 0,
          },
          recordRate: {
            expectedRecordRate: 'Expected Record Rate(Lines)',
            p21: 0,
            p2: 0,
            p3: 0,
            total: 0,
          },
          keySequence: {
            p21: 1,
            p2: 2,
            p3: 3,
            total: 4,
          },
        },
        servicesDetails: [],
        quoteDetails: {
          grandTotal: 0,
          quoteSubTotal: 0,
          accGrossProfit: 0,
          accCostSubTotal: 0,
          combinedCostTotal: 0,
          internalCostSubTotal: 0,
          accGrossProfitPercent: 0,
          internalCostGrossProfit: 0,
          transferPricingDiscount: 0,
          internalCostGrossProfitPercent: 0,
          transferPricingDiscountPercent: 0,
        },
        primaryLanguageId: null,
        projectCategory: 'Games & Non Games',
        createdBy: 120003107,
        id: 8,
        type: 'LA',
        category: 'Existing Project',
        name: 'quote la 2',
        version: '5.0',
        status: 'Converted',
        project: 'Stranger things',
        languages: [
          'Arabic',
          'Brazilian Portuguese',
          'Chinese',
          'Danish',
          'Dutch',
          'English',
          'English Uk',
          'English Us',
          'Eu Portuguese',
          'Filipino',
          'French',
          'French Canadian',
          'German',
          'Hebrew',
          'Hindi',
          'Hk Cantonese',
          'Indonesian',
          'Italian',
          'Japanese',
          'Jhxdjkf Skjdfk Kdjhfj Jh',
          'Korean',
          'Mandarin Chinese',
          'Mandarin Taiwan',
          'Mexican Spanish',
          'New',
          'Norwegian',
          'Polish',
          'Russian',
          'Spanish',
          'Standard Arebic',
          'Swedish',
          'Thai',
          'Turkish',
        ],
        talents: null,
        characters: null,
        brief: 'brief about project',
        milestone: 'Pro000003B',
        currency: {
          id: 142,
          name: 'Zambia Kwacha',
          symbol: 'ZK',
        },
        projectRel: 'Stranger things',
        createdUser: {
          user: 'Pavitra Hegde',
          emailId: 'pavitra.subramanyahegde@ptw.com',
        },
        locLanguages: [],
        studios: [],
      },
      {
        milestoneId: 5,
        currencyId: 142,
        clientCrmId: 471,
        clientName: 'HMT',
        clientId: 4,
        clientContact: 'Shubham G',
        clientEmail: 'shubham@gmail.com',
        clientPo: null,
        projectId: 2,
        projectOppId: null,
        castingType: 'Side Directed Auditions and Demos',
        directingType: 'Side Directing',
        sideBookingTime: 'Side Booking',
        actorMinRate: null,
        actorMaxRate: null,
        actorBuyoutType: null,
        postRate: null,
        postDelivery: 'Batch Delivery',
        quoteDate: '2022-10-21',
        invoiceDate: null,
        sideJobNumber: 'abc67276',
        createdUserId: 120003107,
        jobType: 'Union',
        bonusDisplay: 'Condensed',
        pmNotes: null,
        expectedHours: {},
        servicesDetails: [],
        quoteDetails: {
          grandTotal: 0,
          quoteSubTotal: 0,
          accGrossProfit: 0,
          accCostSubTotal: 0,
          combinedCostTotal: 0,
          internalCostSubTotal: 0,
          accGrossProfitPercent: 0,
          internalCostGrossProfit: 0,
          transferPricingDiscount: 0,
          internalCostGrossProfitPercent: 0,
          transferPricingDiscountPercent: 0,
        },
        primaryLanguageId: null,
        projectCategory: 'Games & Non Games',
        createdBy: 120003107,
        id: 7,
        type: 'LA',
        category: 'Existing Project',
        name: 'quote la',
        version: '4.0',
        status: 'Converted',
        project: 'Stranger things',
        languages: ['English Us'],
        talents: null,
        characters: null,
        brief: 'project details',
        milestone: 'Pro00002D',
        currency: {
          id: 142,
          name: 'Zambia Kwacha',
          symbol: 'ZK',
        },
        projectRel: 'Stranger things',
        createdUser: {
          user: 'Pavitra Hegde',
          emailId: 'pavitra.subramanyahegde@ptw.com',
        },
        locLanguages: [],
        studios: [],
      },
      {
        milestoneId: 6,
        currencyId: 142,
        clientCrmId: 471,
        clientName: 'HMT',
        clientId: 4,
        clientContact: 'Shubham G',
        clientEmail: 'shubham@gmail.com',
        clientPo: null,
        projectId: 2,
        projectOppId: null,
        castingType: 'Side Directed Auditions No Clips',
        directingType: 'Client Directing',
        sideBookingTime: 'Side Booking',
        actorMinRate: null,
        actorMaxRate: null,
        actorBuyoutType: 'Buyout Not Included in Studio Fee',
        postRate: null,
        postDelivery: 'Batch Delivery',
        quoteDate: '2022-10-21',
        invoiceDate: null,
        sideJobNumber: '1234',
        createdUserId: 120003107,
        jobType: null,
        bonusDisplay: null,
        pmNotes: null,
        expectedHours: {
          totals: {
            p1Total: 'Enter Rate',
            p2Total: 'Enter Rate',
            p3Total: 'Enter Rate',
          },
          wordCount: {
            p1: 0,
            p2: 0,
            p3: 0,
            total: 0,
          },
          linesCount: {
            p1: 0,
            p2: 0,
            p3: 0,
            total: 0,
          },
          recordRate: {
            expectedRecordRate: 'Expected Record Rate(Lines)',
            p1: 0,
            p2: 0,
            p3: 0,
            total: 0,
          },
          keySequence: {
            p1: 1,
            p2: 2,
            p3: 3,
            total: 4,
          },
        },
        servicesDetails: [],
        quoteDetails: {
          grandTotal: 0,
          quoteSubTotal: 0,
          accGrossProfit: 0,
          accCostSubTotal: 0,
          combinedCostTotal: 0,
          internalCostSubTotal: 0,
          accGrossProfitPercent: 0,
          internalCostGrossProfit: 0,
          transferPricingDiscount: 0,
          internalCostGrossProfitPercent: 0,
          transferPricingDiscountPercent: 0,
        },
        primaryLanguageId: null,
        projectCategory: 'Games & Non Games',
        createdBy: 120003107,
        id: 6,
        type: 'Tier',
        category: 'Existing Project',
        name: 'quote v tier',
        version: '3.0',
        status: 'Converted',
        project: 'Stranger things',
        languages: ['English Uk'],
        talents: null,
        characters: null,
        brief: 'project',
        milestone: 'Pro00002E',
        currency: {
          id: 142,
          name: 'Zambia Kwacha',
          symbol: 'ZK',
        },
        projectRel: 'Stranger things',
        createdUser: {
          user: 'Pavitra Hegde',
          emailId: 'pavitra.subramanyahegde@ptw.com',
        },
        locLanguages: [],
        studios: [],
      },
      {
        milestoneId: 7,
        currencyId: 142,
        clientCrmId: 469,
        clientName: 'Former Animation',
        clientId: 5,
        clientContact: 'rmaaa R',
        clientEmail: 'wfmramam@ptw.com',
        clientPo: null,
        projectId: 1,
        projectOppId: null,
        castingType: 'Side Directed Auditions and Demos',
        directingType: 'Side Directing',
        sideBookingTime: 'Side Booking',
        actorMinRate: null,
        actorMaxRate: null,
        actorBuyoutType: null,
        postRate: 780,
        postDelivery: 'Batch Delivery',
        quoteDate: '2022-10-18',
        invoiceDate: null,
        sideJobNumber: '123ss',
        createdUserId: 120003107,
        jobType: 'Union',
        bonusDisplay: 'Condensed',
        pmNotes: null,
        expectedHours: {},
        servicesDetails: [
          {
            sectionName: 'Talent Costs',
            sectionTotals: {
              adminFee: 4881.29,
              subTotal: 0,
              corpSumFUI: 0,
              corpSumSUI: 0,
              corpSumUphc: 4075.63,
              indivSumFUI: 53.05,
              indivSumSUI: 365.47,
              indivSumUphc: 972.61,
              runningTotal: 38284.61,
              bonusTotalSum: 2024,
              corpSumTaxFee: 0,
              extSigFeeTotal: 0,
              indivSumTaxFee: 869.46,
              adminFeePercent: 12.5,
              corpSumMedicare: 0,
              serviceSubTotal: 43931.59,
              corpSumBaseTotal: 24700.8,
              indivSumMedicare: 85.47,
              indivSumBaseTotal: 5894.63,
              accountingSubTotal: 39050.32,
              payRollHandlingFee: 765.69,
              corpSumWorkerCompFee: 1430.18,
              internalCostSubTotal: 0,
              indivSumWorkerCompFee: 341.3,
              payRollHandlingFeePer: 2,
              corpSumSocialSecurityTax: 0,
              runningTotalClientPaying: 0,
              indivSumSocialSecurityTax: 365.47,
              runningTotalClientPayingSum: 38284.61,
            },
            sectionDetails: [
              {
                FUI: 53.05,
                SUI: 365.47,
                uphc: 972.61,
                units: 5,
                agency: 'Agency(10%)',
                feeRate: 'Scale',
                inQuote: 'yes',
                bonusEnd: 5,
                medicare: 85.47,
                unitRate: 956.75,
                baseTotal: 5894.63,
                extSigFee: 0,
                taxStatus: 'Individual',
                bonusStart: 3,
                bonusTotal: 575,
                talentName: 6,
                serviceType: 'Talent Bonus Payments',
                serviceTotal: 8078,
                talentFeeOnly: 5358.75,
                workerCompFee: 341.3,
                accountingTotal: 8239.57,
                agentFeePercent: 10,
                agencyFeeSession: 535.88,
                internalCostTotal: 0,
                socialSecurityTax: 365.47,
                accountingCategory: 'Talent Costs',
                accountingUnitRate: '',
                serviceDescription: 'Talent Bonus Payments',
                internalCostUnitRate: '',
              },
              {
                FUI: 0,
                SUI: 0,
                uphc: 4075.63,
                units: 10,
                agency: 'Agency(20%)',
                feeRate: '2*Scale',
                inQuote: 'yes',
                bonusEnd: 9,
                medicare: 0,
                unitRate: 1913.5,
                baseTotal: 24700.8,
                extSigFee: 0,
                taxStatus: 'Corporation',
                bonusStart: 4,
                bonusTotal: 1449,
                talentName: 6,
                serviceType: 'Talent Bonus Payments',
                serviceTotal: 30206.61,
                talentFeeOnly: 20584,
                workerCompFee: 1430.18,
                accountingTotal: 30810.75,
                agentFeePercent: 20,
                agencyFeeSession: 4116.8,
                internalCostTotal: 0,
                socialSecurityTax: 0,
                accountingCategory: 'Talent Costs',
                accountingUnitRate: '',
                serviceDescription: 'Talent Bonus Payments',
                internalCostUnitRate: '',
              },
            ],
            clientPayingFees: 'No',
          },
        ],
        quoteDetails: {
          grandTotal: 43931.59,
          quoteSubTotal: 43931.59,
          accGrossProfit: 4881.27,
          accCostSubTotal: 39050.32,
          stdProductionFee: 0,
          combinedCostTotal: 39050.32,
          internalCostSubTotal: 0,
          accGrossProfitPercent: 11.11,
          internalCostGrossProfit: 4881.27,
          transferPricingDiscount: 0,
          internalCostGrossProfitPercent: 11.11,
          transferPricingDiscountPercent: 0,
        },
        primaryLanguageId: null,
        projectCategory: 'Games & Non Games',
        createdBy: 120003107,
        id: 5,
        type: 'LA',
        category: 'Existing Project',
        name: 'Quote v5',
        version: '5.0',
        status: 'Converted',
        project:
          'TheBloodDrhhghj asdad asdad ajsdhakdkad kjasdhkajdkassd kjasdhkadkashdkd',
        languages: ['English Us'],
        talents: null,
        characters: null,
        brief: 'details about your project',
        milestone: 'Pro00001B',
        currency: {
          id: 142,
          name: 'Zambia Kwacha',
          symbol: 'ZK',
        },
        projectRel: 'TheBloodDrhhghj asdad asdad ajsdhakdkad kjasdhkadkashdkd',
        createdUser: {
          user: 'Pavitra Hegde',
          emailId: 'pavitra.subramanyahegde@ptw.com',
        },
        locLanguages: [],
        studios: [],
      },
      {
        milestoneId: null,
        currencyId: 142,
        clientCrmId: 469,
        clientName: 'Former Animation',
        clientId: 5,
        clientContact: 'rmaaa R',
        clientEmail: 'wfmramam@ptw.com',
        clientPo: null,
        projectId: 1,
        projectOppId: null,
        castingType: 'Side Directed Auditions No Clips',
        directingType: 'Side Directing',
        sideBookingTime: 'Side Booking',
        actorMinRate: 5,
        actorMaxRate: 8,
        actorBuyoutType: 'Buyout Not Included in Studio Fee',
        postRate: 670,
        postDelivery: 'Batch Delivery',
        quoteDate: '2022-10-18',
        invoiceDate: null,
        sideJobNumber: '13shh6',
        createdUserId: 120003107,
        jobType: null,
        bonusDisplay: null,
        pmNotes: null,
        expectedHours: {
          totals: {
            noTimeConstraintTotal: 79508079365095,
            timeConstrainedTotal: 69569569444458,
            lipSyncTotal: 79508079365095,
          },
          wordCount: {
            noTimeConstraint: 3,
            timeConstrained: 6,
            lipSync: 8,
            total: 17,
          },
          linesCount: {
            noTimeConstraint: 556556555555664,
            timeConstrained: 556556555555664,
            lipSync: 556556555555664,
            total: 1669669666666992,
          },
          recordRate: {
            expectedRecordRate: 'Expected Record Rate(Lines)',
            noTimeConstraint: 7,
            timeConstrained: 8,
            lipSync: 7,
            total: 22,
          },
          keySequence: {
            total: 4,
            lipSync: 3,
            timeConstrained: 2,
            noTimeConstraint: 1,
          },
        },
        servicesDetails: [
          {
            sectionName: 'Expenses',
            sectionTotals: {
              serviceSubTotal: 11,
              accountingSubTotal: 11,
              internalCostSubTotal: 11,
            },
            sectionDetails: [
              {
                units: 5,
                unitRate: 1,
                serviceType: 'other talent expenses',
                serviceTotal: 5,
                accountingTotal: 5,
                internalCostTotal: 5,
                accountingCategory: 'Expenses',
                accountingUnitRate: 1,
                serviceDescription: 'other talent expenses',
                internalCostUnitRate: 1,
              },
              {
                units: 6,
                unitRate: 1,
                serviceType: 'other non-talent expenses',
                serviceTotal: 6,
                accountingTotal: 6,
                internalCostTotal: 6,
                accountingCategory: 'Expenses',
                accountingUnitRate: 1,
                serviceDescription: 'other non-talent expenses',
                internalCostUnitRate: 1,
              },
            ],
          },
          {
            sectionName: 'On Location',
            sectionTotals: {
              serviceSubTotal: 12,
              accountingSubTotal: 12,
              internalCostSubTotal: 12,
            },
            sectionDetails: [
              {
                units: 6,
                unitRate: 1,
                serviceType: 'day(s) performance director shoot',
                serviceTotal: 6,
                accountingTotal: 6,
                internalCostTotal: 6,
                accountingCategory: 'On Location',
                accountingUnitRate: 1,
                serviceDescription: 'day(s) performance director shoot',
                internalCostUnitRate: 1,
              },
              {
                units: 6,
                unitRate: 1,
                serviceType: 'audio rig delivery/collection costs',
                serviceTotal: 6,
                accountingTotal: 6,
                internalCostTotal: 6,
                accountingCategory: 'On Location',
                accountingUnitRate: 1,
                serviceDescription: 'audio rig delivery/collection costs',
                internalCostUnitRate: 1,
              },
            ],
          },
          {
            sectionName: 'Post-Production',
            sectionTotals: {
              serviceSubTotal: 13,
              accountingSubTotal: 13,
              internalCostSubTotal: 13,
            },
            sectionDetails: [
              {
                units: 6,
                unitRate: 1,
                serviceType: 'day(s) export, upload',
                serviceTotal: 6,
                accountingTotal: 6,
                internalCostTotal: 6,
                accountingCategory: 'Post-Production',
                accountingUnitRate: 1,
                serviceDescription: 'day(s) export, upload',
                internalCostUnitRate: 1,
              },
              {
                units: 7,
                unitRate: 1,
                serviceType: 'day(s) export, upload',
                serviceTotal: 7,
                accountingTotal: 7,
                internalCostTotal: 7,
                accountingCategory: 'Post-Production',
                accountingUnitRate: 1,
                serviceDescription: 'day(s) export, upload',
                internalCostUnitRate: 1,
              },
            ],
          },
        ],
        quoteDetails: {
          grandTotal: 38.41,
          quoteSubTotal: 36,
          accGrossProfit: 2.41,
          accCostSubTotal: 36,
          stdProductionFee: 3.6,
          combinedCostTotal: 72,
          estimatedProdCost: 0,
          internalCostSubTotal: 36,
          accGrossProfitPercent: 6.27,
          internalCostGrossProfit: -33.59,
          stdProductionFeePercent: 10,
          transferPricingDiscount: 1.19,
          estDaysProdInternalCosts: null,
          internalCostGrossProfitPercent: -87.45,
          transferPricingDiscountPercent: 3,
        },
        primaryLanguageId: null,
        projectCategory: 'Games & Non Games',
        createdBy: 120003107,
        id: 4,
        type: 'Classic',
        category: 'Existing Project',
        name: 'Quote v4',
        version: '4.0',
        status: 'Approved',
        project:
          'TheBloodDrhhghj asdad asdad jsdhakdkad kjasdhkajdkassd kjasdhkadkashdkd',
        languages: ['English Us'],
        talents: 5,
        characters: 8,
        brief: 'details',
        milestone: null,
        currency: {
          id: 142,
          name: 'Zambia Kwacha',
          symbol: 'ZK',
        },
        projectRel:
          'TheBloodDrhhghj asdad ajsdhakdkad kjasdhkajdkassd kjasdhkadkashdkd',
        createdUser: {
          user: 'Pavitra Hegde',
          emailId: 'pavitra.subramanyahegde@ptw.com',
        },
        locLanguages: [],
        studios: [],
      },
      {
        milestoneId: null,
        currencyId: 142,
        clientCrmId: 471,
        clientName: 'HMT',
        clientId: 4,
        clientContact: 'Shubham G',
        clientEmail: 'shubham@gmail.com',
        clientPo: null,
        projectId: 1,
        projectOppId: null,
        castingType: 'Side Directed Auditions No Clips',
        directingType: 'Client Directing',
        sideBookingTime: 'Side Booking',
        actorMinRate: 1,
        actorMaxRate: 2,
        actorBuyoutType: 'Buyout Not Included in Studio Fee',
        postRate: 549,
        postDelivery: 'Batch Delivery',
        quoteDate: '2022-10-18',
        invoiceDate: null,
        sideJobNumber: 'tyes66552',
        createdUserId: 120003107,
        jobType: null,
        bonusDisplay: null,
        pmNotes: null,
        expectedHours: {
          totals: {
            noTimeConstraintTotal: 'Enter Rate',
            timeConstrainedTotal: 'Enter Rate',
            lipSyncTotal: 'Enter Rate',
          },
          wordCount: {
            noTimeConstraint: 0,
            timeConstrained: 0,
            lipSync: 0,
            total: 0,
          },
          linesCount: {
            noTimeConstraint: 0,
            timeConstrained: 0,
            lipSync: 0,
            total: 0,
          },
          recordRate: {
            expectedRecordRate: 'Expected Record Rate(Lines)',
            noTimeConstraint: 0,
            timeConstrained: 0,
            lipSync: 0,
            total: 0,
          },
          keySequence: {
            noTimeConstraint: 1,
            timeConstrained: 2,
            lipSync: 3,
            total: 4,
          },
        },
        servicesDetails: [
          {
            sectionName: 'Expenses',
            sectionTotals: {
              runningTotal: 5,
              serviceSubTotal: 5,
              accountingSubTotal: 5,
              internalCostSubTotal: 5,
            },
            sectionDetails: [
              {
                units: 5,
                unitRate: 1,
                serviceType: 'other talent expenses',
                serviceTotal: 5,
                accountingTotal: 5,
                internalCostTotal: 5,
                accountingCategory: 'Expenses',
                accountingUnitRate: 1,
                serviceDescription: 'other talent expenses',
                internalCostUnitRate: 1,
              },
            ],
          },
          {
            sectionName: 'On Location',
            sectionTotals: {
              runningTotal: 5,
              serviceSubTotal: 5,
              accountingSubTotal: 5,
              internalCostSubTotal: 5,
            },
            sectionDetails: [
              {
                units: 5,
                unitRate: 1,
                serviceType: 'day(s) performance director shoot',
                serviceTotal: 5,
                accountingTotal: 5,
                internalCostTotal: 5,
                accountingCategory: 'On Location',
                accountingUnitRate: 1,
                serviceDescription: 'day(s) performance director shoot',
                internalCostUnitRate: 1,
              },
            ],
          },
        ],
        quoteDetails: {
          estPmFee: 0,
          grandTotal: 9.7,
          quoteSubTotal: 10,
          accGrossProfit: -0.3,
          accCostSubTotal: 10,
          stdProductionFee: 0,
          combinedCostTotal: 20,
          internalCostSubTotal: 10,
          accGrossProfitPercent: 0,
          internalCostGrossProfit: -10.3,
          transferPricingDiscount: 0.3,
          internalCostGrossProfitPercent: -106.19,
          transferPricingDiscountPercent: 3,
        },
        primaryLanguageId: null,
        projectCategory: 'Games & Non Games',
        createdBy: 120003107,
        id: 3,
        type: 'Tier',
        category: 'Existing Project',
        name: 'Quote v3',
        version: '3.0',
        status: 'Approved',
        project:
          'TheBloodDrhhghj asdad asdad ajsdhakdkad kjasdhkajdkassd kjasdhkadkashdkd',
        languages: ['English Uk'],
        talents: 12,
        characters: 34,
        brief: 'details about',
        milestone: null,
        currency: {
          id: 142,
          name: 'Zambia Kwacha',
          symbol: 'ZK',
        },
        projectRel:
          'TheBloodDrhhghj asdad asdad kjasdhkajdkassd kjasdhkadkashdkd',
        createdUser: {
          user: 'Pavitra Hegde',
          emailId: 'pavitra.subramanyahegde@ptw.com',
        },
        locLanguages: [],
        studios: [],
      },
      {
        milestoneId: 2,
        currencyId: 142,
        clientCrmId: 471,
        clientName: 'HMT',
        clientId: 4,
        clientContact: 'Shubham G',
        clientEmail: 'shubham@gmail.com',
        clientPo: null,
        projectId: 2,
        projectOppId: null,
        castingType: 'Side Directed Auditions and Clips',
        directingType: 'Client Directing',
        sideBookingTime: 'Client Determined',
        actorMinRate: null,
        actorMaxRate: null,
        actorBuyoutType: 'Buyout Included in Studio Fee',
        postRate: null,
        postDelivery: 'Rolling Delivery',
        quoteDate: '2022-10-17',
        invoiceDate: null,
        sideJobNumber: 'bdgdg33',
        createdUserId: 120003107,
        jobType: null,
        bonusDisplay: null,
        pmNotes: null,
        expectedHours: {
          totals: {
            lipSyncTotal: 'Enter Rate',
            timeConstrainedTotal: 'Enter Rate',
            noTimeConstraintTotal: 'Enter Rate',
          },
          wordCount: {
            total: 0,
            lipSync: 0,
            timeConstrained: 0,
            noTimeConstraint: 0,
          },
          linesCount: {
            total: 0,
            lipSync: 0,
            timeConstrained: 0,
            noTimeConstraint: 0,
          },
          recordRate: {
            total: 0,
            lipSync: 0,
            timeConstrained: 0,
            noTimeConstraint: 0,
            expectedRecordRate: 'Expected Record Rate(Lines)',
          },
          keySequence: {
            total: 4,
            lipSync: 3,
            timeConstrained: 2,
            noTimeConstraint: 1,
          },
        },
        servicesDetails: [],
        quoteDetails: {
          grandTotal: 0,
          quoteSubTotal: 0,
          accGrossProfit: 0,
          accCostSubTotal: 0,
          combinedCostTotal: 0,
          internalCostSubTotal: 0,
          accGrossProfitPercent: 0,
          internalCostGrossProfit: 0,
          transferPricingDiscount: 0,
          internalCostGrossProfitPercent: 0,
          transferPricingDiscountPercent: 0,
        },
        primaryLanguageId: 2,
        projectCategory: 'Games & Non Games',
        createdBy: 120003107,
        id: 2,
        type: 'LOC',
        category: 'Existing Project',
        name: 'quote v2English Us',
        version: '2.0',
        status: 'Converted',
        project: 'Stranger things',
        languages: ['English Us'],
        talents: null,
        characters: null,
        brief: 'this is a brief',
        milestone: 'Pro00001B',
        currency: {
          id: 142,
          name: 'Zambia Kwacha',
          symbol: 'ZK',
        },
        projectRel: 'Stranger things',
        createdUser: {
          user: 'Pavitra Hegde',
          emailId: 'pavitra.subramanyahegde@ptw.com',
        },
        locLanguages: [
          {
            id: 2,
            name: 'English Us',
          },
        ],
        studios: [
          {
            id: 18,
            name: 'Monocon',
          },
          {
            id: 14,
            name: 'Digital Azul',
          },
          {
            id: 19,
            name: 'Red Angel',
          },
          {
            id: 20,
            name: 'SIDE Shanghai',
          },
          {
            id: 21,
            name: 'NorDubb',
          },
          {
            id: 22,
            name: 'Cineast',
          },
          {
            id: 23,
            name: 'Deaf Cat Gulf',
          },
          {
            id: 24,
            name: 'Deaf Cat Levant',
          },
          {
            id: 25,
            name: 'Qumra House Levant',
          },
          {
            id: 26,
            name: 'Meraki',
          },
          {
            id: 27,
            name: 'Halo',
          },
          {
            id: 28,
            name: 'Andovar',
          },
          {
            id: 29,
            name: 'ATM',
          },
          {
            id: 30,
            name: 'Melodika',
          },
          {
            id: 31,
            name: 'Perfect Voices',
          },
          {
            id: 32,
            name: 'Soundesign',
          },
          {
            id: 33,
            name: 'Kable Group',
          },
          {
            id: 16,
            name: 'Entalize',
          },
          {
            id: 1,
            name: 'SIDE',
          },
          {
            id: 2,
            name: 'Studios VOA',
          },
          {
            id: 3,
            name: 'Red Audio Fool Moon',
          },
          {
            id: 4,
            name: 'TakeMaker',
          },
          {
            id: 5,
            name: 'iKSample',
          },
          {
            id: 6,
            name: 'Cinemata',
          },
          {
            id: 7,
            name: 'WPP',
          },
          {
            id: 8,
            name: 'Levsha',
          },
          {
            id: 9,
            name: 'Arc TV',
          },
          {
            id: 10,
            name: 'Café Ole',
          },
          {
            id: 11,
            name: 'Jarpa',
          },
          {
            id: 12,
            name: 'Lola MX',
          },
          {
            id: 13,
            name: 'Character',
          },
          {
            id: 15,
            name: 'TV Group',
          },
          {
            id: 17,
            name: 'Musai',
          },
        ],
      },
      {
        milestoneId: 1,
        currencyId: 142,
        clientCrmId: 445,
        clientName: 'Tata Power',
        clientId: 1,
        clientContact: 'Employee hower',
        clientEmail: 'ledEmployee@az.co',
        clientPo: null,
        projectId: 1,
        projectOppId: null,
        castingType: 'Side Directed Auditions No Clips',
        directingType: 'Client Directing',
        sideBookingTime: 'Side Booking',
        actorMinRate: null,
        actorMaxRate: null,
        actorBuyoutType: 'Buyout Not Included in Studio Fee',
        postRate: null,
        postDelivery: 'Batch Delivery',
        quoteDate: '2022-10-14',
        invoiceDate: null,
        sideJobNumber: null,
        createdUserId: 120003108,
        jobType: null,
        bonusDisplay: null,
        pmNotes: null,
        expectedHours: {
          totals: {
            noTimeConstraintTotal: 0.5,
            timeConstrainedTotal: 1,
            lipSyncTotal: 1,
          },
          wordCount: {
            noTimeConstraint: 5,
            timeConstrained: 4,
            lipSync: 3,
            total: 12,
          },
          linesCount: {
            noTimeConstraint: 1,
            timeConstrained: 2,
            lipSync: 3,
            total: 6,
          },
          recordRate: {
            expectedRecordRate: 'Expected Record Rate(Lines)',
            noTimeConstraint: 4,
            timeConstrained: 2,
            lipSync: 3,
            total: 9,
          },
          keySequence: {
            noTimeConstraint: 1,
            timeConstrained: 2,
            lipSync: 3,
            total: 4,
          },
        },
        servicesDetails: [
          {
            sectionName: 'Expenses',
            sectionTotals: {
              runningTotal: 4,
              serviceSubTotal: 4,
              accountingSubTotal: 4,
              internalCostSubTotal: 4,
            },
            sectionDetails: [
              {
                units: 4,
                unitRate: 1,
                serviceType: 'other talent expenses',
                serviceTotal: 4,
                accountingTotal: 4,
                internalCostTotal: 4,
                accountingCategory: 'Expenses',
                accountingUnitRate: 1,
                serviceDescription: 'other talent expenses',
                internalCostUnitRate: 1,
              },
            ],
          },
          {
            sectionName: 'On Location',
            sectionTotals: {
              runningTotal: 5,
              serviceSubTotal: 5,
              accountingSubTotal: 5,
              internalCostSubTotal: 5,
            },
            sectionDetails: [
              {
                units: 5,
                unitRate: 1,
                serviceType: 'audio rig delivery/collection costs',
                serviceTotal: 5,
                accountingTotal: 5,
                internalCostTotal: 5,
                accountingCategory: 'On Location',
                accountingUnitRate: 1,
                serviceDescription: 'audio rig delivery/collection costs',
                internalCostUnitRate: 1,
              },
            ],
          },
          {
            sectionName: 'Post-Production',
            sectionTotals: {
              runningTotal: 14,
              serviceSubTotal: 14,
              accountingSubTotal: 14,
              internalCostSubTotal: 14,
            },
            sectionDetails: [
              {
                units: 7,
                unitRate: 1,
                serviceType: 'day(s) export, upload',
                serviceTotal: 7,
                accountingTotal: 7,
                internalCostTotal: 7,
                accountingCategory: 'Post-Production',
                accountingUnitRate: 1,
                serviceDescription: 'day(s) export, upload',
                internalCostUnitRate: 1,
              },
              {
                units: 7,
                unitRate: 1,
                serviceType:
                  'day(s) shoot dialogue clean up, de noise, edit, label',
                serviceTotal: 7,
                accountingTotal: 7,
                internalCostTotal: 7,
                accountingCategory: 'Post-Production',
                accountingUnitRate: 1,
                serviceDescription:
                  'day(s) shoot dialogue clean up, de noise, edit, label',
                internalCostUnitRate: 1,
              },
            ],
          },
        ],
        quoteDetails: {
          estPmFee: 0,
          grandTotal: 23,
          quoteSubTotal: 23,
          accGrossProfit: 0,
          accCostSubTotal: 23,
          stdProductionFee: 0,
          combinedCostTotal: 46,
          internalCostSubTotal: 23,
          accGrossProfitPercent: 0,
          internalCostGrossProfit: -23,
          transferPricingDiscount: 0,
          internalCostGrossProfitPercent: -100,
          transferPricingDiscountPercent: 0,
        },
        primaryLanguageId: null,
        projectCategory: 'Games & Non Games',
        createdBy: 120003108,
        id: 1,
        type: 'Tier',
        category: 'Potential Project',
        name: 'new quote stranger',
        version: '1.0',
        status: 'Converted',
        project:
          'TheBloodDrhhghj asdad asdad ajsdhakdkad kjasdhkajdkassd kjasdhkadkashdkd',
        languages: ['English Uk'],
        talents: null,
        characters: null,
        brief: 'about your project',
        milestone: 'Pro00001A',
        currency: {
          id: 142,
          name: 'Zambia Kwacha',
          symbol: 'ZK',
        },
        projectRel: 'TheBloodDrhhghj asdad asdad ajsdhakdkad kjasdhkajdkassd',
        createdUser: {
          user: 'Sreeja Vijayakumar',
          emailId: 'sreeja.vijayakumar@ptw.com',
        },
        locLanguages: [],
        studios: [],
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/side/quotes/',
};
