export default {
  response: {
    count: 1,
    next: null,
    previous: null,
    result: [
      {
        uniqueId: 'PRO00003',
        sideUsers: {
          1: 'admin admin',
          4: 'Naveen Alle',
          23: 'manikanta kamepalli',
          120003104: 'Vinodh gk',
          120003107: 'Pavitra Hegde',
          120003108: 'Sreeja Vijayakumar',
          120003111: 'Atul Bhat',
          120003112: 'Sushma Savanth',
          120003114: 'Kiran V',
          120003242: 'Govind Menon',
        },
        lobId: 277,
        clientCrmId: 471,
        clientName: 'HMT',
        clientId: 1,
        primaryDirectorId: null,
        primaryEngineerId: null,
        projectManagerId: 120003104,
        projectCategories: {},
        dateStarted: '2022-03-30',
        dateCompleted: null,
        projectDetails: null,
        isPotential: false,
        id: 3,
        name: 'Cyclone test',
        status: 'Active',
        lob: 'Voice & Audio',
        studios: {
          1: 'Studio Bangalore',
          2: 'Jarpa',
          3: 'Lola MX',
          4: 'Cafe Ole',
          5: 'WPP',
        },
        languages: ['English Uk'],
        milestones: 1,
        favourite: false,
        primaryDirector: null,
        primaryEngineer: null,
        projectManager: 'Vinodh gk',
        projectDocs: [],
        equipments: [
          {
            id: 4,
            projectEquipmentId: 5,
            name: 'Cables',
            count: 10,
          },
        ],
        fav_projects: [2, 7],
        projectMilestones: [
          {
            id: 8,
            name: 'Acsxbhndc',
            adminStatus: 'Billed',
            projectStatus: 'Active',
            uniqueId: 'UK0008',
            studios: {
              1: 'Studio Bangalore',
              2: 'Jarpa',
              3: 'Lola MX',
              4: 'Cafe Ole',
              5: 'WPP',
              6: 'check for test',
            },
          },
          {
            id: 2,
            name: 'Milestone 1',
            adminStatus: 'Active',
            projectStatus: 'Active',
            uniqueId: 'UK0002',
            studios: {
              1: 'Studio Bangalore',
              2: 'Jarpa',
              3: 'Lola MX',
              4: 'Cafe Ole',
              5: 'WPP',
            },
          },
        ],
        projectToDoList: [
          {
            id: 27,
            postedTime: '04:52 PM',
            taskDate: '2022-05-06',
            task: 'a',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 0,
          },
          {
            id: 23,
            postedTime: '04:26 PM',
            taskDate: '2022-05-06',
            task: 'tst',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 0,
          },
          {
            id: 17,
            postedTime: '12:12 PM',
            taskDate: '2022-05-02',
            task: 'Testing',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 0,
          },
          {
            id: 11,
            postedTime: '12:20 PM',
            taskDate: '2022-04-25',
            task: 'test',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 0,
          },
          {
            id: 5,
            postedTime: '07:35 PM',
            taskDate: '2022-04-13',
            task: 'gdsjskkaksjghjkdlxkjha',
            sideUserId: 120003112,
            user: 'Sushma Savanth',
            priority: null,
            status: 0,
          },
          {
            id: 4,
            postedTime: '05:01 PM',
            taskDate: '2022-04-05',
            task: 'test',
            sideUserId: 120003108,
            user: 'Sreeja Vijayakumar',
            priority: 'Low',
            status: 0,
          },
          {
            id: 16,
            postedTime: '03:44 PM',
            taskDate: '2022-04-28',
            task: 'sdfhjgk ksadjfhghjkh kdsfjhg',
            sideUserId: 120003108,
            user: 'Sreeja Vijayakumar',
            priority: null,
            status: 1,
          },
          {
            id: 10,
            postedTime: '06:09 PM',
            taskDate: '2022-04-26',
            task: 'sdasd fasdf asdf',
            sideUserId: 120003243,
            user: 'Jaya Surya',
            priority: 'Medium',
            status: 1,
          },
          {
            id: 3,
            postedTime: '05:01 PM',
            taskDate: '2022-04-05',
            task: 'test',
            sideUserId: 120003112,
            user: 'Sushma Savanth',
            priority: 'High',
            status: 1,
          },
          {
            id: 2,
            postedTime: '05:00 PM',
            taskDate: '2022-04-05',
            task: 'test',
            sideUserId: 120003242,
            user: 'Govind Menon',
            priority: 'Low',
            status: 1,
          },
        ],
        projectNotes: [
          13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
          30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
          47, 48, 49,
        ],
        projects: [2],
        quotes: [
          {
            id: 18,
            version: '6.0',
            quoteDate: '2022-04-27',
            status: 'To Do',
            type: 'Classic',
            name: 'classic wui4',
            category: 'Existing Project',
            milestoneId: null,
            milestone: null,
            amount: 0,
          },
          {
            id: 17,
            version: '5.0',
            quoteDate: '2022-04-27',
            status: 'To Do',
            type: 'Classic',
            name: 'classic wui',
            category: 'Existing Project',
            milestoneId: null,
            milestone: null,
            amount: 0,
          },
          {
            id: 16,
            version: '4.0',
            quoteDate: '2022-04-27',
            status: 'To Do',
            type: 'LA',
            name: 'LAQuote1',
            category: 'Existing Project',
            milestoneId: null,
            milestone: null,
            amount: 0,
          },
          {
            id: 15,
            version: '3.0',
            quoteDate: '2022-04-27',
            status: 'To Do',
            type: 'Tier',
            name: 'laQuote',
            category: 'Existing Project',
            milestoneId: null,
            milestone: null,
            amount: 16.88,
          },
          {
            id: 7,
            version: '2.0',
            quoteDate: '2022-03-30',
            status: 'Archived',
            type: 'Tier',
            name: 'Tier quote 8.0',
            category: 'Potential Project',
            milestoneId: 2,
            milestone: 'Milestone 1',
            amount: 0,
          },
          {
            id: 3,
            version: '1.0',
            quoteDate: '2022-03-30',
            status: 'To Do',
            type: 'Tier',
            name: 'Tier quote 3.0',
            category: 'Potential Project',
            milestoneId: null,
            milestone: null,
            amount: 0,
          },
          {
            id: 10,
            version: '1.0',
            quoteDate: '2022-04-07',
            status: 'Converted',
            type: 'LOC',
            name: 'wip',
            category: 'Potential Project',
            milestoneId: 2,
            milestone: 'Milestone 1',
            amount: 944788562363.13,
          },
        ],
      },
    ],
    message: 'Record Found Successfully',
    id: null,
    statusCode: 200,
  },
  endPoint: 'https://gateway.ptw.com/dev/side/project/',
};
