export default {
  response: {
    count: 5,
    next: null,
    previous: null,
    result: [
      {
        uniqueId: 'PRO00014',
        sideUsers: {
          1: 'admin admin',
          4: 'Naveen Alle',
          23: 'manikanta kamepalli',
          120003104: 'Vinodh gk',
          120003107: 'Pavitra Hegde',
          120003108: 'Sreeja Vijayakumar',
          120003111: 'Atul Bhat',
          120003112: 'Sushma Savanth',
          120003114: 'Kiran V',
          120003242: 'Govind Menon',
        },
        lobId: 277,
        clientCrmId: 471,
        clientName: 'HMT',
        clientId: 1,
        primaryDirectorId: null,
        primaryEngineerId: null,
        projectManagerId: null,
        projectCategories: {},
        dateStarted: '2022-03-30',
        dateCompleted: null,
        projectDetails: 'QA',
        isPotential: false,
        id: 14,
        name: 'Cyclone1',
        status: 'Active',
        lob: 'Voice & Audio',
        studios: {
          1: 'Studio Bangalore',
        },
        languages: ['English Uk'],
        milestones: 1,
        favourite: false,
        primaryDirector: null,
        primaryEngineer: null,
        projectManager: null,
        projectDocs: [],
        equipments: [],
        fav_projects: [13],
        projectMilestones: [
          {
            id: 10,
            name: 'Milestone1',
            adminStatus: 'Active',
            projectStatus: 'Active',
            uniqueId: 'UK0010',
            studios: {
              1: 'Studio Bangalore',
            },
          },
        ],
        projectToDoList: [
          {
            id: 42,
            postedTime: '08:18 AM',
            taskDate: '2022-05-21',
            task: 'add task',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 0,
          },
          {
            id: 41,
            postedTime: '04:22 PM',
            taskDate: '2022-05-11',
            task: 'from dashboard',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 0,
          },
          {
            id: 40,
            postedTime: '12:01 PM',
            taskDate: '2022-05-11',
            task: 'from project',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: 'Low',
            status: 0,
          },
          {
            id: 37,
            postedTime: '11:46 AM',
            taskDate: '2022-05-11',
            task: 'ok',
            sideUserId: 120003242,
            user: 'Govind Menon',
            priority: 'Low',
            status: 0,
          },
          {
            id: 35,
            postedTime: '11:41 AM',
            taskDate: '2022-05-11',
            task: 'testing update',
            sideUserId: 120003242,
            user: 'Govind Menon',
            priority: 'Low',
            status: 0,
          },
        ],
        projectNotes: [],
        projects: [],
        quotes: [
          {
            id: 2,
            version: '1.0',
            quoteDate: '2022-03-30',
            status: 'Converted',
            type: 'Tier',
            name: 'Tier quote 2.0',
            category: 'Potential Project',
            milestoneId: 10,
            milestone: 'Milestone1',
            amount: 0,
          },
        ],
      },
      {
        uniqueId: 'PRO00013',
        sideUsers: {
          1: 'admin admin',
          4: 'Naveen Alle',
          23: 'manikanta kamepalli',
          120003104: 'Vinodh gk',
          120003107: 'Pavitra Hegde',
          120003108: 'Sreeja Vijayakumar',
          120003111: 'Atul Bhat',
          120003112: 'Sushma Savanth',
          120003114: 'Kiran V',
          120003242: 'Govind Menon',
          120003243: 'Jaya Surya',
        },
        lobId: 277,
        clientCrmId: 471,
        clientName: 'HMT',
        clientId: 1,
        primaryDirectorId: null,
        primaryEngineerId: null,
        projectManagerId: null,
        projectCategories: {},
        dateStarted: '2022-05-04',
        dateCompleted: null,
        projectDetails: 'QA',
        isPotential: false,
        id: 13,
        name: 'Dynamic Project1',
        status: 'Active',
        lob: 'Voice & Audio',
        studios: {
          1: 'Studio Bangalore',
          2: 'Jarpa',
          3: 'Lola MX',
          4: 'Cafe Ole',
          5: 'WPP',
          6: 'check for test ',
        },
        languages: ['English Us', 'English Uk', 'Mexican Spanish'],
        milestones: 1,
        favourite: false,
        primaryDirector: null,
        primaryEngineer: null,
        projectManager: null,
        projectDocs: [],
        equipments: [],
        fav_projects: [],
        projectMilestones: [
          {
            id: 9,
            name: 'Milestone01',
            adminStatus: 'Active',
            projectStatus: 'Active',
            uniqueId: 'UK0009',
            studios: {
              1: 'Studio Bangalore',
              2: 'Jarpa',
              3: 'Lola MX',
              4: 'Cafe Ole',
              5: 'WPP',
              6: 'check for test ',
            },
          },
        ],
        projectToDoList: [
          {
            id: 43,
            postedTime: '03:44 PM',
            taskDate: '2022-05-21',
            task: 'to do',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 0,
          },
          {
            id: 38,
            postedTime: '11:57 AM',
            taskDate: '2022-05-11',
            task: 'new one',
            sideUserId: 120003242,
            user: 'Govind Menon',
            priority: 'Low',
            status: 0,
          },
          {
            id: 36,
            postedTime: '11:44 AM',
            taskDate: '2022-05-11',
            task: 'task from dashboard',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: 'Low',
            status: 0,
          },
          {
            id: 28,
            postedTime: '04:20 PM',
            taskDate: '2022-05-10',
            task: 'test test',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 0,
          },
          {
            id: 26,
            postedTime: '04:47 PM',
            taskDate: '2022-05-07',
            task: 'e',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 0,
          },
        ],
        projectNotes: [],
        projects: [],
        quotes: [
          {
            id: 19,
            version: '1.0',
            quoteDate: '2022-05-04',
            status: 'Converted',
            type: 'Tier',
            name: 'DP01',
            category: 'Potential Project',
            milestoneId: 9,
            milestone: 'Milestone01',
            amount: 133.75,
          },
        ],
      },
      {
        uniqueId: 'PRO00009',
        sideUsers: {
          1: 'admin admin',
          4: 'Naveen Alle',
          23: 'manikanta kamepalli',
          120003104: 'Vinodh gk',
          120003107: 'Pavitra Hegde',
          120003108: 'Sreeja Vijayakumar',
          120003111: 'Atul Bhat',
          120003112: 'Sushma Savanth',
          120003114: 'Kiran V',
          120003242: 'Govind Menon',
        },
        lobId: 277,
        clientCrmId: 468,
        clientName: 'Focus media',
        clientId: 12,
        primaryDirectorId: null,
        primaryEngineerId: null,
        projectManagerId: 120003104,
        projectCategories: {},
        dateStarted: '2022-04-07',
        dateCompleted: null,
        projectDetails: null,
        isPotential: false,
        id: 9,
        name: 'informat89',
        status: 'Active',
        lob: 'Voice & Audio',
        studios: {
          1: 'Studio Bangalore',
          2: 'Jarpa',
          3: 'Lola MX',
          4: 'Cafe Ole',
          5: 'WPP',
        },
        languages: ['English Us', 'English Uk'],
        milestones: 1,
        favourite: false,
        primaryDirector: null,
        primaryEngineer: null,
        projectManager: 'Vinodh gk',
        projectDocs: [],
        equipments: [],
        fav_projects: [1, 11, 12],
        projectMilestones: [
          {
            id: 6,
            name: 'Milestone 1',
            adminStatus: 'Active',
            projectStatus: 'Active',
            uniqueId: 'UK0006',
            studios: {
              1: 'Studio Bangalore',
              2: 'Jarpa',
              3: 'Lola MX',
              4: 'Cafe Ole',
              5: 'WPP',
            },
          },
        ],
        projectToDoList: [
          {
            id: 21,
            postedTime: '04:18 PM',
            taskDate: '2022-05-06',
            task: 'testt',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 0,
          },
          {
            id: 19,
            postedTime: '04:10 PM',
            taskDate: '2022-05-02',
            task: 'test',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 0,
          },
          {
            id: 18,
            postedTime: '12:12 PM',
            taskDate: '2022-05-02',
            task: 'Test',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 0,
          },
          {
            id: 7,
            postedTime: '06:06 PM',
            taskDate: '2022-04-08',
            task: 'test',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 0,
          },
          {
            id: 15,
            postedTime: '04:05 PM',
            taskDate: '2022-04-27',
            task: 'testing Meet',
            sideUserId: 120003112,
            user: 'Sushma Savanth',
            priority: 'High',
            status: 1,
          },
          {
            id: 14,
            postedTime: '04:05 PM',
            taskDate: '2022-04-27',
            task: 'Development Meeting',
            sideUserId: 120003108,
            user: 'Sreeja Vijayakumar',
            priority: null,
            status: 1,
          },
          {
            id: 9,
            postedTime: '10:11 AM',
            taskDate: '2022-04-14',
            task: 'Testing',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 1,
          },
        ],
        projectNotes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        projects: [1],
        quotes: [
          {
            id: 11,
            version: '1.0',
            quoteDate: '2022-04-07',
            status: 'Converted',
            type: 'LOC',
            name: 'Quote89',
            category: 'Potential Project',
            milestoneId: 6,
            milestone: 'Milestone 1',
            amount: 7947069952572,
          },
        ],
      },
      {
        uniqueId: 'PRO00003',
        sideUsers: {
          1: 'admin admin',
          4: 'Naveen Alle',
          23: 'manikanta kamepalli',
          120003104: 'Vinodh gk',
          120003107: 'Pavitra Hegde',
          120003108: 'Sreeja Vijayakumar',
          120003111: 'Atul Bhat',
          120003112: 'Sushma Savanth',
          120003114: 'Kiran V',
          120003242: 'Govind Menon',
        },
        lobId: 277,
        clientCrmId: 471,
        clientName: 'HMT',
        clientId: 1,
        primaryDirectorId: null,
        primaryEngineerId: null,
        projectManagerId: 120003104,
        projectCategories: {},
        dateStarted: '2022-03-30',
        dateCompleted: null,
        projectDetails: null,
        isPotential: false,
        id: 3,
        name: 'Cyclone test',
        status: 'Active',
        lob: 'Voice & Audio',
        studios: {
          1: 'Studio Bangalore',
          2: 'Jarpa',
          3: 'Lola MX',
          4: 'Cafe Ole',
          5: 'WPP',
        },
        languages: ['English Uk'],
        milestones: 1,
        favourite: false,
        primaryDirector: null,
        primaryEngineer: null,
        projectManager: 'Vinodh gk',
        projectDocs: [],
        equipments: [
          {
            id: 4,
            projectEquipmentId: 5,
            name: 'Cables',
            count: 10,
          },
        ],
        fav_projects: [2, 7, 14],
        projectMilestones: [
          {
            id: 8,
            name: 'Acsxbhndc',
            adminStatus: 'Billed',
            projectStatus: 'Active',
            uniqueId: 'UK0008',
            studios: {
              1: 'Studio Bangalore',
              2: 'Jarpa',
              3: 'Lola MX',
              4: 'Cafe Ole',
              5: 'WPP',
              6: 'check for test ',
            },
          },
          {
            id: 2,
            name: 'Milestone 1',
            adminStatus: 'Active',
            projectStatus: 'Active',
            uniqueId: 'UK0002',
            studios: {
              1: 'Studio Bangalore',
              2: 'Jarpa',
              3: 'Lola MX',
              4: 'Cafe Ole',
              5: 'WPP',
            },
          },
        ],
        projectToDoList: [
          {
            id: 27,
            postedTime: '04:52 PM',
            taskDate: '2022-05-06',
            task: 'a',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 0,
          },
          {
            id: 23,
            postedTime: '04:26 PM',
            taskDate: '2022-05-06',
            task: 'tst',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 0,
          },
          {
            id: 17,
            postedTime: '12:12 PM',
            taskDate: '2022-05-02',
            task: 'Testing',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 0,
          },
          {
            id: 11,
            postedTime: '12:20 PM',
            taskDate: '2022-04-25',
            task: 'test',
            sideUserId: 120003107,
            user: 'Pavitra Hegde',
            priority: null,
            status: 0,
          },
          {
            id: 5,
            postedTime: '07:35 PM',
            taskDate: '2022-04-13',
            task: 'gdsjskkaksjghjkdlxkjha',
            sideUserId: 120003112,
            user: 'Sushma Savanth',
            priority: null,
            status: 0,
          },
          {
            id: 4,
            postedTime: '05:01 PM',
            taskDate: '2022-04-05',
            task: 'test',
            sideUserId: 120003108,
            user: 'Sreeja Vijayakumar',
            priority: 'Low',
            status: 0,
          },
          {
            id: 16,
            postedTime: '03:44 PM',
            taskDate: '2022-04-28',
            task: 'sdfhjgk ksadjfhghjkh kdsfjhg',
            sideUserId: 120003108,
            user: 'Sreeja Vijayakumar',
            priority: null,
            status: 1,
          },
          {
            id: 10,
            postedTime: '06:09 PM',
            taskDate: '2022-04-26',
            task: 'sdasd fasdf asdf',
            sideUserId: 120003243,
            user: 'Jaya Surya',
            priority: 'Medium',
            status: 1,
          },
          {
            id: 3,
            postedTime: '05:01 PM',
            taskDate: '2022-04-05',
            task: 'test',
            sideUserId: 120003112,
            user: 'Sushma Savanth',
            priority: 'High',
            status: 1,
          },
          {
            id: 2,
            postedTime: '05:00 PM',
            taskDate: '2022-04-05',
            task: 'test',
            sideUserId: 120003242,
            user: 'Govind Menon',
            priority: 'Low',
            status: 1,
          },
        ],
        projectNotes: [
          13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
          30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
          47, 48, 49,
        ],
        projects: [2],
        quotes: [
          {
            id: 18,
            version: '6.0',
            quoteDate: '2022-04-27',
            status: 'To Do',
            type: 'Classic',
            name: 'classic wui4',
            category: 'Existing Project',
            milestoneId: null,
            milestone: null,
            amount: 0,
          },
          {
            id: 17,
            version: '5.0',
            quoteDate: '2022-04-27',
            status: 'To Do',
            type: 'Classic',
            name: 'classic wui',
            category: 'Existing Project',
            milestoneId: null,
            milestone: null,
            amount: 0,
          },
          {
            id: 16,
            version: '4.0',
            quoteDate: '2022-04-27',
            status: 'To Do',
            type: 'LA',
            name: 'LAQuote1',
            category: 'Existing Project',
            milestoneId: null,
            milestone: null,
            amount: 0,
          },
          {
            id: 15,
            version: '3.0',
            quoteDate: '2022-04-27',
            status: 'To Do',
            type: 'Tier',
            name: 'laQuote',
            category: 'Existing Project',
            milestoneId: null,
            milestone: null,
            amount: 16.88,
          },
          {
            id: 7,
            version: '2.0',
            quoteDate: '2022-03-30',
            status: 'Archived',
            type: 'Tier',
            name: 'Tier quote 8.0',
            category: 'Potential Project',
            milestoneId: 2,
            milestone: 'Milestone 1',
            amount: 0,
          },
          {
            id: 3,
            version: '1.0',
            quoteDate: '2022-03-30',
            status: 'To Do',
            type: 'Tier',
            name: 'Tier quote 3.0',
            category: 'Potential Project',
            milestoneId: null,
            milestone: null,
            amount: 0,
          },
          {
            id: 10,
            version: '1.0',
            quoteDate: '2022-04-07',
            status: 'Converted',
            type: 'LOC',
            name: 'wip',
            category: 'Potential Project',
            milestoneId: 2,
            milestone: 'Milestone 1',
            amount: 944788562363.13,
          },
        ],
      },
      {
        uniqueId: 'PRO00001',
        sideUsers: {
          1: 'admin admin',
          4: 'Naveen Alle',
          23: 'manikanta kamepalli',
          120003104: 'Vinodh gk',
          120003107: 'Pavitra Hegde',
          120003108: 'Sreeja Vijayakumar',
          120003111: 'Atul Bhat',
          120003112: 'Sushma Savanth',
          120003114: 'Kiran V',
          120003242: 'Govind Menon',
        },
        lobId: 277,
        clientCrmId: 471,
        clientName: 'HMT',
        clientId: 1,
        primaryDirectorId: 120003112,
        primaryEngineerId: null,
        projectManagerId: 120003104,
        projectCategories: {},
        dateStarted: '2022-03-30',
        dateCompleted: null,
        projectDetails: 'test',
        isPotential: false,
        id: 1,
        name: 'Cyclone',
        status: 'Active',
        lob: 'Voice & Audio',
        studios: {
          1: 'Studio Bangalore',
        },
        languages: ['English Uk'],
        milestones: 1,
        favourite: false,
        primaryDirector: 'Sushma Savanth',
        primaryEngineer: null,
        projectManager: 'Vinodh gk',
        projectDocs: [],
        equipments: [
          {
            id: 6,
            projectEquipmentId: 3,
            name: 'Mouse',
            count: 4,
          },
          {
            id: 4,
            projectEquipmentId: 2,
            name: 'Cables',
            count: 3,
          },
        ],
        fav_projects: [8],
        projectMilestones: [
          {
            id: 7,
            name: 'Milestone 3',
            adminStatus: 'Active',
            projectStatus: 'Active',
            uniqueId: 'UK0007',
            studios: {
              1: 'Studio Bangalore',
            },
          },
          {
            id: 5,
            name: 'Milestone 3',
            adminStatus: 'WIP',
            projectStatus: 'Active',
            uniqueId: 'UK0005',
            studios: {
              1: 'Studio Bangalore',
              2: 'Jarpa',
              3: 'Lola MX',
              4: 'Cafe Ole',
              5: 'WPP',
            },
          },
          {
            id: 4,
            name: 'Milestone 4',
            adminStatus: 'Billed',
            projectStatus: 'Active',
            uniqueId: 'UK0004',
            studios: {
              1: 'Studio Bangalore',
              2: 'Jarpa',
              3: 'Lola MX',
              4: 'Cafe Ole',
              5: 'WPP',
            },
          },
          {
            id: 3,
            name: 'Milestone 2',
            adminStatus: 'Active',
            projectStatus: 'Active',
            uniqueId: 'UK0003',
            studios: {
              1: 'Studio Bangalore',
              2: 'Jarpa',
              3: 'Lola MX',
              4: 'Cafe Ole',
              5: 'WPP',
            },
          },
          {
            id: 1,
            name: 'Milestone 1',
            adminStatus: 'Active',
            projectStatus: 'Active',
            uniqueId: 'UK0001',
            studios: {
              1: 'Studio Bangalore',
            },
          },
        ],
        projectToDoList: [
          {
            id: 20,
            postedTime: '06:25 PM',
            taskDate: '2022-05-02',
            task: 'hello test',
            sideUserId: 120003108,
            user: 'Sreeja Vijayakumar',
            priority: null,
            status: 0,
          },
          {
            id: 12,
            postedTime: '01:38 PM',
            taskDate: '2022-04-27',
            task: 'dfasdfasdf',
            sideUserId: 120003243,
            user: 'Jaya Surya',
            priority: null,
            status: 0,
          },
          {
            id: 1,
            postedTime: '04:21 PM',
            taskDate: '2022-04-05',
            task: 'test',
            sideUserId: 120003242,
            user: 'Govind Menon',
            priority: 'High',
            status: 0,
          },
          {
            id: 13,
            postedTime: '01:38 PM',
            taskDate: '2022-04-25',
            task: 'asdf asdfasdf',
            sideUserId: 120003243,
            user: 'Jaya Surya',
            priority: null,
            status: 1,
          },
        ],
        projectNotes: [],
        projects: [3],
        quotes: [
          {
            id: 13,
            version: '3.0',
            quoteDate: '2022-04-21',
            status: 'To Do',
            type: 'Tier',
            name: 'quoteExistingProject',
            category: 'Existing Project',
            milestoneId: null,
            milestone: null,
            amount: 0,
          },
          {
            id: 8,
            version: '2.0',
            quoteDate: '2022-04-05',
            status: 'To Do',
            type: 'LOC',
            name: 'quote 2',
            category: 'Existing Project',
            milestoneId: null,
            milestone: null,
            amount: 275337555051.38,
          },
          {
            id: 1,
            version: '1.0',
            quoteDate: '2022-03-30',
            status: 'Converted',
            type: 'Tier',
            name: 'Tier quote 1.0',
            category: 'Potential Project',
            milestoneId: 1,
            milestone: 'Milestone 1',
            amount: 0,
          },
          {
            id: 5,
            version: '1.0',
            quoteDate: '2022-03-30',
            status: 'Converted',
            type: 'Tier',
            name: 'Tier quote 5.0',
            category: 'Potential Project',
            milestoneId: 7,
            milestone: 'Milestone 3',
            amount: 0,
          },
        ],
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/side/project/',
};
