export default {
  response: {
    count: 2,
    next: null,
    previous: null,
    result: [
      {
        taskDate: '2022-05-02',
        addTask: 'Test',
        assignTo: 120003107,
        projectId: 9,
        id: 18,
        priority: null,
        status: 0,
        assignedToUser: 'Pavitra Hegde',
        postedTime: '12:12 PM',
        project: 'informat89',
      },
      {
        taskDate: '2022-05-02',
        addTask: 'Testing',
        assignTo: 120003107,
        projectId: 3,
        id: 17,
        priority: null,
        status: 0,
        assignedToUser: 'Pavitra Hegde',
        postedTime: '12:12 PM',
        project: 'Cyclone test',
      },
      {
        taskDate: '2022-09-12',
        addTask: 'you need to work on that test',
        assignTo: 120003243,
        projectId: 34,
        id: 114,
        priority: 'Low',
        status: 1,
        assignedToUser: 'Pavitra Hegde',
        postedTime: '11:57 AM',
        project: 'Stranger Things',
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/side/projectTask/',
};
