export default {
  response: {
    count: 41,
    next: 'https://side-pydev.ptw.com/quoteSetup/?limit=15&offset=15',
    previous: null,
    result: [
      {
        createdOn: '2022-09-27T13:21:29',
        isActive: true,
        quoteType: 'LA',
        variableType: 'Client Paying Talent+Agent',
        variableName: 'No',
        createdBy: 4,
        id: 42,
        content: 'test Client Paying Talent + Agent',
        created_by_relation: null,
      },
      {
        createdOn: '2022-09-27T13:20:15',
        isActive: true,
        quoteType: 'LA',
        variableType: 'LA - Tax',
        variableName: 'Individual',
        createdBy: 4,
        id: 41,
        content: 'testing LA - Tax',
        created_by_relation: null,
      },
      {
        createdOn: '2022-09-08T05:14:02',
        isActive: true,
        quoteType: 'Classic',
        variableType: 'Casting',
        variableName: 'Side Directed Auditions No Clips',
        createdBy: 120003107,
        id: 40,
        content:
          '"Side has an independent casting department allowing us to select the best talent for your project from across all the leading voice and acting agencies. We study your character briefs, carry out searches, liaise with agents, and then:',
        created_by_relation: null,
      },
      {
        createdOn: '2022-09-08T04:49:00',
        isActive: true,
        quoteType: 'Classic',
        variableType: 'Record Rate',
        variableName: 'Expected Record Rate(Lines)',
        createdBy: 120003107,
        id: 39,
        content:
          "Apart from counting words and characters, our online editor can help you to improve word choice and writing style, and, optionally, help you to detect grammar mistakes and plagiarism. To check word count, simply place your cursor into the text box above and start typing. You'll see the number of characters and words increase or decrease as you type, delete, and edit them. You can also copy and paste text from another program over into the online editor above. The Auto-Save feature will make sure you won't lose any changes while editing, even if you leave the site and come back later. Tip: Bookmark this page now.Apart from counting words and characters, our online editor can help you to improve word choice and writing style, and, optionally, help you to detect grammar mistakes and plagiarism. To check word count,k this page now. Apart from counting words and characters, our online editor can help you to improve word choice and writing style, an hi ng style, an hi ng style, an hing style",
        created_by_relation: null,
      },
      {
        createdOn: '2022-09-08T04:23:50',
        isActive: true,
        quoteType: 'Classic',
        variableType: 'Record Rate',
        variableName: 'Expected Record Rate(Words)',
        createdBy: 120003107,
        id: 38,
        content:
          "Apart from counting words and characters, our online editor can help you to improve word choice and writing style, and, optionally, help you to detect grammar mistakes and plagiarism. To check word count, simply place your cursor into the text box above and start typing. You'll see the number of characters and words increase or decrease as you type, delete, and edit them. You can also copy and paste text from another program over into the online editor above. The Auto-Save feature will make sure you won't lose any changes while editing, even if you leave the site and come back later. Tip: Bookmark this page now.Apart from counting words and characters, our online editor can help you to improve word choice and writing style, and, optionally, help you to detect grammar mistakes and plagiarism. To check word count,k this page now. Apart from counting words and characters, our online editor can help you to improve word choice and writing style, an hi ng style, an hi ng style, an hing style",
        created_by_relation: null,
      },
      {
        createdOn: '2022-09-08T04:23:36',
        isActive: true,
        quoteType: 'Tier',
        variableType: 'Record Rate',
        variableName: 'Expected Record Rate(Lines)',
        createdBy: 120003107,
        id: 37,
        content:
          "Apart from counting words and characters, our online editor can help you to improve word choice and writing style, and, optionally, help you to detect grammar mistakes and plagiarism. To check word count, simply place your cursor into the text box above and start typing. You'll see the number of characters and words increase or decrease as you type, delete, and edit them. You can also copy and paste text from another program over into the online editor above. The Auto-Save feature will make sure you won't lose any changes while editing, even if you leave the site and come back later. Tip: Bookmark this page now.Apart from counting words and characters, our online editor can help you to improve word choice and writing style, and, optionally, help you to detect grammar mistakes and plagiarism. To check word count,k this page now. Apart from counting words and characters, our online editor can help you to improve word choice and writing style, an hi ng style, an hi ng style, an hing style",
        created_by_relation: null,
      },
      {
        createdOn: '2022-09-07T10:59:20',
        isActive: true,
        quoteType: 'LA',
        variableType: 'Post',
        variableName: 'Batch Delivery',
        createdBy: 4,
        id: 36,
        content: 'test',
        created_by_relation: null,
      },
      {
        createdOn: '2022-09-02T06:34:20',
        isActive: true,
        quoteType: 'LOC',
        variableType: 'Casting',
        variableName: 'Client Directed auditions No Clips',
        createdBy: 120003107,
        id: 35,
        content: 'no clips',
        created_by_relation: null,
      },
      {
        createdOn: '2022-08-30T08:23:40',
        isActive: true,
        quoteType: 'LOC',
        variableType: 'Recent Project',
        variableName: '3',
        createdBy: 120003107,
        id: 34,
        content: 'recent project third',
        created_by_relation: null,
      },
      {
        createdOn: '2022-08-30T08:23:03',
        isActive: true,
        quoteType: 'LOC',
        variableType: 'Recent Project',
        variableName: '1',
        createdBy: 120003107,
        id: 33,
        content: 'recent project first',
        created_by_relation: null,
      },
      {
        createdOn: '2022-08-30T07:13:01',
        isActive: true,
        quoteType: 'LOC',
        variableType: 'Record Rate',
        variableName: 'Expected Record Rate(Words)',
        createdBy: 120003107,
        id: 32,
        content: 'updated word',
        created_by_relation: null,
      },
      {
        createdOn: '2022-08-30T06:49:21',
        isActive: true,
        quoteType: 'LOC',
        variableType: 'Record Rate',
        variableName: 'Expected Record Rate(Lines)',
        createdBy: 120003107,
        id: 31,
        content: 'updated lines',
        created_by_relation: null,
      },
      {
        createdOn: '2022-08-29T11:01:49',
        isActive: true,
        quoteType: 'LOC',
        variableType: 'Buyout',
        variableName: 'Buyout Included in Studio Fee',
        createdBy: 120003107,
        id: 30,
        content:'content',
        created_by_relation: null,
      },
      {
        createdOn: '2022-08-25T06:40:24',
        isActive: true,
        quoteType: 'LOC',
        variableType: 'Directing',
        variableName: 'Client Directing',
        createdBy: 120003107,
        id: 29,
        content: 'comment for client directing for LOC',
        created_by_relation: null,
      },
      {
        createdOn: '2022-08-25T06:39:37',
        isActive: true,
        quoteType: 'LOC',
        variableType: 'Directing',
        variableName: 'No Director',
        createdBy: 120003107,
        id: 28,
        content: 'not director comment for LOC',
        created_by_relation: null,
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/side/quoteSetup/',
};
