export default {
  response: {
    count: 3,
    next: null,
    previous: null,
    result: [
      {
        milestoneId: 2,
        talentShortlistId: 11,
        billingDuration: 1,
        id: 6,
        status: null,
        buyout: 'No',
        talentId: 37,
        talent: 'Farukh Patel',
        talentStatus: 'Active',
        characterId: 2,
        character: 'Hubert Blaine Wolfeschlegelsteinhausenber',
        supplierId: null,
        supplier: null,
        poId: null,
        documents: [],
      },
      {
        milestoneId: 2,
        talentShortlistId: 10,
        billingDuration: 0,
        id: 5,
        status: null,
        buyout: 'No',
        talentId: 38,
        talent: 'Testing sbdf',
        talentStatus: 'Active',
        characterId: 2,
        character: 'Hubert Blaine Wolfeschlegelsteinhausenber',
        supplierId: null,
        supplier: null,
        poId: null,
        documents: [],
      },
      {
        milestoneId: 2,
        talentShortlistId: 6,
        billingDuration: 0,
        id: 3,
        status: null,
        buyout: 'No',
        talentId: 2,
        talent: 'Naveen Kumar',
        talentStatus: 'Active',
        characterId: 2,
        character: 'Hubert Blaine Wolfeschlegelsteinhausenber',
        supplierId: null,
        supplier: null,
        poId: null,
        documents: [],
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/side/castList/',
};
