export default {
  response: {
    count: 28,
    result: [
      {
        id: 67,
        name: 'Naveen Alle',
        billType: 'Tier1',
        status: 'Active',
      },
      {
        id: 66,
        name: 'kij jjk',
        billType: 'Tier1',
        status: 'Active',
      },
      {
        id: 64,
        name: 'new one',
        billType: 'Tier1',
        status: 'Active',
      },
      {
        id: 63,
        name: 'Neew Test',
        billType: 'Tier1',
        status: 'Active',
      },
      {
        id: 62,
        name: 'New TT',
        billType: 'Tier1',
        status: 'Active',
      },
      {
        id: 61,
        name: 'farukh patel',
        billType: 'Tier1',
        status: 'Active',
      },
      {
        id: 60,
        name: 'farukh patel',
        billType: 'Tier1',
        status: 'Active',
      },
      {
        id: 59,
        name: 'Pavan Ku',
        billType: 'Custom Tier',
        status: 'Active',
      },
      {
        id: 58,
        name: 'Honda Start',
        billType: 'Tier2',
        status: 'Active',
      },
      {
        id: 56,
        name: 'Ramu Rao',
        billType: 'Tier1',
        status: 'Active',
      },
      {
        id: 55,
        name: 'Krack style',
        billType: 'Tier3',
        status: 'Active',
      },
      {
        id: 54,
        name: 'jaggu kk',
        billType: 'Tier3',
        status: 'Active',
      },
      {
        id: 53,
        name: 'Rocky Rock',
        billType: 'Tier1',
        status: 'Active',
      },
      {
        id: 52,
        name: 'test test',
        billType: 'Tier2',
        status: 'Active',
      },
      {
        id: 51,
        name: 'test test',
        billType: 'Tier2',
        status: 'Active',
      },
      {
        id: 50,
        name: 'test test',
        billType: 'Tier2',
        status: 'Active',
      },
      {
        id: 49,
        name: 'Test test',
        billType: 'Tier2',
        status: 'Active',
      },
      {
        id: 48,
        name: 'test test',
        billType: 'Tier1',
        status: 'Active',
      },
      {
        id: 42,
        name: 'check test',
        billType: 'Tier1',
        status: 'Active',
      },
      {
        id: 38,
        name: 'Testing sbdf',
        billType: 'Tier2',
        status: 'Active',
      },
      {
        id: 37,
        name: 'Farukh Patel',
        billType: 'Tier1',
        status: 'Active',
      },
      {
        id: 33,
        name: 'rekha sen',
        billType: 'Tier2',
        status: 'Active',
      },
      {
        id: 31,
        name: 'Mac star',
        billType: 'Tier3',
        status: 'Active',
      },
      {
        id: 30,
        name: 'jhjha ghajaaaeg shjhsjsjgsgsgsggsghsgs sjhjjhhjhjj rickahjjjhjhajhjhajh gagaghghhga gahhghghga ghgahg',
        billType: 'Custom Tier',
        status: 'Active',
      },
      {
        id: 28,
        name: 'Name JKK',
        billType: 'Tier3',
        status: 'Active',
      },
      {
        id: 26,
        name: 'LIlli ghhghghghghhgahhgahhgahghghgahghgahghghgahg HHJK hghghghghghjhhjhjjhajhhjjhjhjhjhjhajhjhjhjhjh',
        billType: 'Tier3',
        status: 'Active',
      },
      {
        id: 25,
        name: 'PAGUU jskdlk',
        billType: 'Tier2',
        status: 'Active',
      },
      {
        id: 20,
        name: 'gxhjcj kxjchgvhj bhn mncbvbn hhhghghgghhghghghghg nsxbdcnmvf tyytytytytytghwtytyytytytytytwytytwytyt',
        billType: 'Tier1',
        status: 'Active',
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/side/talent/',
};
