export default {
  response: {
    count: 4,
    next: 'https://wfm-pydev.ptw.com/users/all/?lessData=true&searchString=&limit=50&offset=50',
    previous: null,
    result: [
      {
        userName: 'bnaina',
        empId: 'Hyd/Ptw-156',
        positionNumber: 'Ind-Hyd-Qua-0014',
        id: 120003207,
        firstName: 'naina',
        lastName: 'b',
        name: 'naina b',
        emailId: 'b.naina@ptw.com',
      },
      {
        userName: 'bnaveena',
        empId: 'PTW-HYD-015',
        positionNumber: 'Ind-Hyd-Qua-0013',
        id: 120003206,
        firstName: 'naveena',
        lastName: 'b',
        name: 'naveena b',
        emailId: 'naveena.b@ptw.com',
      },
      {
        userName: 'Naresh Singh',
        empId: 's/s-122',
        positionNumber: 'Ind-Hyd-Can-0003',
        id: 120003204,
        firstName: 'Naresh',
        lastName: 'Singh',
        name: 'Naresh Singh',
        emailId: 'naresh.singh@ptw.com',
      },
      {
        userName: 'Ramesh Kumar',
        empId: 's/s-121',
        positionNumber: 'Ind-Hyd-Can-0002',
        id: 120003202,
        firstName: 'Ramesh',
        lastName: 'Kumar',
        name: 'Ramesh Kumar',
        emailId: 'ramesh.kumar.123456@ptw.com',
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/wfm/users/all/',
};
