export default {
  response: {
    count: 11,
    next: null,
    previous: null,
    result: [
      {
        id: 120003243,
        name: 'Jaya Surya',
        userName: 'jsurya',
        emailId: 'jayasurya.anisetty@ptw.com',
        roles: 'Default Role, Admin',
        userStudios: [
          {
            id: 2,
            name: 'Jarpa',
          },
        ],
        colorCode: '#fcb900',
        location: 'Hyderabad',
      },
      {
        id: 120003242,
        name: 'Govind Menon',
        userName: 'Govind',
        emailId: 'govind.menon@ptw.com',
        roles: null,
        userStudios: [],
        colorCode: null,
        location: 'Hyderabad',
      },
      {
        id: 120003114,
        name: 'Kiran V',
        userName: 'kiran',
        emailId: 'kiran.valluri@ptw.com',
        roles: 'Default Role',
        userStudios: [],
        colorCode: null,
        location: 'Hyderabad',
      },
      {
        id: 120003112,
        name: 'Sushma Savanth',
        userName: 'sushmasavanth',
        emailId: 'savanth.sushma@ptw.com',
        roles: null,
        userStudios: [],
        colorCode: null,
        location: 'Bangalore',
      },
      {
        id: 120003111,
        name: 'Atul Bhat',
        userName: 'atulbhat',
        emailId: 'atul.bhatt@ptw.com',
        roles: null,
        userStudios: [],
        colorCode: null,
        location: 'Bangalore',
      },
      {
        id: 120003108,
        name: 'Sreeja Vijayakumar',
        userName: 'SreejaV',
        emailId: 'sreeja.vijayakumar@ptw.com',
        roles: 'Default Role, Engineer, Super Admin',
        userStudios: [],
        colorCode: null,
        location: 'Bangalore',
      },
      {
        id: 120003107,
        name: 'Pavitra Hegde',
        userName: 'pavitrahegde',
        emailId: 'pavitra.subramanyahegde@ptw.com',
        roles: 'Default Role, Admin',
        userStudios: [],
        colorCode: null,
        location: 'Bangalore',
      },
      {
        id: 120003104,
        name: 'Vinodh gk',
        userName: 'vinodh',
        emailId: 'vinodh.gk@ptw.com',
        roles: 'Freelance PM',
        userStudios: [],
        colorCode: null,
        location: 'Bangalore',
      },
      {
        id: 23,
        name: 'manikanta kamepalli',
        userName: 'manikanta',
        emailId: 'manikanta.kamepalli@ptw.com',
        roles: null,
        userStudios: [],
        colorCode: null,
        location: 'Hyderabad',
      },
      {
        id: 4,
        name: 'Naveen Alle',
        userName: 'Naveen',
        emailId: 'naveenkumar.reddy@ptw.com',
        roles: 'Admin',
        userStudios: [],
        colorCode: null,
        location: 'Bangalore',
      },
      {
        id: 1,
        name: 'admin admin',
        userName: 'admin',
        emailId: 'admin@admin.com',
        roles: null,
        userStudios: [],
        colorCode: null,
        location: null,
      },
    ],
  },
  endPoint: 'https://gateway.ptw.com/dev/side/users/',
};
