export default {
  response: {
    createdOn: '2021-08-25T07:03:56',
    isActive: true,
    targetId: 1,
    typeId: 34,
    isAdmin: false,
    id: 468,
    createdBy: 3,
    updatedOn: null,
    groupId: null,
    roleId: 1,
    isApprover: false,
    isCrm: false,
    regions: [
      {
        id: 7,
        createdOn: '2021-08-20T12:16:51',
        isActive: true,
        updatedOn: null,
        createdBy: 1,
        name: 'Asia',
      },
      {
        id: 6,
        createdOn: '2021-08-20T12:16:49',
        isActive: true,
        updatedOn: null,
        createdBy: 1,
        name: 'APAC',
      },
      {
        id: 5,
        createdOn: '2021-08-20T12:16:46',
        isActive: true,
        updatedOn: null,
        createdBy: 1,
        name: 'Europe',
      },
      {
        id: 4,
        createdOn: '2021-08-20T12:16:45',
        isActive: true,
        updatedOn: null,
        createdBy: 1,
        name: 'LATAM',
      },
      {
        id: 3,
        createdOn: '2021-08-20T12:16:44',
        isActive: true,
        updatedOn: null,
        createdBy: 1,
        name: 'South America',
      },
      {
        id: 2,
        createdOn: '2021-08-20T12:16:37',
        isActive: true,
        updatedOn: null,
        createdBy: 1,
        name: 'North America',
      },
      {
        id: 1,
        createdOn: '2021-08-20T12:16:30',
        isActive: true,
        updatedOn: null,
        createdBy: 1,
        name: 'EMEA',
      },
    ],
    departments: [],
    name: 'Jaya Surya',
  },
  endPoint: 'https://gateway.ptw.com/dev/crm/users/userDetails/',
};
